/* Linearization */
/* Simulation code for BooleanNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "BooleanNetwork1_functions.h"
#include "BooleanNetwork1_model.h"
#include "BooleanNetwork1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

const char *BooleanNetwork1_linear_model_frame()
{
  return "model linear_BooleanNetwork1\n  parameter Integer n = 0; // states \n  parameter Integer k = 1; // top-level inputs \n  parameter Integer l = 7; // top-level outputs \n"
  "  parameter Real x0[0] = {%s};\n"
  "  parameter Real u0[1] = {%s};\n"
  "  parameter Real A[0,0] = zeros(0,0);%s\n"
  "  parameter Real B[0,1] = zeros(0,1);%s\n"
  "  parameter Real C[7,0] = zeros(7,0);%s\n"
  "  parameter Real D[7,1] = [%s];\n"
  "  Real x[0];\n"
  "  input Real u[1](start= u0);\n"
  "  output Real y[7];\n"
  "\n    Real u_PbooleanStep = u[1];\n    Real y_PQ = y[1];\n  Real y_PQI = y[2];\n  Real y_Py = y[3];\n  Real y_Py1 = y[4];\n  Real y_Py2 = y[5];\n  Real y_Py3 = y[6];\n  Real y_Py4 = y[7];\n  \n"
  "equation\n  der(x) = A * x + B * u;\n  y = C * x + D * u;\nend linear_BooleanNetwork1;\n";
}
#if defined(__cplusplus)
}
#endif

