/* update bound parameters and variable attributes (start, nominal, min, max) */
/* Simulation code for BooleanNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "BooleanNetwork1_functions.h"
#include "BooleanNetwork1_model.h"
#include "BooleanNetwork1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

int BooleanNetwork1_updateBoundVariableAttributes(DATA *data)
{
  TRACE_PUSH
  
  /* min ******************************************************** */
  
  infoStreamPrint(LOG_INIT, 1, "updating min-values");
  if (ACTIVE_STREAM(LOG_INIT)) messageClose(LOG_INIT);
  
  /* max ******************************************************** */
  
  infoStreamPrint(LOG_INIT, 1, "updating max-values");
  if (ACTIVE_STREAM(LOG_INIT)) messageClose(LOG_INIT);
  
  /* nominal **************************************************** */
  
  infoStreamPrint(LOG_INIT, 1, "updating nominal-values");
  if (ACTIVE_STREAM(LOG_INIT)) messageClose(LOG_INIT);
  
  /* start ****************************************************** */
  
  infoStreamPrint(LOG_INIT, 1, "updating start-values");
  if (ACTIVE_STREAM(LOG_INIT)) messageClose(LOG_INIT);
  
  TRACE_POP
  return 0;
}


/*
 equation index: 93
 type: SIMPLE_ASSIGN
 rSFlipFlop._pre._pre_u_start = not rSFlipFlop.Qini
 */
void BooleanNetwork1_eqFunction_93(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,93};
  $PrSFlipFlop$Ppre$Ppre_u_start = (!$PrSFlipFlop$PQini);
  TRACE_POP
}
/*
 equation index: 94
 type: ALGORITHM
 
   assert(sampleTriggerReset.period >= 1e-060, "Variable sampleTriggerReset.period out of [min, max] interval: sampleTriggerReset.period >= 1e-060 has value: " + String(sampleTriggerReset.period, "g"));
 */
void BooleanNetwork1_eqFunction_94(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,94};
  modelica_boolean tmp0;
  static const MMC_DEFSTRINGLIT(tmp1,110,"Variable sampleTriggerReset.period out of [min, max] interval: sampleTriggerReset.period >= 1e-060 has value: ");
  modelica_string tmp2;
  static int tmp3 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp3)
  {
    tmp0 = GreaterEq($PsampleTriggerReset$Pperiod,1e-060);
    if(!tmp0)
    {
      tmp2 = modelica_real_to_modelica_string_format($PsampleTriggerReset$Pperiod, (modelica_string) mmc_strings_len1[103]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp1),tmp2);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Sources.mo",2882,5,2883,36,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nsampleTriggerReset.period >= 1e-060", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp3 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 95
 type: ALGORITHM
 
   assert(sampleTriggerSet.period >= 1e-060, "Variable sampleTriggerSet.period out of [min, max] interval: sampleTriggerSet.period >= 1e-060 has value: " + String(sampleTriggerSet.period, "g"));
 */
void BooleanNetwork1_eqFunction_95(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,95};
  modelica_boolean tmp4;
  static const MMC_DEFSTRINGLIT(tmp5,106,"Variable sampleTriggerSet.period out of [min, max] interval: sampleTriggerSet.period >= 1e-060 has value: ");
  modelica_string tmp6;
  static int tmp7 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp7)
  {
    tmp4 = GreaterEq($PsampleTriggerSet$Pperiod,1e-060);
    if(!tmp4)
    {
      tmp6 = modelica_real_to_modelica_string_format($PsampleTriggerSet$Pperiod, (modelica_string) mmc_strings_len1[103]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp5),tmp6);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Sources.mo",2882,5,2883,36,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nsampleTriggerSet.period >= 1e-060", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp7 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 96
 type: ALGORITHM
 
   assert(set1.nu >= 0, "Variable set1.nu out of [min, max] interval: set1.nu >= 0 has value: " + String(set1.nu, "d"));
 */
void BooleanNetwork1_eqFunction_96(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,96};
  modelica_boolean tmp8;
  static const MMC_DEFSTRINGLIT(tmp9,69,"Variable set1.nu out of [min, max] interval: set1.nu >= 0 has value: ");
  modelica_string tmp10;
  static int tmp11 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp11)
  {
    tmp8 = GreaterEq((modelica_integer)$Pset1$Pnu,(modelica_integer) 0);
    if(!tmp8)
    {
      tmp10 = modelica_integer_to_modelica_string_format((modelica_integer)$Pset1$Pnu, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp9),tmp10);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/MathBoolean.mo",18,3,19,68,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nset1.nu >= 0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp11 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 97
 type: ALGORITHM
 
   assert(or2.nu >= 0, "Variable or2.nu out of [min, max] interval: or2.nu >= 0 has value: " + String(or2.nu, "d"));
 */
void BooleanNetwork1_eqFunction_97(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,97};
  modelica_boolean tmp12;
  static const MMC_DEFSTRINGLIT(tmp13,67,"Variable or2.nu out of [min, max] interval: or2.nu >= 0 has value: ");
  modelica_string tmp14;
  static int tmp15 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp15)
  {
    tmp12 = GreaterEq((modelica_integer)$Por2$Pnu,(modelica_integer) 0);
    if(!tmp12)
    {
      tmp14 = modelica_integer_to_modelica_string_format((modelica_integer)$Por2$Pnu, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp13),tmp14);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Interfaces.mo",1301,5,1302,65,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nor2.nu >= 0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp15 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 98
 type: ALGORITHM
 
   assert(nand1.nu >= 0, "Variable nand1.nu out of [min, max] interval: nand1.nu >= 0 has value: " + String(nand1.nu, "d"));
 */
void BooleanNetwork1_eqFunction_98(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,98};
  modelica_boolean tmp16;
  static const MMC_DEFSTRINGLIT(tmp17,71,"Variable nand1.nu out of [min, max] interval: nand1.nu >= 0 has value: ");
  modelica_string tmp18;
  static int tmp19 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp19)
  {
    tmp16 = GreaterEq((modelica_integer)$Pnand1$Pnu,(modelica_integer) 0);
    if(!tmp16)
    {
      tmp18 = modelica_integer_to_modelica_string_format((modelica_integer)$Pnand1$Pnu, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp17),tmp18);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Interfaces.mo",1301,5,1302,65,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nnand1.nu >= 0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp19 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 99
 type: ALGORITHM
 
   assert(xor1.nu >= 0, "Variable xor1.nu out of [min, max] interval: xor1.nu >= 0 has value: " + String(xor1.nu, "d"));
 */
void BooleanNetwork1_eqFunction_99(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,99};
  modelica_boolean tmp20;
  static const MMC_DEFSTRINGLIT(tmp21,69,"Variable xor1.nu out of [min, max] interval: xor1.nu >= 0 has value: ");
  modelica_string tmp22;
  static int tmp23 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp23)
  {
    tmp20 = GreaterEq((modelica_integer)$Pxor1$Pnu,(modelica_integer) 0);
    if(!tmp20)
    {
      tmp22 = modelica_integer_to_modelica_string_format((modelica_integer)$Pxor1$Pnu, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp21),tmp22);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Interfaces.mo",1301,5,1302,65,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nxor1.nu >= 0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp23 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 100
 type: ALGORITHM
 
   assert(or1.nu >= 0, "Variable or1.nu out of [min, max] interval: or1.nu >= 0 has value: " + String(or1.nu, "d"));
 */
void BooleanNetwork1_eqFunction_100(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,100};
  modelica_boolean tmp24;
  static const MMC_DEFSTRINGLIT(tmp25,67,"Variable or1.nu out of [min, max] interval: or1.nu >= 0 has value: ");
  modelica_string tmp26;
  static int tmp27 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp27)
  {
    tmp24 = GreaterEq((modelica_integer)$Por1$Pnu,(modelica_integer) 0);
    if(!tmp24)
    {
      tmp26 = modelica_integer_to_modelica_string_format((modelica_integer)$Por1$Pnu, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp25),tmp26);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Interfaces.mo",1301,5,1302,65,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nor1.nu >= 0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp27 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 101
 type: ALGORITHM
 
   assert(booleanPulse2.period >= 1e-060, "Variable booleanPulse2.period out of [min, max] interval: booleanPulse2.period >= 1e-060 has value: " + String(booleanPulse2.period, "g"));
 */
void BooleanNetwork1_eqFunction_101(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,101};
  modelica_boolean tmp28;
  static const MMC_DEFSTRINGLIT(tmp29,100,"Variable booleanPulse2.period out of [min, max] interval: booleanPulse2.period >= 1e-060 has value: ");
  modelica_string tmp30;
  static int tmp31 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp31)
  {
    tmp28 = GreaterEq($PbooleanPulse2$Pperiod,1e-060);
    if(!tmp28)
    {
      tmp30 = modelica_real_to_modelica_string_format($PbooleanPulse2$Pperiod, (modelica_string) mmc_strings_len1[103]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp29),tmp30);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Sources.mo",2790,5,2791,39,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nbooleanPulse2.period >= 1e-060", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp31 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 102
 type: ALGORITHM
 
   assert(booleanPulse2.width >= 1e-060 and booleanPulse2.width <= 100.0, "Variable booleanPulse2.width out of [min, max] interval: booleanPulse2.width >= 1e-060 and booleanPulse2.width <= 100.0 has value: " + String(booleanPulse2.width, "g"));
 */
void BooleanNetwork1_eqFunction_102(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,102};
  modelica_boolean tmp32;
  modelica_boolean tmp33;
  static const MMC_DEFSTRINGLIT(tmp34,131,"Variable booleanPulse2.width out of [min, max] interval: booleanPulse2.width >= 1e-060 and booleanPulse2.width <= 100.0 has value: ");
  modelica_string tmp35;
  static int tmp36 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp36)
  {
    tmp32 = GreaterEq($PbooleanPulse2$Pwidth,1e-060);
    tmp33 = LessEq($PbooleanPulse2$Pwidth,100.0);
    if(!(tmp32 && tmp33))
    {
      tmp35 = modelica_real_to_modelica_string_format($PbooleanPulse2$Pwidth, (modelica_string) mmc_strings_len1[103]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp34),tmp35);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Sources.mo",2787,5,2789,58,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nbooleanPulse2.width >= 1e-060 and booleanPulse2.width <= 100.0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp36 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 103
 type: ALGORITHM
 
   assert(booleanPulse1.period >= 1e-060, "Variable booleanPulse1.period out of [min, max] interval: booleanPulse1.period >= 1e-060 has value: " + String(booleanPulse1.period, "g"));
 */
void BooleanNetwork1_eqFunction_103(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,103};
  modelica_boolean tmp37;
  static const MMC_DEFSTRINGLIT(tmp38,100,"Variable booleanPulse1.period out of [min, max] interval: booleanPulse1.period >= 1e-060 has value: ");
  modelica_string tmp39;
  static int tmp40 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp40)
  {
    tmp37 = GreaterEq($PbooleanPulse1$Pperiod,1e-060);
    if(!tmp37)
    {
      tmp39 = modelica_real_to_modelica_string_format($PbooleanPulse1$Pperiod, (modelica_string) mmc_strings_len1[103]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp38),tmp39);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Sources.mo",2790,5,2791,39,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nbooleanPulse1.period >= 1e-060", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp40 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 104
 type: ALGORITHM
 
   assert(booleanPulse1.width >= 1e-060 and booleanPulse1.width <= 100.0, "Variable booleanPulse1.width out of [min, max] interval: booleanPulse1.width >= 1e-060 and booleanPulse1.width <= 100.0 has value: " + String(booleanPulse1.width, "g"));
 */
void BooleanNetwork1_eqFunction_104(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,104};
  modelica_boolean tmp41;
  modelica_boolean tmp42;
  static const MMC_DEFSTRINGLIT(tmp43,131,"Variable booleanPulse1.width out of [min, max] interval: booleanPulse1.width >= 1e-060 and booleanPulse1.width <= 100.0 has value: ");
  modelica_string tmp44;
  static int tmp45 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp45)
  {
    tmp41 = GreaterEq($PbooleanPulse1$Pwidth,1e-060);
    tmp42 = LessEq($PbooleanPulse1$Pwidth,100.0);
    if(!(tmp41 && tmp42))
    {
      tmp44 = modelica_real_to_modelica_string_format($PbooleanPulse1$Pwidth, (modelica_string) mmc_strings_len1[103]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp43),tmp44);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Sources.mo",2787,5,2789,58,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nbooleanPulse1.width >= 1e-060 and booleanPulse1.width <= 100.0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp45 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 105
 type: ALGORITHM
 
   assert(and1.nu >= 0, "Variable and1.nu out of [min, max] interval: and1.nu >= 0 has value: " + String(and1.nu, "d"));
 */
void BooleanNetwork1_eqFunction_105(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,105};
  modelica_boolean tmp46;
  static const MMC_DEFSTRINGLIT(tmp47,69,"Variable and1.nu out of [min, max] interval: and1.nu >= 0 has value: ");
  modelica_string tmp48;
  static int tmp49 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp49)
  {
    tmp46 = GreaterEq((modelica_integer)$Pand1$Pnu,(modelica_integer) 0);
    if(!tmp46)
    {
      tmp48 = modelica_integer_to_modelica_string_format((modelica_integer)$Pand1$Pnu, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp47),tmp48);
      FILE_INFO info = {"C:/OpenModelica/trunk/build/lib/omlibrary/Modelica 3.2.1/Blocks/Interfaces.mo",1301,5,1302,65,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f\nand1.nu >= 0", time);
      omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      tmp49 = 1;
    }
  }
  TRACE_POP
}
int BooleanNetwork1_updateBoundParameters(DATA *data)
{
  TRACE_PUSH
  BooleanNetwork1_eqFunction_93(data);

  BooleanNetwork1_eqFunction_94(data);

  BooleanNetwork1_eqFunction_95(data);

  BooleanNetwork1_eqFunction_96(data);

  BooleanNetwork1_eqFunction_97(data);

  BooleanNetwork1_eqFunction_98(data);

  BooleanNetwork1_eqFunction_99(data);

  BooleanNetwork1_eqFunction_100(data);

  BooleanNetwork1_eqFunction_101(data);

  BooleanNetwork1_eqFunction_102(data);

  BooleanNetwork1_eqFunction_103(data);

  BooleanNetwork1_eqFunction_104(data);

  BooleanNetwork1_eqFunction_105(data);
  
  TRACE_POP
  return 0;
}

#if defined(__cplusplus)
}
#endif

