/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for BooleanNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "BooleanNetwork1_functions.h"
#include "BooleanNetwork1_model.h"
#include "BooleanNetwork1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void BooleanNetwork1_function_initSample(DATA *data)
{
  long i=0;
  /* $P$sample1 */
  data->modelData.samplesInfo[i].index = 1;
  data->modelData.samplesInfo[i].start = $PbooleanPulse1$PstartTime;
  data->modelData.samplesInfo[i].interval = $PbooleanPulse1$Pperiod;
  assertStreamPrint(threadData,data->modelData.samplesInfo[i].interval > 0.0, "sample-interval <= 0.0");
  i++;
  /* $P$sample2 */
  data->modelData.samplesInfo[i].index = 2;
  data->modelData.samplesInfo[i].start = $PbooleanPulse2$PstartTime;
  data->modelData.samplesInfo[i].interval = $PbooleanPulse2$Pperiod;
  assertStreamPrint(threadData,data->modelData.samplesInfo[i].interval > 0.0, "sample-interval <= 0.0");
  i++;
  /* $P$sample3 */
  data->modelData.samplesInfo[i].index = 3;
  data->modelData.samplesInfo[i].start = $PsampleTriggerSet$PstartTime;
  data->modelData.samplesInfo[i].interval = $PsampleTriggerSet$Pperiod;
  assertStreamPrint(threadData,data->modelData.samplesInfo[i].interval > 0.0, "sample-interval <= 0.0");
  i++;
  /* $P$sample4 */
  data->modelData.samplesInfo[i].index = 4;
  data->modelData.samplesInfo[i].start = $PsampleTriggerReset$PstartTime;
  data->modelData.samplesInfo[i].interval = $PsampleTriggerReset$Pperiod;
  assertStreamPrint(threadData,data->modelData.samplesInfo[i].interval > 0.0, "sample-interval <= 0.0");
  i++;
}

const char *BooleanNetwork1_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"time >= pre(booleanTable.nextTime)",
  "time >= onDelay.t_next",
  "time >= booleanPulse1.pulsStart and time < booleanPulse1.pulsStart + 0.2",
  "time >= booleanPulse2.pulsStart and time < booleanPulse2.pulsStart + 0.8"};
  static const int occurEqs0[] = {1,62};
  static const int occurEqs1[] = {1,63};
  static const int occurEqs2[] = {1,61};
  static const int occurEqs3[] = {1,63};
  static const int *occurEqs[] = {occurEqs0,occurEqs1,occurEqs2,occurEqs3};
  *out_EquationIndexes = (int*) occurEqs[i];
  return res[i];
}

/* forwarded equations */
extern void BooleanNetwork1_eqFunction_65(DATA* data);
extern void BooleanNetwork1_eqFunction_66(DATA* data);
extern void BooleanNetwork1_eqFunction_67(DATA* data);
extern void BooleanNetwork1_eqFunction_70(DATA* data);
extern void BooleanNetwork1_eqFunction_71(DATA* data);

int BooleanNetwork1_function_ZeroCrossingsEquations(DATA *data)
{
  TRACE_PUSH
  
  data->simulationInfo.callStatistics.functionZeroCrossingsEquations++;
  
  data->simulationInfo.discreteCall = 0;
  BooleanNetwork1_eqFunction_65(data);

  BooleanNetwork1_eqFunction_66(data);

  BooleanNetwork1_eqFunction_67(data);

  BooleanNetwork1_eqFunction_70(data);

  BooleanNetwork1_eqFunction_71(data);
  
  TRACE_POP
  return 0;
}

int BooleanNetwork1_function_ZeroCrossings(DATA *data, double *gout)
{
  TRACE_PUSH
  modelica_boolean tmp1054;
  modelica_boolean tmp1055;
  modelica_boolean tmp1056;
  modelica_boolean tmp1057;
  modelica_boolean tmp1058;
  modelica_boolean tmp1059;
  
  data->simulationInfo.callStatistics.functionZeroCrossings++;
  
  tmp1054 = GreaterEqZC(time, $P$PRE$PbooleanTable$PnextTime, data->simulationInfo.storedRelations[0]);
  gout[0] = (tmp1054) ? 1 : -1;
  tmp1055 = GreaterEqZC(time, $PonDelay$Pt_next, data->simulationInfo.storedRelations[1]);
  gout[1] = (tmp1055) ? 1 : -1;
  tmp1056 = GreaterEqZC(time, $PbooleanPulse1$PpulsStart, data->simulationInfo.storedRelations[2]);
  tmp1057 = LessZC(time, ($PbooleanPulse1$PpulsStart + 0.2), data->simulationInfo.storedRelations[3]);
  gout[2] = ((tmp1056 && tmp1057)) ? 1 : -1;
  tmp1058 = GreaterEqZC(time, $PbooleanPulse2$PpulsStart, data->simulationInfo.storedRelations[4]);
  tmp1059 = LessZC(time, ($PbooleanPulse2$PpulsStart + 0.8), data->simulationInfo.storedRelations[5]);
  gout[3] = ((tmp1058 && tmp1059)) ? 1 : -1;
  
  TRACE_POP
  return 0;
}

const char *BooleanNetwork1_relationDescription(int i)
{
  const char *res[] = {"time >= pre(booleanTable.nextTime)",
  "time >= onDelay.t_next",
  "time >= booleanPulse1.pulsStart",
  "time < booleanPulse1.pulsStart + 0.2",
  "time >= booleanPulse2.pulsStart",
  "time < booleanPulse2.pulsStart + 0.8"};
  return res[i];
}

int BooleanNetwork1_function_updateRelations(DATA *data, int evalforZeroCross)
{
  TRACE_PUSH
  modelica_boolean tmp1060;
  modelica_boolean tmp1061;
  modelica_boolean tmp1062;
  modelica_boolean tmp1063;
  modelica_boolean tmp1064;
  modelica_boolean tmp1065;
  
  
  if(evalforZeroCross)
  {
    tmp1060 = GreaterEqZC(time, $P$PRE$PbooleanTable$PnextTime, data->simulationInfo.storedRelations[0]);
    data->simulationInfo.relations[0] = tmp1060;
    tmp1061 = GreaterEqZC(time, $PonDelay$Pt_next, data->simulationInfo.storedRelations[1]);
    data->simulationInfo.relations[1] = tmp1061;
    tmp1062 = GreaterEqZC(time, $PbooleanPulse1$PpulsStart, data->simulationInfo.storedRelations[2]);
    data->simulationInfo.relations[2] = tmp1062;
    tmp1063 = LessZC(time, ($PbooleanPulse1$PpulsStart + 0.2), data->simulationInfo.storedRelations[3]);
    data->simulationInfo.relations[3] = tmp1063;
    tmp1064 = GreaterEqZC(time, $PbooleanPulse2$PpulsStart, data->simulationInfo.storedRelations[4]);
    data->simulationInfo.relations[4] = tmp1064;
    tmp1065 = LessZC(time, ($PbooleanPulse2$PpulsStart + 0.8), data->simulationInfo.storedRelations[5]);
    data->simulationInfo.relations[5] = tmp1065;
  }
  else
  {
    data->simulationInfo.relations[0] = (time >= $P$PRE$PbooleanTable$PnextTime);
    data->simulationInfo.relations[1] = (time >= $PonDelay$Pt_next);
    data->simulationInfo.relations[2] = (time >= $PbooleanPulse1$PpulsStart);
    data->simulationInfo.relations[3] = (time < ($PbooleanPulse1$PpulsStart + 0.2));
    data->simulationInfo.relations[4] = (time >= $PbooleanPulse2$PpulsStart);
    data->simulationInfo.relations[5] = (time < ($PbooleanPulse2$PpulsStart + 0.8));
  }
  
  TRACE_POP
  return 0;
}

int BooleanNetwork1_checkForDiscreteChanges(DATA *data)
{
  TRACE_PUSH
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes at time=%.12g", data->localData[0]->timeValue);
  if($P$whenCondition7 != $P$PRE$P$whenCondition7)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition7 from %d to %d", $P$PRE$P$whenCondition7, $P$whenCondition7);
    needToIterate = 1;
  }
  if($P$whenCondition6 != $P$PRE$P$whenCondition6)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition6 from %d to %d", $P$PRE$P$whenCondition6, $P$whenCondition6);
    needToIterate = 1;
  }
  if($P$whenCondition5 != $P$PRE$P$whenCondition5)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition5 from %d to %d", $P$PRE$P$whenCondition5, $P$whenCondition5);
    needToIterate = 1;
  }
  if($P$whenCondition4 != $P$PRE$P$whenCondition4)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition4 from %d to %d", $P$PRE$P$whenCondition4, $P$whenCondition4);
    needToIterate = 1;
  }
  if($Pand1$Pu$lB1$rB != $P$PRE$Pand1$Pu$lB1$rB)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: and1._u[1] from %d to %d", $P$PRE$Pand1$Pu$lB1$rB, $Pand1$Pu$lB1$rB);
    needToIterate = 1;
  }
  if($PbooleanPulse1$PpulsStart != $P$PRE$PbooleanPulse1$PpulsStart)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: booleanPulse1._pulsStart from %g to %g", $P$PRE$PbooleanPulse1$PpulsStart, $PbooleanPulse1$PpulsStart);
    needToIterate = 1;
  }
  if($PbooleanPulse2$PpulsStart != $P$PRE$PbooleanPulse2$PpulsStart)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: booleanPulse2._pulsStart from %g to %g", $P$PRE$PbooleanPulse2$PpulsStart, $PbooleanPulse2$PpulsStart);
    needToIterate = 1;
  }
  if($Pxor1$Pu$lB1$rB != $P$PRE$Pxor1$Pu$lB1$rB)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: xor1._u[1] from %d to %d", $P$PRE$Pxor1$Pu$lB1$rB, $Pxor1$Pu$lB1$rB);
    needToIterate = 1;
  }
  if($Pnand1$Pu$lB1$rB != $P$PRE$Pnand1$Pu$lB1$rB)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: nand1._u[1] from %d to %d", $P$PRE$Pnand1$Pu$lB1$rB, $Pnand1$Pu$lB1$rB);
    needToIterate = 1;
  }
  if($Por2$Pu$lB1$rB != $P$PRE$Por2$Pu$lB1$rB)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: or2._u[1] from %d to %d", $P$PRE$Por2$Pu$lB1$rB, $Por2$Pu$lB1$rB);
    needToIterate = 1;
  }
  if($Pnor1$Py != $P$PRE$Pnor1$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: nor1._y from %d to %d", $P$PRE$Pnor1$Py, $Pnor1$Py);
    needToIterate = 1;
  }
  if($Prising$Pu != $P$PRE$Prising$Pu)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rising._u from %d to %d", $P$PRE$Prising$Pu, $Prising$Pu);
    needToIterate = 1;
  }
  if($Pset1$Py != $P$PRE$Pset1$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: set1._y from %d to %d", $P$PRE$Pset1$Py, $Pset1$Py);
    needToIterate = 1;
  }
  if($Pset1$PfirstActiveIndex != $P$PRE$Pset1$PfirstActiveIndex)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: set1._firstActiveIndex from %ld to %ld", $P$PRE$Pset1$PfirstActiveIndex, $Pset1$PfirstActiveIndex);
    needToIterate = 1;
  }
  if($Pset1$Pu$lB1$rB != $P$PRE$Pset1$Pu$lB1$rB)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: set1._u[1] from %d to %d", $P$PRE$Pset1$Pu$lB1$rB, $Pset1$Pu$lB1$rB);
    needToIterate = 1;
  }
  if($Pset1$Pu$lB2$rB != $P$PRE$Pset1$Pu$lB2$rB)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: set1._u[2] from %d to %d", $P$PRE$Pset1$Pu$lB2$rB, $Pset1$Pu$lB2$rB);
    needToIterate = 1;
  }
  if($Pfalling$Pnot_u != $P$PRE$Pfalling$Pnot_u)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: falling._not_u from %d to %d", $P$PRE$Pfalling$Pnot_u, $Pfalling$Pnot_u);
    needToIterate = 1;
  }
  if($Pchanging$Pu != $P$PRE$Pchanging$Pu)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: changing._u from %d to %d", $P$PRE$Pchanging$Pu, $Pchanging$Pu);
    needToIterate = 1;
  }
  if($Pchanging$Py != $P$PRE$Pchanging$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: changing._y from %d to %d", $P$PRE$Pchanging$Py, $Pchanging$Py);
    needToIterate = 1;
  }
  if($PtriggeredAdd$Py != $P$PRE$PtriggeredAdd$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: triggeredAdd._y from %ld to %ld", $P$PRE$PtriggeredAdd$Py, $PtriggeredAdd$Py);
    needToIterate = 1;
  }
  if($Py != $P$PRE$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: y from %d to %d", $P$PRE$Py, $Py);
    needToIterate = 1;
  }
  if($Py2 != $P$PRE$Py2)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: y2 from %d to %d", $P$PRE$Py2, $Py2);
    needToIterate = 1;
  }
  if($Py3 != $P$PRE$Py3)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: y3 from %d to %d", $P$PRE$Py3, $Py3);
    needToIterate = 1;
  }
  if($Py1 != $P$PRE$Py1)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: y1 from %ld to %ld", $P$PRE$Py1, $Py1);
    needToIterate = 1;
  }
  if($P$whenCondition1 != $P$PRE$P$whenCondition1)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition1 from %d to %d", $P$PRE$P$whenCondition1, $P$whenCondition1);
    needToIterate = 1;
  }
  if($P$whenCondition2 != $P$PRE$P$whenCondition2)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition2 from %d to %d", $P$PRE$P$whenCondition2, $P$whenCondition2);
    needToIterate = 1;
  }
  if($P$whenCondition3 != $P$PRE$P$whenCondition3)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition3 from %d to %d", $P$PRE$P$whenCondition3, $P$whenCondition3);
    needToIterate = 1;
  }
  if($PonDelay$Pu != $P$PRE$PonDelay$Pu)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: onDelay._u from %d to %d", $P$PRE$PonDelay$Pu, $PonDelay$Pu);
    needToIterate = 1;
  }
  if($PonDelay$PdelaySignal != $P$PRE$PonDelay$PdelaySignal)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: onDelay._delaySignal from %d to %d", $P$PRE$PonDelay$PdelaySignal, $PonDelay$PdelaySignal);
    needToIterate = 1;
  }
  if($PonDelay$Pt_next != $P$PRE$PonDelay$Pt_next)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: onDelay._t_next from %g to %g", $P$PRE$PonDelay$Pt_next, $PonDelay$Pt_next);
    needToIterate = 1;
  }
  if($PbooleanTable$Py != $P$PRE$PbooleanTable$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: booleanTable._y from %d to %d", $P$PRE$PbooleanTable$Py, $PbooleanTable$Py);
    needToIterate = 1;
  }
  if($PbooleanTable$PnextTime != $P$PRE$PbooleanTable$PnextTime)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: booleanTable._nextTime from %g to %g", $P$PRE$PbooleanTable$PnextTime, $PbooleanTable$PnextTime);
    needToIterate = 1;
  }
  if($PbooleanTable$Pindex != $P$PRE$PbooleanTable$Pindex)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: booleanTable._index from %ld to %ld", $P$PRE$PbooleanTable$Pindex, $PbooleanTable$Pindex);
    needToIterate = 1;
  }
  if($Py4 != $P$PRE$Py4)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: y4 from %d to %d", $P$PRE$Py4, $Py4);
    needToIterate = 1;
  }
  if($PrSFlipFlop$PS != $P$PRE$PrSFlipFlop$PS)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rSFlipFlop._S from %d to %d", $P$PRE$PrSFlipFlop$PS, $PrSFlipFlop$PS);
    needToIterate = 1;
  }
  if($PrSFlipFlop$PR != $P$PRE$PrSFlipFlop$PR)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rSFlipFlop._R from %d to %d", $P$PRE$PrSFlipFlop$PR, $PrSFlipFlop$PR);
    needToIterate = 1;
  }
  if($PrSFlipFlop$Ppre$Pu != $P$PRE$PrSFlipFlop$Ppre$Pu)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rSFlipFlop._pre._u from %d to %d", $P$PRE$PrSFlipFlop$Ppre$Pu, $PrSFlipFlop$Ppre$Pu);
    needToIterate = 1;
  }
  if($PQ != $P$PRE$PQ)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: Q from %d to %d", $P$PRE$PQ, $PQ);
    needToIterate = 1;
  }
  if($PQI != $P$PRE$PQI)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: QI from %d to %d", $P$PRE$PQI, $PQI);
    needToIterate = 1;
  }
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  TRACE_POP
  return needToIterate;
}

#if defined(__cplusplus)
}
#endif

