/* Simulation code for BooleanNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */
#define time data->localData[0]->timeValue

/* States */

/* StatesDerivatives */

/* Non Discrete Real Algebraic Vars */

/* Discrete Real Algebraic Vars */
/* booleanPulse1.pulsStart */
#define _$PbooleanPulse1$PpulsStart(i) data->localData[i]->realVars[0]
#define $PbooleanPulse1$PpulsStart _$PbooleanPulse1$PpulsStart(0)
#define $P$PRE$PbooleanPulse1$PpulsStart data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$PbooleanPulse1$PpulsStart data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse1$PpulsStart $P$ATTRIBUTE$PbooleanPulse1$PpulsStart
#define $PbooleanPulse1$PpulsStart__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$PbooleanPulse1$PpulsStart__varInfo data->modelData.realVarsData[0].info
#define _$P$PRE$PbooleanPulse1$PpulsStart(i) $P$PRE$PbooleanPulse1$PpulsStart


/* booleanPulse2.pulsStart */
#define _$PbooleanPulse2$PpulsStart(i) data->localData[i]->realVars[1]
#define $PbooleanPulse2$PpulsStart _$PbooleanPulse2$PpulsStart(0)
#define $P$PRE$PbooleanPulse2$PpulsStart data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$PbooleanPulse2$PpulsStart data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse2$PpulsStart $P$ATTRIBUTE$PbooleanPulse2$PpulsStart
#define $PbooleanPulse2$PpulsStart__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$PbooleanPulse2$PpulsStart__varInfo data->modelData.realVarsData[1].info
#define _$P$PRE$PbooleanPulse2$PpulsStart(i) $P$PRE$PbooleanPulse2$PpulsStart


/* booleanTable.nextTime */
#define _$PbooleanTable$PnextTime(i) data->localData[i]->realVars[2]
#define $PbooleanTable$PnextTime _$PbooleanTable$PnextTime(0)
#define $P$PRE$PbooleanTable$PnextTime data->simulationInfo.realVarsPre[2]
#define $P$ATTRIBUTE$PbooleanTable$PnextTime data->modelData.realVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$PnextTime $P$ATTRIBUTE$PbooleanTable$PnextTime
#define $PbooleanTable$PnextTime__varInfo data->modelData.realVarsData[2].info
#define $P$PRE$PbooleanTable$PnextTime__varInfo data->modelData.realVarsData[2].info
#define _$P$PRE$PbooleanTable$PnextTime(i) $P$PRE$PbooleanTable$PnextTime


/* onDelay.t_next */
#define _$PonDelay$Pt_next(i) data->localData[i]->realVars[3]
#define $PonDelay$Pt_next _$PonDelay$Pt_next(0)
#define $P$PRE$PonDelay$Pt_next data->simulationInfo.realVarsPre[3]
#define $P$ATTRIBUTE$PonDelay$Pt_next data->modelData.realVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PonDelay$Pt_next $P$ATTRIBUTE$PonDelay$Pt_next
#define $PonDelay$Pt_next__varInfo data->modelData.realVarsData[3].info
#define $P$PRE$PonDelay$Pt_next__varInfo data->modelData.realVarsData[3].info
#define _$P$PRE$PonDelay$Pt_next(i) $P$PRE$PonDelay$Pt_next


/* Nonlinear Constraints For Dyn. Optimization */

/* Nonlinear Final Constraints For Dyn. Optimization */

/* Algebraic Parameter */
/* booleanPulse1.Twidth */
#define $PbooleanPulse1$PTwidth data->simulationInfo.realParameter[0]
#define _$PbooleanPulse1$PTwidth(i) $PbooleanPulse1$PTwidth
#define $P$ATTRIBUTE$PbooleanPulse1$PTwidth data->modelData.realParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse1$PTwidth $P$ATTRIBUTE$PbooleanPulse1$PTwidth
#define $PbooleanPulse1$PTwidth__varInfo data->modelData.realParameterData[0].info


/* booleanPulse1.period */
#define $PbooleanPulse1$Pperiod data->simulationInfo.realParameter[1]
#define _$PbooleanPulse1$Pperiod(i) $PbooleanPulse1$Pperiod
#define $P$ATTRIBUTE$PbooleanPulse1$Pperiod data->modelData.realParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse1$Pperiod $P$ATTRIBUTE$PbooleanPulse1$Pperiod
#define $PbooleanPulse1$Pperiod__varInfo data->modelData.realParameterData[1].info


/* booleanPulse1.startTime */
#define $PbooleanPulse1$PstartTime data->simulationInfo.realParameter[2]
#define _$PbooleanPulse1$PstartTime(i) $PbooleanPulse1$PstartTime
#define $P$ATTRIBUTE$PbooleanPulse1$PstartTime data->modelData.realParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse1$PstartTime $P$ATTRIBUTE$PbooleanPulse1$PstartTime
#define $PbooleanPulse1$PstartTime__varInfo data->modelData.realParameterData[2].info


/* booleanPulse1.width */
#define $PbooleanPulse1$Pwidth data->simulationInfo.realParameter[3]
#define _$PbooleanPulse1$Pwidth(i) $PbooleanPulse1$Pwidth
#define $P$ATTRIBUTE$PbooleanPulse1$Pwidth data->modelData.realParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse1$Pwidth $P$ATTRIBUTE$PbooleanPulse1$Pwidth
#define $PbooleanPulse1$Pwidth__varInfo data->modelData.realParameterData[3].info


/* booleanPulse2.Twidth */
#define $PbooleanPulse2$PTwidth data->simulationInfo.realParameter[4]
#define _$PbooleanPulse2$PTwidth(i) $PbooleanPulse2$PTwidth
#define $P$ATTRIBUTE$PbooleanPulse2$PTwidth data->modelData.realParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse2$PTwidth $P$ATTRIBUTE$PbooleanPulse2$PTwidth
#define $PbooleanPulse2$PTwidth__varInfo data->modelData.realParameterData[4].info


/* booleanPulse2.period */
#define $PbooleanPulse2$Pperiod data->simulationInfo.realParameter[5]
#define _$PbooleanPulse2$Pperiod(i) $PbooleanPulse2$Pperiod
#define $P$ATTRIBUTE$PbooleanPulse2$Pperiod data->modelData.realParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse2$Pperiod $P$ATTRIBUTE$PbooleanPulse2$Pperiod
#define $PbooleanPulse2$Pperiod__varInfo data->modelData.realParameterData[5].info


/* booleanPulse2.startTime */
#define $PbooleanPulse2$PstartTime data->simulationInfo.realParameter[6]
#define _$PbooleanPulse2$PstartTime(i) $PbooleanPulse2$PstartTime
#define $P$ATTRIBUTE$PbooleanPulse2$PstartTime data->modelData.realParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse2$PstartTime $P$ATTRIBUTE$PbooleanPulse2$PstartTime
#define $PbooleanPulse2$PstartTime__varInfo data->modelData.realParameterData[6].info


/* booleanPulse2.width */
#define $PbooleanPulse2$Pwidth data->simulationInfo.realParameter[7]
#define _$PbooleanPulse2$Pwidth(i) $PbooleanPulse2$Pwidth
#define $P$ATTRIBUTE$PbooleanPulse2$Pwidth data->modelData.realParameterData[7].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanPulse2$Pwidth $P$ATTRIBUTE$PbooleanPulse2$Pwidth
#define $PbooleanPulse2$Pwidth__varInfo data->modelData.realParameterData[7].info


/* booleanTable.table */
#define $PbooleanTable$Ptable data->simulationInfo.realParameter[8]

#define $PbooleanTable$Ptable_index(i_1)    (&$PbooleanTable$Ptable)[calc_base_index_dims_subs(1, 7, i_1)]

/* booleanTable.table[1] */
#define $PbooleanTable$Ptable$lB1$rB data->simulationInfo.realParameter[8]
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB1$rB data->modelData.realParameterData[8].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB1$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB1$rB
#define _$PbooleanTable$Ptable$lB1$rB(i) $PbooleanTable$Ptable$lB1$rB
#define $PbooleanTable$Ptable$lB1$rB__varInfo data->modelData.realParameterData[8].info


/* booleanTable.table[2] */
#define $PbooleanTable$Ptable$lB2$rB data->simulationInfo.realParameter[9]
#define _$PbooleanTable$Ptable$lB2$rB(i) $PbooleanTable$Ptable$lB2$rB
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB2$rB data->modelData.realParameterData[9].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB2$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB2$rB
#define $PbooleanTable$Ptable$lB2$rB__varInfo data->modelData.realParameterData[9].info


/* booleanTable.table[3] */
#define $PbooleanTable$Ptable$lB3$rB data->simulationInfo.realParameter[10]
#define _$PbooleanTable$Ptable$lB3$rB(i) $PbooleanTable$Ptable$lB3$rB
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB3$rB data->modelData.realParameterData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB3$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB3$rB
#define $PbooleanTable$Ptable$lB3$rB__varInfo data->modelData.realParameterData[10].info


/* booleanTable.table[4] */
#define $PbooleanTable$Ptable$lB4$rB data->simulationInfo.realParameter[11]
#define _$PbooleanTable$Ptable$lB4$rB(i) $PbooleanTable$Ptable$lB4$rB
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB4$rB data->modelData.realParameterData[11].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB4$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB4$rB
#define $PbooleanTable$Ptable$lB4$rB__varInfo data->modelData.realParameterData[11].info


/* booleanTable.table[5] */
#define $PbooleanTable$Ptable$lB5$rB data->simulationInfo.realParameter[12]
#define _$PbooleanTable$Ptable$lB5$rB(i) $PbooleanTable$Ptable$lB5$rB
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB5$rB data->modelData.realParameterData[12].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB5$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB5$rB
#define $PbooleanTable$Ptable$lB5$rB__varInfo data->modelData.realParameterData[12].info


/* booleanTable.table[6] */
#define $PbooleanTable$Ptable$lB6$rB data->simulationInfo.realParameter[13]
#define _$PbooleanTable$Ptable$lB6$rB(i) $PbooleanTable$Ptable$lB6$rB
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB6$rB data->modelData.realParameterData[13].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB6$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB6$rB
#define $PbooleanTable$Ptable$lB6$rB__varInfo data->modelData.realParameterData[13].info


/* booleanTable.table[7] */
#define $PbooleanTable$Ptable$lB7$rB data->simulationInfo.realParameter[14]
#define _$PbooleanTable$Ptable$lB7$rB(i) $PbooleanTable$Ptable$lB7$rB
#define $P$ATTRIBUTE$PbooleanTable$Ptable$lB7$rB data->modelData.realParameterData[14].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Ptable$lB7$rB $P$ATTRIBUTE$PbooleanTable$Ptable$lB7$rB
#define $PbooleanTable$Ptable$lB7$rB__varInfo data->modelData.realParameterData[14].info


/* onDelay.delayTime */
#define $PonDelay$PdelayTime data->simulationInfo.realParameter[15]
#define _$PonDelay$PdelayTime(i) $PonDelay$PdelayTime
#define $P$ATTRIBUTE$PonDelay$PdelayTime data->modelData.realParameterData[15].attribute
#define $P$ATTRIBUTE$P$PRE$PonDelay$PdelayTime $P$ATTRIBUTE$PonDelay$PdelayTime
#define $PonDelay$PdelayTime__varInfo data->modelData.realParameterData[15].info


/* sampleTriggerReset.period */
#define $PsampleTriggerReset$Pperiod data->simulationInfo.realParameter[16]
#define _$PsampleTriggerReset$Pperiod(i) $PsampleTriggerReset$Pperiod
#define $P$ATTRIBUTE$PsampleTriggerReset$Pperiod data->modelData.realParameterData[16].attribute
#define $P$ATTRIBUTE$P$PRE$PsampleTriggerReset$Pperiod $P$ATTRIBUTE$PsampleTriggerReset$Pperiod
#define $PsampleTriggerReset$Pperiod__varInfo data->modelData.realParameterData[16].info


/* sampleTriggerReset.startTime */
#define $PsampleTriggerReset$PstartTime data->simulationInfo.realParameter[17]
#define _$PsampleTriggerReset$PstartTime(i) $PsampleTriggerReset$PstartTime
#define $P$ATTRIBUTE$PsampleTriggerReset$PstartTime data->modelData.realParameterData[17].attribute
#define $P$ATTRIBUTE$P$PRE$PsampleTriggerReset$PstartTime $P$ATTRIBUTE$PsampleTriggerReset$PstartTime
#define $PsampleTriggerReset$PstartTime__varInfo data->modelData.realParameterData[17].info


/* sampleTriggerSet.period */
#define $PsampleTriggerSet$Pperiod data->simulationInfo.realParameter[18]
#define _$PsampleTriggerSet$Pperiod(i) $PsampleTriggerSet$Pperiod
#define $P$ATTRIBUTE$PsampleTriggerSet$Pperiod data->modelData.realParameterData[18].attribute
#define $P$ATTRIBUTE$P$PRE$PsampleTriggerSet$Pperiod $P$ATTRIBUTE$PsampleTriggerSet$Pperiod
#define $PsampleTriggerSet$Pperiod__varInfo data->modelData.realParameterData[18].info


/* sampleTriggerSet.startTime */
#define $PsampleTriggerSet$PstartTime data->simulationInfo.realParameter[19]
#define _$PsampleTriggerSet$PstartTime(i) $PsampleTriggerSet$PstartTime
#define $P$ATTRIBUTE$PsampleTriggerSet$PstartTime data->modelData.realParameterData[19].attribute
#define $P$ATTRIBUTE$P$PRE$PsampleTriggerSet$PstartTime $P$ATTRIBUTE$PsampleTriggerSet$PstartTime
#define $PsampleTriggerSet$PstartTime__varInfo data->modelData.realParameterData[19].info


/* External Objects */

/* Algebraic Integer Vars */
/* booleanTable.index */
#define _$PbooleanTable$Pindex(i) data->localData[i]->integerVars[0]
#define $PbooleanTable$Pindex _$PbooleanTable$Pindex(0)
#define $P$PRE$PbooleanTable$Pindex data->simulationInfo.integerVarsPre[0]
#define $P$ATTRIBUTE$PbooleanTable$Pindex data->modelData.integerVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Pindex $P$ATTRIBUTE$PbooleanTable$Pindex
#define $PbooleanTable$Pindex__varInfo data->modelData.integerVarsData[0].info
#define $P$PRE$PbooleanTable$Pindex__varInfo data->modelData.integerVarsData[0].info
#define _$P$PRE$PbooleanTable$Pindex(i) $P$PRE$PbooleanTable$Pindex


/* set1.firstActiveIndex */
#define _$Pset1$PfirstActiveIndex(i) data->localData[i]->integerVars[1]
#define $Pset1$PfirstActiveIndex _$Pset1$PfirstActiveIndex(0)
#define $P$PRE$Pset1$PfirstActiveIndex data->simulationInfo.integerVarsPre[1]
#define $P$ATTRIBUTE$Pset1$PfirstActiveIndex data->modelData.integerVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$PfirstActiveIndex $P$ATTRIBUTE$Pset1$PfirstActiveIndex
#define $Pset1$PfirstActiveIndex__varInfo data->modelData.integerVarsData[1].info
#define $P$PRE$Pset1$PfirstActiveIndex__varInfo data->modelData.integerVarsData[1].info
#define _$P$PRE$Pset1$PfirstActiveIndex(i) $P$PRE$Pset1$PfirstActiveIndex


/* showValue1.number */
#define _$PshowValue1$Pnumber(i) data->localData[i]->integerVars[2]
#define $PshowValue1$Pnumber _$PshowValue1$Pnumber(0)
#define $P$PRE$PshowValue1$Pnumber data->simulationInfo.integerVarsPre[2]
#define $P$ATTRIBUTE$PshowValue1$Pnumber data->modelData.integerVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue1$Pnumber $P$ATTRIBUTE$PshowValue1$Pnumber
#define $PshowValue1$Pnumber__varInfo data->modelData.integerVarsData[2].info
#define $P$PRE$PshowValue1$Pnumber__varInfo data->modelData.integerVarsData[2].info
#define _$P$PRE$PshowValue1$Pnumber(i) $P$PRE$PshowValue1$Pnumber


/* triggeredAdd.local_set */
#define _$PtriggeredAdd$Plocal_set(i) data->localData[i]->integerVars[3]
#define $PtriggeredAdd$Plocal_set _$PtriggeredAdd$Plocal_set(0)
#define $P$PRE$PtriggeredAdd$Plocal_set data->simulationInfo.integerVarsPre[3]
#define $P$ATTRIBUTE$PtriggeredAdd$Plocal_set data->modelData.integerVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PtriggeredAdd$Plocal_set $P$ATTRIBUTE$PtriggeredAdd$Plocal_set
#define $PtriggeredAdd$Plocal_set__varInfo data->modelData.integerVarsData[3].info
#define $P$PRE$PtriggeredAdd$Plocal_set__varInfo data->modelData.integerVarsData[3].info
#define _$P$PRE$PtriggeredAdd$Plocal_set(i) $P$PRE$PtriggeredAdd$Plocal_set


/* triggeredAdd.y */
#define _$PtriggeredAdd$Py(i) data->localData[i]->integerVars[4]
#define $PtriggeredAdd$Py _$PtriggeredAdd$Py(0)
#define $P$PRE$PtriggeredAdd$Py data->simulationInfo.integerVarsPre[4]
#define $P$ATTRIBUTE$PtriggeredAdd$Py data->modelData.integerVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$PtriggeredAdd$Py $P$ATTRIBUTE$PtriggeredAdd$Py
#define $PtriggeredAdd$Py__varInfo data->modelData.integerVarsData[4].info
#define $P$PRE$PtriggeredAdd$Py__varInfo data->modelData.integerVarsData[4].info
#define _$P$PRE$PtriggeredAdd$Py(i) $P$PRE$PtriggeredAdd$Py


/* y1 */
#define _$Py1(i) data->localData[i]->integerVars[5]
#define $Py1 _$Py1(0)
#define $P$PRE$Py1 data->simulationInfo.integerVarsPre[5]
#define $P$ATTRIBUTE$Py1 data->modelData.integerVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Py1 $P$ATTRIBUTE$Py1
#define $Py1__varInfo data->modelData.integerVarsData[5].info
#define $P$PRE$Py1__varInfo data->modelData.integerVarsData[5].info
#define _$P$PRE$Py1(i) $P$PRE$Py1


/* Algebraic Integer Parameter */
/* and1.nu */
#define $Pand1$Pnu data->simulationInfo.integerParameter[0]
#define _$Pand1$Pnu(i) $Pand1$Pnu
#define $P$ATTRIBUTE$Pand1$Pnu data->modelData.integerParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Pand1$Pnu $P$ATTRIBUTE$Pand1$Pnu
#define $Pand1$Pnu__varInfo data->modelData.integerParameterData[0].info


/* booleanTable.n */
#define $PbooleanTable$Pn data->simulationInfo.integerParameter[1]
#define _$PbooleanTable$Pn(i) $PbooleanTable$Pn
#define $P$ATTRIBUTE$PbooleanTable$Pn data->modelData.integerParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Pn $P$ATTRIBUTE$PbooleanTable$Pn
#define $PbooleanTable$Pn__varInfo data->modelData.integerParameterData[1].info


/* integerConstant.k */
#define $PintegerConstant$Pk data->simulationInfo.integerParameter[2]
#define _$PintegerConstant$Pk(i) $PintegerConstant$Pk
#define $P$ATTRIBUTE$PintegerConstant$Pk data->modelData.integerParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PintegerConstant$Pk $P$ATTRIBUTE$PintegerConstant$Pk
#define $PintegerConstant$Pk__varInfo data->modelData.integerParameterData[2].info


/* nand1.nu */
#define $Pnand1$Pnu data->simulationInfo.integerParameter[3]
#define _$Pnand1$Pnu(i) $Pnand1$Pnu
#define $P$ATTRIBUTE$Pnand1$Pnu data->modelData.integerParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$Pnand1$Pnu $P$ATTRIBUTE$Pnand1$Pnu
#define $Pnand1$Pnu__varInfo data->modelData.integerParameterData[3].info


/* or1.nu */
#define $Por1$Pnu data->simulationInfo.integerParameter[4]
#define _$Por1$Pnu(i) $Por1$Pnu
#define $P$ATTRIBUTE$Por1$Pnu data->modelData.integerParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$Por1$Pnu $P$ATTRIBUTE$Por1$Pnu
#define $Por1$Pnu__varInfo data->modelData.integerParameterData[4].info


/* or2.nu */
#define $Por2$Pnu data->simulationInfo.integerParameter[5]
#define _$Por2$Pnu(i) $Por2$Pnu
#define $P$ATTRIBUTE$Por2$Pnu data->modelData.integerParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Por2$Pnu $P$ATTRIBUTE$Por2$Pnu
#define $Por2$Pnu__varInfo data->modelData.integerParameterData[5].info


/* set1.nu */
#define $Pset1$Pnu data->simulationInfo.integerParameter[6]
#define _$Pset1$Pnu(i) $Pset1$Pnu
#define $P$ATTRIBUTE$Pset1$Pnu data->modelData.integerParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Pnu $P$ATTRIBUTE$Pset1$Pnu
#define $Pset1$Pnu__varInfo data->modelData.integerParameterData[6].info


/* triggeredAdd.y_start */
#define $PtriggeredAdd$Py_start data->simulationInfo.integerParameter[7]
#define _$PtriggeredAdd$Py_start(i) $PtriggeredAdd$Py_start
#define $P$ATTRIBUTE$PtriggeredAdd$Py_start data->modelData.integerParameterData[7].attribute
#define $P$ATTRIBUTE$P$PRE$PtriggeredAdd$Py_start $P$ATTRIBUTE$PtriggeredAdd$Py_start
#define $PtriggeredAdd$Py_start__varInfo data->modelData.integerParameterData[7].info


/* xor1.nu */
#define $Pxor1$Pnu data->simulationInfo.integerParameter[8]
#define _$Pxor1$Pnu(i) $Pxor1$Pnu
#define $P$ATTRIBUTE$Pxor1$Pnu data->modelData.integerParameterData[8].attribute
#define $P$ATTRIBUTE$P$PRE$Pxor1$Pnu $P$ATTRIBUTE$Pxor1$Pnu
#define $Pxor1$Pnu__varInfo data->modelData.integerParameterData[8].info


/* Algebraic Boolean Vars */
/* $whenCondition1 */
#define _$P$whenCondition1(i) data->localData[i]->booleanVars[0]
#define $P$whenCondition1 _$P$whenCondition1(0)
#define $P$PRE$P$whenCondition1 data->simulationInfo.booleanVarsPre[0]
#define $P$ATTRIBUTE$P$whenCondition1 data->modelData.booleanVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition1 $P$ATTRIBUTE$P$whenCondition1
#define $P$whenCondition1__varInfo data->modelData.booleanVarsData[0].info
#define $P$PRE$P$whenCondition1__varInfo data->modelData.booleanVarsData[0].info
#define _$P$PRE$P$whenCondition1(i) $P$PRE$P$whenCondition1


/* $whenCondition2 */
#define _$P$whenCondition2(i) data->localData[i]->booleanVars[1]
#define $P$whenCondition2 _$P$whenCondition2(0)
#define $P$PRE$P$whenCondition2 data->simulationInfo.booleanVarsPre[1]
#define $P$ATTRIBUTE$P$whenCondition2 data->modelData.booleanVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition2 $P$ATTRIBUTE$P$whenCondition2
#define $P$whenCondition2__varInfo data->modelData.booleanVarsData[1].info
#define $P$PRE$P$whenCondition2__varInfo data->modelData.booleanVarsData[1].info
#define _$P$PRE$P$whenCondition2(i) $P$PRE$P$whenCondition2


/* $whenCondition3 */
#define _$P$whenCondition3(i) data->localData[i]->booleanVars[2]
#define $P$whenCondition3 _$P$whenCondition3(0)
#define $P$PRE$P$whenCondition3 data->simulationInfo.booleanVarsPre[2]
#define $P$ATTRIBUTE$P$whenCondition3 data->modelData.booleanVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition3 $P$ATTRIBUTE$P$whenCondition3
#define $P$whenCondition3__varInfo data->modelData.booleanVarsData[2].info
#define $P$PRE$P$whenCondition3__varInfo data->modelData.booleanVarsData[2].info
#define _$P$PRE$P$whenCondition3(i) $P$PRE$P$whenCondition3


/* $whenCondition4 */
#define _$P$whenCondition4(i) data->localData[i]->booleanVars[3]
#define $P$whenCondition4 _$P$whenCondition4(0)
#define $P$PRE$P$whenCondition4 data->simulationInfo.booleanVarsPre[3]
#define $P$ATTRIBUTE$P$whenCondition4 data->modelData.booleanVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition4 $P$ATTRIBUTE$P$whenCondition4
#define $P$whenCondition4__varInfo data->modelData.booleanVarsData[3].info
#define $P$PRE$P$whenCondition4__varInfo data->modelData.booleanVarsData[3].info
#define _$P$PRE$P$whenCondition4(i) $P$PRE$P$whenCondition4


/* $whenCondition5 */
#define _$P$whenCondition5(i) data->localData[i]->booleanVars[4]
#define $P$whenCondition5 _$P$whenCondition5(0)
#define $P$PRE$P$whenCondition5 data->simulationInfo.booleanVarsPre[4]
#define $P$ATTRIBUTE$P$whenCondition5 data->modelData.booleanVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition5 $P$ATTRIBUTE$P$whenCondition5
#define $P$whenCondition5__varInfo data->modelData.booleanVarsData[4].info
#define $P$PRE$P$whenCondition5__varInfo data->modelData.booleanVarsData[4].info
#define _$P$PRE$P$whenCondition5(i) $P$PRE$P$whenCondition5


/* $whenCondition6 */
#define _$P$whenCondition6(i) data->localData[i]->booleanVars[5]
#define $P$whenCondition6 _$P$whenCondition6(0)
#define $P$PRE$P$whenCondition6 data->simulationInfo.booleanVarsPre[5]
#define $P$ATTRIBUTE$P$whenCondition6 data->modelData.booleanVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition6 $P$ATTRIBUTE$P$whenCondition6
#define $P$whenCondition6__varInfo data->modelData.booleanVarsData[5].info
#define $P$PRE$P$whenCondition6__varInfo data->modelData.booleanVarsData[5].info
#define _$P$PRE$P$whenCondition6(i) $P$PRE$P$whenCondition6


/* $whenCondition7 */
#define _$P$whenCondition7(i) data->localData[i]->booleanVars[6]
#define $P$whenCondition7 _$P$whenCondition7(0)
#define $P$PRE$P$whenCondition7 data->simulationInfo.booleanVarsPre[6]
#define $P$ATTRIBUTE$P$whenCondition7 data->modelData.booleanVarsData[6].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition7 $P$ATTRIBUTE$P$whenCondition7
#define $P$whenCondition7__varInfo data->modelData.booleanVarsData[6].info
#define $P$PRE$P$whenCondition7__varInfo data->modelData.booleanVarsData[6].info
#define _$P$PRE$P$whenCondition7(i) $P$PRE$P$whenCondition7


/* Q */
#define _$PQ(i) data->localData[i]->booleanVars[7]
#define $PQ _$PQ(0)
#define $P$PRE$PQ data->simulationInfo.booleanVarsPre[7]
#define $P$ATTRIBUTE$PQ data->modelData.booleanVarsData[7].attribute
#define $P$ATTRIBUTE$P$PRE$PQ $P$ATTRIBUTE$PQ
#define $PQ__varInfo data->modelData.booleanVarsData[7].info
#define $P$PRE$PQ__varInfo data->modelData.booleanVarsData[7].info
#define _$P$PRE$PQ(i) $P$PRE$PQ


/* QI */
#define _$PQI(i) data->localData[i]->booleanVars[8]
#define $PQI _$PQI(0)
#define $P$PRE$PQI data->simulationInfo.booleanVarsPre[8]
#define $P$ATTRIBUTE$PQI data->modelData.booleanVarsData[8].attribute
#define $P$ATTRIBUTE$P$PRE$PQI $P$ATTRIBUTE$PQI
#define $PQI__varInfo data->modelData.booleanVarsData[8].info
#define $P$PRE$PQI__varInfo data->modelData.booleanVarsData[8].info
#define _$P$PRE$PQI(i) $P$PRE$PQI


/* and1.u */
#define _$Pand1$Pu(i) data->localData[i]->booleanVars[9]
#define $Pand1$Pu _$Pand1$Pu(0)
#define $P$PRE$Pand1$Pu data->simulationInfo.booleanVarsPre[9]

#define $Pand1$Pu_index(i_1)    (&$Pand1$Pu)[calc_base_index_dims_subs(1, 3, i_1)]
#define $P$PRE$Pand1$Pu_index(i_1)    (&$P$PRE$Pand1$Pu)[calc_base_index_dims_subs(1, 3, i_1)]

/* and1.u[1] */
#define _$Pand1$Pu$lB1$rB(i) data->localData[i]->booleanVars[9]
#define $Pand1$Pu$lB1$rB _$Pand1$Pu$lB1$rB(0)
#define $P$PRE$Pand1$Pu$lB1$rB data->simulationInfo.booleanVarsPre[9]
#define $P$ATTRIBUTE$Pand1$Pu$lB1$rB data->modelData.booleanVarsData[9].attribute
#define $P$ATTRIBUTE$P$PRE$Pand1$Pu$lB1$rB $P$ATTRIBUTE$Pand1$Pu$lB1$rB
#define $Pand1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[9].info
#define $P$PRE$Pand1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[9].info


/* booleanStep */
#define _$PbooleanStep(i) data->localData[i]->booleanVars[10]
#define $PbooleanStep _$PbooleanStep(0)
#define $P$PRE$PbooleanStep data->simulationInfo.booleanVarsPre[10]
#define $P$ATTRIBUTE$PbooleanStep data->modelData.booleanVarsData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanStep $P$ATTRIBUTE$PbooleanStep
#define $PbooleanStep__varInfo data->modelData.booleanVarsData[10].info
#define $P$PRE$PbooleanStep__varInfo data->modelData.booleanVarsData[10].info
#define _$P$PRE$PbooleanStep(i) $P$PRE$PbooleanStep


/* booleanTable.y */
#define _$PbooleanTable$Py(i) data->localData[i]->booleanVars[11]
#define $PbooleanTable$Py _$PbooleanTable$Py(0)
#define $P$PRE$PbooleanTable$Py data->simulationInfo.booleanVarsPre[11]
#define $P$ATTRIBUTE$PbooleanTable$Py data->modelData.booleanVarsData[11].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$Py $P$ATTRIBUTE$PbooleanTable$Py
#define $PbooleanTable$Py__varInfo data->modelData.booleanVarsData[11].info
#define $P$PRE$PbooleanTable$Py__varInfo data->modelData.booleanVarsData[11].info
#define _$P$PRE$PbooleanTable$Py(i) $P$PRE$PbooleanTable$Py


/* changing.u */
#define _$Pchanging$Pu(i) data->localData[i]->booleanVars[12]
#define $Pchanging$Pu _$Pchanging$Pu(0)
#define $P$PRE$Pchanging$Pu data->simulationInfo.booleanVarsPre[12]
#define $P$ATTRIBUTE$Pchanging$Pu data->modelData.booleanVarsData[12].attribute
#define $P$ATTRIBUTE$P$PRE$Pchanging$Pu $P$ATTRIBUTE$Pchanging$Pu
#define $Pchanging$Pu__varInfo data->modelData.booleanVarsData[12].info
#define $P$PRE$Pchanging$Pu__varInfo data->modelData.booleanVarsData[12].info
#define _$P$PRE$Pchanging$Pu(i) $P$PRE$Pchanging$Pu


/* changing.y */
#define _$Pchanging$Py(i) data->localData[i]->booleanVars[13]
#define $Pchanging$Py _$Pchanging$Py(0)
#define $P$PRE$Pchanging$Py data->simulationInfo.booleanVarsPre[13]
#define $P$ATTRIBUTE$Pchanging$Py data->modelData.booleanVarsData[13].attribute
#define $P$ATTRIBUTE$P$PRE$Pchanging$Py $P$ATTRIBUTE$Pchanging$Py
#define $Pchanging$Py__varInfo data->modelData.booleanVarsData[13].info
#define $P$PRE$Pchanging$Py__varInfo data->modelData.booleanVarsData[13].info
#define _$P$PRE$Pchanging$Py(i) $P$PRE$Pchanging$Py


/* falling.not_u */
#define _$Pfalling$Pnot_u(i) data->localData[i]->booleanVars[14]
#define $Pfalling$Pnot_u _$Pfalling$Pnot_u(0)
#define $P$PRE$Pfalling$Pnot_u data->simulationInfo.booleanVarsPre[14]
#define $P$ATTRIBUTE$Pfalling$Pnot_u data->modelData.booleanVarsData[14].attribute
#define $P$ATTRIBUTE$P$PRE$Pfalling$Pnot_u $P$ATTRIBUTE$Pfalling$Pnot_u
#define $Pfalling$Pnot_u__varInfo data->modelData.booleanVarsData[14].info
#define $P$PRE$Pfalling$Pnot_u__varInfo data->modelData.booleanVarsData[14].info
#define _$P$PRE$Pfalling$Pnot_u(i) $P$PRE$Pfalling$Pnot_u


/* nand1.u */
#define _$Pnand1$Pu(i) data->localData[i]->booleanVars[15]
#define $Pnand1$Pu _$Pnand1$Pu(0)
#define $P$PRE$Pnand1$Pu data->simulationInfo.booleanVarsPre[15]

#define $Pnand1$Pu_index(i_1)    (&$Pnand1$Pu)[calc_base_index_dims_subs(1, 2, i_1)]
#define $P$PRE$Pnand1$Pu_index(i_1)    (&$P$PRE$Pnand1$Pu)[calc_base_index_dims_subs(1, 2, i_1)]

/* nand1.u[1] */
#define _$Pnand1$Pu$lB1$rB(i) data->localData[i]->booleanVars[15]
#define $Pnand1$Pu$lB1$rB _$Pnand1$Pu$lB1$rB(0)
#define $P$PRE$Pnand1$Pu$lB1$rB data->simulationInfo.booleanVarsPre[15]
#define $P$ATTRIBUTE$Pnand1$Pu$lB1$rB data->modelData.booleanVarsData[15].attribute
#define $P$ATTRIBUTE$P$PRE$Pnand1$Pu$lB1$rB $P$ATTRIBUTE$Pnand1$Pu$lB1$rB
#define $Pnand1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[15].info
#define $P$PRE$Pnand1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[15].info


/* nor1.y */
#define _$Pnor1$Py(i) data->localData[i]->booleanVars[16]
#define $Pnor1$Py _$Pnor1$Py(0)
#define $P$PRE$Pnor1$Py data->simulationInfo.booleanVarsPre[16]
#define $P$ATTRIBUTE$Pnor1$Py data->modelData.booleanVarsData[16].attribute
#define $P$ATTRIBUTE$P$PRE$Pnor1$Py $P$ATTRIBUTE$Pnor1$Py
#define $Pnor1$Py__varInfo data->modelData.booleanVarsData[16].info
#define $P$PRE$Pnor1$Py__varInfo data->modelData.booleanVarsData[16].info
#define _$P$PRE$Pnor1$Py(i) $P$PRE$Pnor1$Py


/* onDelay.delaySignal */
#define _$PonDelay$PdelaySignal(i) data->localData[i]->booleanVars[17]
#define $PonDelay$PdelaySignal _$PonDelay$PdelaySignal(0)
#define $P$PRE$PonDelay$PdelaySignal data->simulationInfo.booleanVarsPre[17]
#define $P$ATTRIBUTE$PonDelay$PdelaySignal data->modelData.booleanVarsData[17].attribute
#define $P$ATTRIBUTE$P$PRE$PonDelay$PdelaySignal $P$ATTRIBUTE$PonDelay$PdelaySignal
#define $PonDelay$PdelaySignal__varInfo data->modelData.booleanVarsData[17].info
#define $P$PRE$PonDelay$PdelaySignal__varInfo data->modelData.booleanVarsData[17].info
#define _$P$PRE$PonDelay$PdelaySignal(i) $P$PRE$PonDelay$PdelaySignal


/* onDelay.u */
#define _$PonDelay$Pu(i) data->localData[i]->booleanVars[18]
#define $PonDelay$Pu _$PonDelay$Pu(0)
#define $P$PRE$PonDelay$Pu data->simulationInfo.booleanVarsPre[18]
#define $P$ATTRIBUTE$PonDelay$Pu data->modelData.booleanVarsData[18].attribute
#define $P$ATTRIBUTE$P$PRE$PonDelay$Pu $P$ATTRIBUTE$PonDelay$Pu
#define $PonDelay$Pu__varInfo data->modelData.booleanVarsData[18].info
#define $P$PRE$PonDelay$Pu__varInfo data->modelData.booleanVarsData[18].info
#define _$P$PRE$PonDelay$Pu(i) $P$PRE$PonDelay$Pu


/* or2.u */
#define _$Por2$Pu(i) data->localData[i]->booleanVars[19]
#define $Por2$Pu _$Por2$Pu(0)
#define $P$PRE$Por2$Pu data->simulationInfo.booleanVarsPre[19]

#define $Por2$Pu_index(i_1)    (&$Por2$Pu)[calc_base_index_dims_subs(1, 2, i_1)]
#define $P$PRE$Por2$Pu_index(i_1)    (&$P$PRE$Por2$Pu)[calc_base_index_dims_subs(1, 2, i_1)]

/* or2.u[1] */
#define _$Por2$Pu$lB1$rB(i) data->localData[i]->booleanVars[19]
#define $Por2$Pu$lB1$rB _$Por2$Pu$lB1$rB(0)
#define $P$PRE$Por2$Pu$lB1$rB data->simulationInfo.booleanVarsPre[19]
#define $P$ATTRIBUTE$Por2$Pu$lB1$rB data->modelData.booleanVarsData[19].attribute
#define $P$ATTRIBUTE$P$PRE$Por2$Pu$lB1$rB $P$ATTRIBUTE$Por2$Pu$lB1$rB
#define $Por2$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[19].info
#define $P$PRE$Por2$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[19].info


/* rSFlipFlop.R */
#define _$PrSFlipFlop$PR(i) data->localData[i]->booleanVars[20]
#define $PrSFlipFlop$PR _$PrSFlipFlop$PR(0)
#define $P$PRE$PrSFlipFlop$PR data->simulationInfo.booleanVarsPre[20]
#define $P$ATTRIBUTE$PrSFlipFlop$PR data->modelData.booleanVarsData[20].attribute
#define $P$ATTRIBUTE$P$PRE$PrSFlipFlop$PR $P$ATTRIBUTE$PrSFlipFlop$PR
#define $PrSFlipFlop$PR__varInfo data->modelData.booleanVarsData[20].info
#define $P$PRE$PrSFlipFlop$PR__varInfo data->modelData.booleanVarsData[20].info
#define _$P$PRE$PrSFlipFlop$PR(i) $P$PRE$PrSFlipFlop$PR


/* rSFlipFlop.S */
#define _$PrSFlipFlop$PS(i) data->localData[i]->booleanVars[21]
#define $PrSFlipFlop$PS _$PrSFlipFlop$PS(0)
#define $P$PRE$PrSFlipFlop$PS data->simulationInfo.booleanVarsPre[21]
#define $P$ATTRIBUTE$PrSFlipFlop$PS data->modelData.booleanVarsData[21].attribute
#define $P$ATTRIBUTE$P$PRE$PrSFlipFlop$PS $P$ATTRIBUTE$PrSFlipFlop$PS
#define $PrSFlipFlop$PS__varInfo data->modelData.booleanVarsData[21].info
#define $P$PRE$PrSFlipFlop$PS__varInfo data->modelData.booleanVarsData[21].info
#define _$P$PRE$PrSFlipFlop$PS(i) $P$PRE$PrSFlipFlop$PS


/* rSFlipFlop.pre.u */
#define _$PrSFlipFlop$Ppre$Pu(i) data->localData[i]->booleanVars[22]
#define $PrSFlipFlop$Ppre$Pu _$PrSFlipFlop$Ppre$Pu(0)
#define $P$PRE$PrSFlipFlop$Ppre$Pu data->simulationInfo.booleanVarsPre[22]
#define $P$ATTRIBUTE$PrSFlipFlop$Ppre$Pu data->modelData.booleanVarsData[22].attribute
#define $P$ATTRIBUTE$P$PRE$PrSFlipFlop$Ppre$Pu $P$ATTRIBUTE$PrSFlipFlop$Ppre$Pu
#define $PrSFlipFlop$Ppre$Pu__varInfo data->modelData.booleanVarsData[22].info
#define $P$PRE$PrSFlipFlop$Ppre$Pu__varInfo data->modelData.booleanVarsData[22].info
#define _$P$PRE$PrSFlipFlop$Ppre$Pu(i) $P$PRE$PrSFlipFlop$Ppre$Pu


/* rising.u */
#define _$Prising$Pu(i) data->localData[i]->booleanVars[23]
#define $Prising$Pu _$Prising$Pu(0)
#define $P$PRE$Prising$Pu data->simulationInfo.booleanVarsPre[23]
#define $P$ATTRIBUTE$Prising$Pu data->modelData.booleanVarsData[23].attribute
#define $P$ATTRIBUTE$P$PRE$Prising$Pu $P$ATTRIBUTE$Prising$Pu
#define $Prising$Pu__varInfo data->modelData.booleanVarsData[23].info
#define $P$PRE$Prising$Pu__varInfo data->modelData.booleanVarsData[23].info
#define _$P$PRE$Prising$Pu(i) $P$PRE$Prising$Pu


/* set1.expr */
#define _$Pset1$Pexpr(i) data->localData[i]->booleanVars[24]
#define $Pset1$Pexpr _$Pset1$Pexpr(0)
#define $P$PRE$Pset1$Pexpr data->simulationInfo.booleanVarsPre[24]

#define $Pset1$Pexpr_index(i_1)    (&$Pset1$Pexpr)[calc_base_index_dims_subs(1, 2, i_1)]
#define $P$PRE$Pset1$Pexpr_index(i_1)    (&$P$PRE$Pset1$Pexpr)[calc_base_index_dims_subs(1, 2, i_1)]

/* set1.expr[1] */
#define _$Pset1$Pexpr$lB1$rB(i) data->localData[i]->booleanVars[24]
#define $Pset1$Pexpr$lB1$rB _$Pset1$Pexpr$lB1$rB(0)
#define $P$PRE$Pset1$Pexpr$lB1$rB data->simulationInfo.booleanVarsPre[24]
#define $P$ATTRIBUTE$Pset1$Pexpr$lB1$rB data->modelData.booleanVarsData[24].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Pexpr$lB1$rB $P$ATTRIBUTE$Pset1$Pexpr$lB1$rB
#define $Pset1$Pexpr$lB1$rB__varInfo data->modelData.booleanVarsData[24].info
#define $P$PRE$Pset1$Pexpr$lB1$rB__varInfo data->modelData.booleanVarsData[24].info


/* set1.expr[2] */
#define _$Pset1$Pexpr$lB2$rB(i) data->localData[i]->booleanVars[25]
#define $Pset1$Pexpr$lB2$rB _$Pset1$Pexpr$lB2$rB(0)
#define $P$PRE$Pset1$Pexpr$lB2$rB data->simulationInfo.booleanVarsPre[25]
#define $P$ATTRIBUTE$Pset1$Pexpr$lB2$rB data->modelData.booleanVarsData[25].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Pexpr$lB2$rB $P$ATTRIBUTE$Pset1$Pexpr$lB2$rB
#define $Pset1$Pexpr$lB2$rB__varInfo data->modelData.booleanVarsData[25].info
#define $P$PRE$Pset1$Pexpr$lB2$rB__varInfo data->modelData.booleanVarsData[25].info
#define _$P$PRE$Pset1$Pexpr$lB2$rB(i) $P$PRE$Pset1$Pexpr$lB2$rB


/* set1.u */
#define _$Pset1$Pu(i) data->localData[i]->booleanVars[26]
#define $Pset1$Pu _$Pset1$Pu(0)
#define $P$PRE$Pset1$Pu data->simulationInfo.booleanVarsPre[26]

#define $Pset1$Pu_index(i_1)    (&$Pset1$Pu)[calc_base_index_dims_subs(1, 2, i_1)]
#define $P$PRE$Pset1$Pu_index(i_1)    (&$P$PRE$Pset1$Pu)[calc_base_index_dims_subs(1, 2, i_1)]

/* set1.u[1] */
#define _$Pset1$Pu$lB1$rB(i) data->localData[i]->booleanVars[26]
#define $Pset1$Pu$lB1$rB _$Pset1$Pu$lB1$rB(0)
#define $P$PRE$Pset1$Pu$lB1$rB data->simulationInfo.booleanVarsPre[26]
#define $P$ATTRIBUTE$Pset1$Pu$lB1$rB data->modelData.booleanVarsData[26].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Pu$lB1$rB $P$ATTRIBUTE$Pset1$Pu$lB1$rB
#define $Pset1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[26].info
#define $P$PRE$Pset1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[26].info


/* set1.u[2] */
#define _$Pset1$Pu$lB2$rB(i) data->localData[i]->booleanVars[27]
#define $Pset1$Pu$lB2$rB _$Pset1$Pu$lB2$rB(0)
#define $P$PRE$Pset1$Pu$lB2$rB data->simulationInfo.booleanVarsPre[27]
#define $P$ATTRIBUTE$Pset1$Pu$lB2$rB data->modelData.booleanVarsData[27].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Pu$lB2$rB $P$ATTRIBUTE$Pset1$Pu$lB2$rB
#define $Pset1$Pu$lB2$rB__varInfo data->modelData.booleanVarsData[27].info
#define $P$PRE$Pset1$Pu$lB2$rB__varInfo data->modelData.booleanVarsData[27].info
#define _$P$PRE$Pset1$Pu$lB2$rB(i) $P$PRE$Pset1$Pu$lB2$rB


/* set1.y */
#define _$Pset1$Py(i) data->localData[i]->booleanVars[28]
#define $Pset1$Py _$Pset1$Py(0)
#define $P$PRE$Pset1$Py data->simulationInfo.booleanVarsPre[28]
#define $P$ATTRIBUTE$Pset1$Py data->modelData.booleanVarsData[28].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Py $P$ATTRIBUTE$Pset1$Py
#define $Pset1$Py__varInfo data->modelData.booleanVarsData[28].info
#define $P$PRE$Pset1$Py__varInfo data->modelData.booleanVarsData[28].info
#define _$P$PRE$Pset1$Py(i) $P$PRE$Pset1$Py


/* showValue.active */
#define _$PshowValue$Pactive(i) data->localData[i]->booleanVars[29]
#define $PshowValue$Pactive _$PshowValue$Pactive(0)
#define $P$PRE$PshowValue$Pactive data->simulationInfo.booleanVarsPre[29]
#define $P$ATTRIBUTE$PshowValue$Pactive data->modelData.booleanVarsData[29].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue$Pactive $P$ATTRIBUTE$PshowValue$Pactive
#define $PshowValue$Pactive__varInfo data->modelData.booleanVarsData[29].info
#define $P$PRE$PshowValue$Pactive__varInfo data->modelData.booleanVarsData[29].info
#define _$P$PRE$PshowValue$Pactive(i) $P$PRE$PshowValue$Pactive


/* showValue2.active */
#define _$PshowValue2$Pactive(i) data->localData[i]->booleanVars[30]
#define $PshowValue2$Pactive _$PshowValue2$Pactive(0)
#define $P$PRE$PshowValue2$Pactive data->simulationInfo.booleanVarsPre[30]
#define $P$ATTRIBUTE$PshowValue2$Pactive data->modelData.booleanVarsData[30].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue2$Pactive $P$ATTRIBUTE$PshowValue2$Pactive
#define $PshowValue2$Pactive__varInfo data->modelData.booleanVarsData[30].info
#define $P$PRE$PshowValue2$Pactive__varInfo data->modelData.booleanVarsData[30].info
#define _$P$PRE$PshowValue2$Pactive(i) $P$PRE$PshowValue2$Pactive


/* showValue3.active */
#define _$PshowValue3$Pactive(i) data->localData[i]->booleanVars[31]
#define $PshowValue3$Pactive _$PshowValue3$Pactive(0)
#define $P$PRE$PshowValue3$Pactive data->simulationInfo.booleanVarsPre[31]
#define $P$ATTRIBUTE$PshowValue3$Pactive data->modelData.booleanVarsData[31].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue3$Pactive $P$ATTRIBUTE$PshowValue3$Pactive
#define $PshowValue3$Pactive__varInfo data->modelData.booleanVarsData[31].info
#define $P$PRE$PshowValue3$Pactive__varInfo data->modelData.booleanVarsData[31].info
#define _$P$PRE$PshowValue3$Pactive(i) $P$PRE$PshowValue3$Pactive


/* showValue4.active */
#define _$PshowValue4$Pactive(i) data->localData[i]->booleanVars[32]
#define $PshowValue4$Pactive _$PshowValue4$Pactive(0)
#define $P$PRE$PshowValue4$Pactive data->simulationInfo.booleanVarsPre[32]
#define $P$ATTRIBUTE$PshowValue4$Pactive data->modelData.booleanVarsData[32].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue4$Pactive $P$ATTRIBUTE$PshowValue4$Pactive
#define $PshowValue4$Pactive__varInfo data->modelData.booleanVarsData[32].info
#define $P$PRE$PshowValue4$Pactive__varInfo data->modelData.booleanVarsData[32].info
#define _$P$PRE$PshowValue4$Pactive(i) $P$PRE$PshowValue4$Pactive


/* showValue5.active */
#define _$PshowValue5$Pactive(i) data->localData[i]->booleanVars[33]
#define $PshowValue5$Pactive _$PshowValue5$Pactive(0)
#define $P$PRE$PshowValue5$Pactive data->simulationInfo.booleanVarsPre[33]
#define $P$ATTRIBUTE$PshowValue5$Pactive data->modelData.booleanVarsData[33].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue5$Pactive $P$ATTRIBUTE$PshowValue5$Pactive
#define $PshowValue5$Pactive__varInfo data->modelData.booleanVarsData[33].info
#define $P$PRE$PshowValue5$Pactive__varInfo data->modelData.booleanVarsData[33].info
#define _$P$PRE$PshowValue5$Pactive(i) $P$PRE$PshowValue5$Pactive


/* showValue6.active */
#define _$PshowValue6$Pactive(i) data->localData[i]->booleanVars[34]
#define $PshowValue6$Pactive _$PshowValue6$Pactive(0)
#define $P$PRE$PshowValue6$Pactive data->simulationInfo.booleanVarsPre[34]
#define $P$ATTRIBUTE$PshowValue6$Pactive data->modelData.booleanVarsData[34].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue6$Pactive $P$ATTRIBUTE$PshowValue6$Pactive
#define $PshowValue6$Pactive__varInfo data->modelData.booleanVarsData[34].info
#define $P$PRE$PshowValue6$Pactive__varInfo data->modelData.booleanVarsData[34].info
#define _$P$PRE$PshowValue6$Pactive(i) $P$PRE$PshowValue6$Pactive


/* triggeredAdd.local_reset */
#define _$PtriggeredAdd$Plocal_reset(i) data->localData[i]->booleanVars[35]
#define $PtriggeredAdd$Plocal_reset _$PtriggeredAdd$Plocal_reset(0)
#define $P$PRE$PtriggeredAdd$Plocal_reset data->simulationInfo.booleanVarsPre[35]
#define $P$ATTRIBUTE$PtriggeredAdd$Plocal_reset data->modelData.booleanVarsData[35].attribute
#define $P$ATTRIBUTE$P$PRE$PtriggeredAdd$Plocal_reset $P$ATTRIBUTE$PtriggeredAdd$Plocal_reset
#define $PtriggeredAdd$Plocal_reset__varInfo data->modelData.booleanVarsData[35].info
#define $P$PRE$PtriggeredAdd$Plocal_reset__varInfo data->modelData.booleanVarsData[35].info
#define _$P$PRE$PtriggeredAdd$Plocal_reset(i) $P$PRE$PtriggeredAdd$Plocal_reset


/* xor1.u */
#define _$Pxor1$Pu(i) data->localData[i]->booleanVars[36]
#define $Pxor1$Pu _$Pxor1$Pu(0)
#define $P$PRE$Pxor1$Pu data->simulationInfo.booleanVarsPre[36]

#define $Pxor1$Pu_index(i_1)    (&$Pxor1$Pu)[calc_base_index_dims_subs(1, 2, i_1)]
#define $P$PRE$Pxor1$Pu_index(i_1)    (&$P$PRE$Pxor1$Pu)[calc_base_index_dims_subs(1, 2, i_1)]

/* xor1.u[1] */
#define _$Pxor1$Pu$lB1$rB(i) data->localData[i]->booleanVars[36]
#define $Pxor1$Pu$lB1$rB _$Pxor1$Pu$lB1$rB(0)
#define $P$PRE$Pxor1$Pu$lB1$rB data->simulationInfo.booleanVarsPre[36]
#define $P$ATTRIBUTE$Pxor1$Pu$lB1$rB data->modelData.booleanVarsData[36].attribute
#define $P$ATTRIBUTE$P$PRE$Pxor1$Pu$lB1$rB $P$ATTRIBUTE$Pxor1$Pu$lB1$rB
#define $Pxor1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[36].info
#define $P$PRE$Pxor1$Pu$lB1$rB__varInfo data->modelData.booleanVarsData[36].info


/* y */
#define _$Py(i) data->localData[i]->booleanVars[37]
#define $Py _$Py(0)
#define $P$PRE$Py data->simulationInfo.booleanVarsPre[37]
#define $P$ATTRIBUTE$Py data->modelData.booleanVarsData[37].attribute
#define $P$ATTRIBUTE$P$PRE$Py $P$ATTRIBUTE$Py
#define $Py__varInfo data->modelData.booleanVarsData[37].info
#define $P$PRE$Py__varInfo data->modelData.booleanVarsData[37].info
#define _$P$PRE$Py(i) $P$PRE$Py


/* y2 */
#define _$Py2(i) data->localData[i]->booleanVars[38]
#define $Py2 _$Py2(0)
#define $P$PRE$Py2 data->simulationInfo.booleanVarsPre[38]
#define $P$ATTRIBUTE$Py2 data->modelData.booleanVarsData[38].attribute
#define $P$ATTRIBUTE$P$PRE$Py2 $P$ATTRIBUTE$Py2
#define $Py2__varInfo data->modelData.booleanVarsData[38].info
#define $P$PRE$Py2__varInfo data->modelData.booleanVarsData[38].info
#define _$P$PRE$Py2(i) $P$PRE$Py2


/* y3 */
#define _$Py3(i) data->localData[i]->booleanVars[39]
#define $Py3 _$Py3(0)
#define $P$PRE$Py3 data->simulationInfo.booleanVarsPre[39]
#define $P$ATTRIBUTE$Py3 data->modelData.booleanVarsData[39].attribute
#define $P$ATTRIBUTE$P$PRE$Py3 $P$ATTRIBUTE$Py3
#define $Py3__varInfo data->modelData.booleanVarsData[39].info
#define $P$PRE$Py3__varInfo data->modelData.booleanVarsData[39].info
#define _$P$PRE$Py3(i) $P$PRE$Py3


/* y4 */
#define _$Py4(i) data->localData[i]->booleanVars[40]
#define $Py4 _$Py4(0)
#define $P$PRE$Py4 data->simulationInfo.booleanVarsPre[40]
#define $P$ATTRIBUTE$Py4 data->modelData.booleanVarsData[40].attribute
#define $P$ATTRIBUTE$P$PRE$Py4 $P$ATTRIBUTE$Py4
#define $Py4__varInfo data->modelData.booleanVarsData[40].info
#define $P$PRE$Py4__varInfo data->modelData.booleanVarsData[40].info
#define _$P$PRE$Py4(i) $P$PRE$Py4


/* Algebraic Boolean Parameters */
/* booleanTable.startValue */
#define $PbooleanTable$PstartValue data->simulationInfo.booleanParameter[0]
#define _$PbooleanTable$PstartValue(i) $PbooleanTable$PstartValue
#define $P$ATTRIBUTE$PbooleanTable$PstartValue data->modelData.booleanParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PbooleanTable$PstartValue $P$ATTRIBUTE$PbooleanTable$PstartValue
#define $PbooleanTable$PstartValue__varInfo data->modelData.booleanParameterData[0].info


/* changing.pre_u_start */
#define $Pchanging$Ppre_u_start data->simulationInfo.booleanParameter[1]
#define _$Pchanging$Ppre_u_start(i) $Pchanging$Ppre_u_start
#define $P$ATTRIBUTE$Pchanging$Ppre_u_start data->modelData.booleanParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Pchanging$Ppre_u_start $P$ATTRIBUTE$Pchanging$Ppre_u_start
#define $Pchanging$Ppre_u_start__varInfo data->modelData.booleanParameterData[1].info


/* falling.pre_u_start */
#define $Pfalling$Ppre_u_start data->simulationInfo.booleanParameter[2]
#define _$Pfalling$Ppre_u_start(i) $Pfalling$Ppre_u_start
#define $P$ATTRIBUTE$Pfalling$Ppre_u_start data->modelData.booleanParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Pfalling$Ppre_u_start $P$ATTRIBUTE$Pfalling$Ppre_u_start
#define $Pfalling$Ppre_u_start__varInfo data->modelData.booleanParameterData[2].info


/* rSFlipFlop.Qini */
#define $PrSFlipFlop$PQini data->simulationInfo.booleanParameter[3]
#define _$PrSFlipFlop$PQini(i) $PrSFlipFlop$PQini
#define $P$ATTRIBUTE$PrSFlipFlop$PQini data->modelData.booleanParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PrSFlipFlop$PQini $P$ATTRIBUTE$PrSFlipFlop$PQini
#define $PrSFlipFlop$PQini__varInfo data->modelData.booleanParameterData[3].info


/* rSFlipFlop.pre.pre_u_start */
#define $PrSFlipFlop$Ppre$Ppre_u_start data->simulationInfo.booleanParameter[4]
#define _$PrSFlipFlop$Ppre$Ppre_u_start(i) $PrSFlipFlop$Ppre$Ppre_u_start
#define $P$ATTRIBUTE$PrSFlipFlop$Ppre$Ppre_u_start data->modelData.booleanParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$PrSFlipFlop$Ppre$Ppre_u_start $P$ATTRIBUTE$PrSFlipFlop$Ppre$Ppre_u_start
#define $PrSFlipFlop$Ppre$Ppre_u_start__varInfo data->modelData.booleanParameterData[4].info


/* rising.pre_u_start */
#define $Prising$Ppre_u_start data->simulationInfo.booleanParameter[5]
#define _$Prising$Ppre_u_start(i) $Prising$Ppre_u_start
#define $P$ATTRIBUTE$Prising$Ppre_u_start data->modelData.booleanParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Prising$Ppre_u_start $P$ATTRIBUTE$Prising$Ppre_u_start
#define $Prising$Ppre_u_start__varInfo data->modelData.booleanParameterData[5].info


/* set1.use_pre_as_default */
#define $Pset1$Puse_pre_as_default data->simulationInfo.booleanParameter[6]
#define _$Pset1$Puse_pre_as_default(i) $Pset1$Puse_pre_as_default
#define $P$ATTRIBUTE$Pset1$Puse_pre_as_default data->modelData.booleanParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Puse_pre_as_default $P$ATTRIBUTE$Pset1$Puse_pre_as_default
#define $Pset1$Puse_pre_as_default__varInfo data->modelData.booleanParameterData[6].info


/* set1.y_default */
#define $Pset1$Py_default data->simulationInfo.booleanParameter[7]
#define _$Pset1$Py_default(i) $Pset1$Py_default
#define $P$ATTRIBUTE$Pset1$Py_default data->modelData.booleanParameterData[7].attribute
#define $P$ATTRIBUTE$P$PRE$Pset1$Py_default $P$ATTRIBUTE$Pset1$Py_default
#define $Pset1$Py_default__varInfo data->modelData.booleanParameterData[7].info


/* showValue.use_activePort */
#define $PshowValue$Puse_activePort data->simulationInfo.booleanParameter[8]
#define _$PshowValue$Puse_activePort(i) $PshowValue$Puse_activePort
#define $P$ATTRIBUTE$PshowValue$Puse_activePort data->modelData.booleanParameterData[8].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue$Puse_activePort $P$ATTRIBUTE$PshowValue$Puse_activePort
#define $PshowValue$Puse_activePort__varInfo data->modelData.booleanParameterData[8].info


/* showValue1.use_numberPort */
#define $PshowValue1$Puse_numberPort data->simulationInfo.booleanParameter[9]
#define _$PshowValue1$Puse_numberPort(i) $PshowValue1$Puse_numberPort
#define $P$ATTRIBUTE$PshowValue1$Puse_numberPort data->modelData.booleanParameterData[9].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue1$Puse_numberPort $P$ATTRIBUTE$PshowValue1$Puse_numberPort
#define $PshowValue1$Puse_numberPort__varInfo data->modelData.booleanParameterData[9].info


/* showValue2.use_activePort */
#define $PshowValue2$Puse_activePort data->simulationInfo.booleanParameter[10]
#define _$PshowValue2$Puse_activePort(i) $PshowValue2$Puse_activePort
#define $P$ATTRIBUTE$PshowValue2$Puse_activePort data->modelData.booleanParameterData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue2$Puse_activePort $P$ATTRIBUTE$PshowValue2$Puse_activePort
#define $PshowValue2$Puse_activePort__varInfo data->modelData.booleanParameterData[10].info


/* showValue3.use_activePort */
#define $PshowValue3$Puse_activePort data->simulationInfo.booleanParameter[11]
#define _$PshowValue3$Puse_activePort(i) $PshowValue3$Puse_activePort
#define $P$ATTRIBUTE$PshowValue3$Puse_activePort data->modelData.booleanParameterData[11].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue3$Puse_activePort $P$ATTRIBUTE$PshowValue3$Puse_activePort
#define $PshowValue3$Puse_activePort__varInfo data->modelData.booleanParameterData[11].info


/* showValue4.use_activePort */
#define $PshowValue4$Puse_activePort data->simulationInfo.booleanParameter[12]
#define _$PshowValue4$Puse_activePort(i) $PshowValue4$Puse_activePort
#define $P$ATTRIBUTE$PshowValue4$Puse_activePort data->modelData.booleanParameterData[12].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue4$Puse_activePort $P$ATTRIBUTE$PshowValue4$Puse_activePort
#define $PshowValue4$Puse_activePort__varInfo data->modelData.booleanParameterData[12].info


/* showValue5.use_activePort */
#define $PshowValue5$Puse_activePort data->simulationInfo.booleanParameter[13]
#define _$PshowValue5$Puse_activePort(i) $PshowValue5$Puse_activePort
#define $P$ATTRIBUTE$PshowValue5$Puse_activePort data->modelData.booleanParameterData[13].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue5$Puse_activePort $P$ATTRIBUTE$PshowValue5$Puse_activePort
#define $PshowValue5$Puse_activePort__varInfo data->modelData.booleanParameterData[13].info


/* showValue6.use_activePort */
#define $PshowValue6$Puse_activePort data->simulationInfo.booleanParameter[14]
#define _$PshowValue6$Puse_activePort(i) $PshowValue6$Puse_activePort
#define $P$ATTRIBUTE$PshowValue6$Puse_activePort data->modelData.booleanParameterData[14].attribute
#define $P$ATTRIBUTE$P$PRE$PshowValue6$Puse_activePort $P$ATTRIBUTE$PshowValue6$Puse_activePort
#define $PshowValue6$Puse_activePort__varInfo data->modelData.booleanParameterData[14].info


/* triggeredAdd.use_reset */
#define $PtriggeredAdd$Puse_reset data->simulationInfo.booleanParameter[15]
#define _$PtriggeredAdd$Puse_reset(i) $PtriggeredAdd$Puse_reset
#define $P$ATTRIBUTE$PtriggeredAdd$Puse_reset data->modelData.booleanParameterData[15].attribute
#define $P$ATTRIBUTE$P$PRE$PtriggeredAdd$Puse_reset $P$ATTRIBUTE$PtriggeredAdd$Puse_reset
#define $PtriggeredAdd$Puse_reset__varInfo data->modelData.booleanParameterData[15].info


/* triggeredAdd.use_set */
#define $PtriggeredAdd$Puse_set data->simulationInfo.booleanParameter[16]
#define _$PtriggeredAdd$Puse_set(i) $PtriggeredAdd$Puse_set
#define $P$ATTRIBUTE$PtriggeredAdd$Puse_set data->modelData.booleanParameterData[16].attribute
#define $P$ATTRIBUTE$P$PRE$PtriggeredAdd$Puse_set $P$ATTRIBUTE$PtriggeredAdd$Puse_set
#define $PtriggeredAdd$Puse_set__varInfo data->modelData.booleanParameterData[16].info


/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */
#define $P$sample1 data->simulationInfo.samples[0]
#define $P$sample2 data->simulationInfo.samples[1]
#define $P$sample3 data->simulationInfo.samples[2]
#define $P$sample4 data->simulationInfo.samples[3]

#define Modelica_Math_BooleanVectors_countTrue_index 0
#define Modelica_Math_BooleanVectors_allTrue_index 1
#define Modelica_Blocks_Sources_BooleanTable$booleanTable_getFirstIndex_index 2
#define Modelica_Math_BooleanVectors_anyTrue_index 3
#define Modelica_Math_BooleanVectors_oneTrue_index 4
#define Modelica_Math_BooleanVectors_firstTrueIndex_index 5

