/* Algebraic */
/* Simulation code for BooleanNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "BooleanNetwork1_functions.h"
#include "BooleanNetwork1_model.h"
#include "BooleanNetwork1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#ifdef __cplusplus
extern "C" {
#endif


/* forwarded equations */
extern void BooleanNetwork1_eqFunction_69(DATA* data);
extern void BooleanNetwork1_eqFunction_70(DATA* data);
extern void BooleanNetwork1_eqFunction_71(DATA* data);
extern void BooleanNetwork1_eqFunction_73(DATA* data);
extern void BooleanNetwork1_eqFunction_74(DATA* data);
extern void BooleanNetwork1_eqFunction_75(DATA* data);
extern void BooleanNetwork1_eqFunction_76(DATA* data);
extern void BooleanNetwork1_eqFunction_77(DATA* data);
extern void BooleanNetwork1_eqFunction_79(DATA* data);
extern void BooleanNetwork1_eqFunction_80(DATA* data);
extern void BooleanNetwork1_eqFunction_81(DATA* data);
extern void BooleanNetwork1_eqFunction_82(DATA* data);
extern void BooleanNetwork1_eqFunction_83(DATA* data);
extern void BooleanNetwork1_eqFunction_84(DATA* data);
extern void BooleanNetwork1_eqFunction_85(DATA* data);
extern void BooleanNetwork1_eqFunction_87(DATA* data);
extern void BooleanNetwork1_eqFunction_88(DATA* data);
extern void BooleanNetwork1_eqFunction_89(DATA* data);
extern void BooleanNetwork1_eqFunction_90(DATA* data);
extern void BooleanNetwork1_eqFunction_91(DATA* data);
extern void BooleanNetwork1_eqFunction_92(DATA* data);
extern void BooleanNetwork1_eqFunction_65(DATA* data);
extern void BooleanNetwork1_eqFunction_66(DATA* data);
extern void BooleanNetwork1_eqFunction_67(DATA* data);
extern void BooleanNetwork1_eqFunction_68(DATA* data);
extern void BooleanNetwork1_eqFunction_60(DATA* data);
extern void BooleanNetwork1_eqFunction_61(DATA* data);
extern void BooleanNetwork1_eqFunction_62(DATA* data);
extern void BooleanNetwork1_eqFunction_63(DATA* data);
extern void BooleanNetwork1_eqFunction_64(DATA* data);

static void functionAlg_system0(DATA *data)
{
  BooleanNetwork1_eqFunction_69(data);

  BooleanNetwork1_eqFunction_70(data);

  BooleanNetwork1_eqFunction_71(data);

  BooleanNetwork1_eqFunction_73(data);

  BooleanNetwork1_eqFunction_74(data);

  BooleanNetwork1_eqFunction_75(data);

  BooleanNetwork1_eqFunction_76(data);

  BooleanNetwork1_eqFunction_77(data);

  BooleanNetwork1_eqFunction_79(data);

  BooleanNetwork1_eqFunction_80(data);

  BooleanNetwork1_eqFunction_81(data);

  BooleanNetwork1_eqFunction_82(data);

  BooleanNetwork1_eqFunction_83(data);

  BooleanNetwork1_eqFunction_84(data);

  BooleanNetwork1_eqFunction_85(data);

  BooleanNetwork1_eqFunction_87(data);

  BooleanNetwork1_eqFunction_88(data);

  BooleanNetwork1_eqFunction_89(data);

  BooleanNetwork1_eqFunction_90(data);

  BooleanNetwork1_eqFunction_91(data);

  BooleanNetwork1_eqFunction_92(data);

  BooleanNetwork1_eqFunction_65(data);

  BooleanNetwork1_eqFunction_66(data);

  BooleanNetwork1_eqFunction_67(data);

  BooleanNetwork1_eqFunction_68(data);

  BooleanNetwork1_eqFunction_60(data);

  BooleanNetwork1_eqFunction_61(data);

  BooleanNetwork1_eqFunction_62(data);

  BooleanNetwork1_eqFunction_63(data);

  BooleanNetwork1_eqFunction_64(data);
}
/* for continuous time variables */
int BooleanNetwork1_functionAlgebraics(DATA *data)
{
  TRACE_PUSH
  
  data->simulationInfo.discreteCall = 0;
  functionAlg_system0(data);
  
  TRACE_POP
  return 0;
}

#ifdef __cplusplus
}
#endif
