/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for CoupledClutches generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "CoupledClutches_functions.h"
#include "CoupledClutches_model.h"
#include "CoupledClutches_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void CoupledClutches_function_initSample(DATA *data)
{
  long i=0;
}

const char *CoupledClutches_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"time < sin1.startTime",
  "clutch3.fn <= 0.0",
  "time < sin2.startTime",
  "clutch1.fn <= 0.0",
  "time < step1.startTime",
  "clutch2.fn <= 0.0",
  "pre(clutch2.mode) == 0 and (clutch2.sa > clutch2.tau0_max or pre(clutch2.startForward) and clutch2.sa > clutch2.tau0) or pre(clutch2.mode) == -1 and clutch2.w_rel > clutch2.w_small or initial() and clutch2.w_rel > 0.0",
  "pre(clutch1.mode) == 0 and (clutch1.sa > clutch1.tau0_max or pre(clutch1.startForward) and clutch1.sa > clutch1.tau0) or pre(clutch1.mode) == -1 and clutch1.w_rel > clutch1.w_small or initial() and clutch1.w_rel > 0.0",
  "pre(clutch1.mode) == 0 and (clutch1.sa < (-clutch1.tau0_max) or pre(clutch1.startBackward) and clutch1.sa < (-clutch1.tau0)) or pre(clutch1.mode) == 1 and clutch1.w_rel < (-clutch1.w_small) or initial() and clutch1.w_rel < 0.0",
  "pre(clutch3.mode) == 0 and (clutch3.sa > clutch3.tau0_max or pre(clutch3.startForward) and clutch3.sa > clutch3.tau0) or pre(clutch3.mode) == -1 and clutch3.w_rel > clutch3.w_small or initial() and clutch3.w_rel > 0.0",
  "pre(clutch3.mode) == 0 and (clutch3.sa < (-clutch3.tau0_max) or pre(clutch3.startBackward) and clutch3.sa < (-clutch3.tau0)) or pre(clutch3.mode) == 1 and clutch3.w_rel < (-clutch3.w_small) or initial() and clutch3.w_rel < 0.0",
  "pre(clutch2.mode) == 0 and (clutch2.sa < (-clutch2.tau0_max) or pre(clutch2.startBackward) and clutch2.sa < (-clutch2.tau0)) or pre(clutch2.mode) == 1 and clutch2.w_rel < (-clutch2.w_small) or initial() and clutch2.w_rel < 0.0",
  "clutch2.w_rel > 0.0",
  "clutch2.w_rel < 0.0",
  "clutch3.w_rel > 0.0",
  "clutch3.w_rel < 0.0",
  "clutch1.w_rel > 0.0",
  "clutch1.w_rel < 0.0"};
  static const int occurEqs0[] = {1,100};
  static const int occurEqs1[] = {1,95};
  static const int occurEqs2[] = {1,88};
  static const int occurEqs3[] = {1,92};
  static const int occurEqs4[] = {1,83};
  static const int occurEqs5[] = {1,87};
  static const int occurEqs6[] = {1,-1};
  static const int occurEqs7[] = {1,-1};
  static const int occurEqs8[] = {1,-1};
  static const int occurEqs9[] = {1,-1};
  static const int occurEqs10[] = {1,-1};
  static const int occurEqs11[] = {1,-1};
  static const int occurEqs12[] = {1,127};
  static const int occurEqs13[] = {1,127};
  static const int occurEqs14[] = {1,130};
  static const int occurEqs15[] = {1,130};
  static const int occurEqs16[] = {1,125};
  static const int occurEqs17[] = {1,125};
  static const int *occurEqs[] = {occurEqs0,occurEqs1,occurEqs2,occurEqs3,occurEqs4,occurEqs5,occurEqs6,occurEqs7,occurEqs8,occurEqs9,occurEqs10,occurEqs11,occurEqs12,occurEqs13,occurEqs14,occurEqs15,occurEqs16,occurEqs17};
  *out_EquationIndexes = (int*) occurEqs[i];
  return res[i];
}

/* forwarded equations */
extern void CoupledClutches_eqFunction_83(DATA* data);
extern void CoupledClutches_eqFunction_84(DATA* data);
extern void CoupledClutches_eqFunction_85(DATA* data);
extern void CoupledClutches_eqFunction_86(DATA* data);
extern void CoupledClutches_eqFunction_87(DATA* data);
extern void CoupledClutches_eqFunction_88(DATA* data);
extern void CoupledClutches_eqFunction_89(DATA* data);
extern void CoupledClutches_eqFunction_90(DATA* data);
extern void CoupledClutches_eqFunction_91(DATA* data);
extern void CoupledClutches_eqFunction_92(DATA* data);
extern void CoupledClutches_eqFunction_94(DATA* data);
extern void CoupledClutches_eqFunction_95(DATA* data);
extern void CoupledClutches_eqFunction_96(DATA* data);
extern void CoupledClutches_eqFunction_97(DATA* data);
extern void CoupledClutches_eqFunction_100(DATA* data);
extern void CoupledClutches_eqFunction_123(DATA* data);
extern void CoupledClutches_eqFunction_124(DATA* data);
extern void CoupledClutches_eqFunction_125(DATA* data);
extern void CoupledClutches_eqFunction_126(DATA* data);
extern void CoupledClutches_eqFunction_127(DATA* data);
extern void CoupledClutches_eqFunction_130(DATA* data);
extern void CoupledClutches_eqFunction_131(DATA* data);

int CoupledClutches_function_ZeroCrossingsEquations(DATA *data)
{
  TRACE_PUSH
  
  data->simulationInfo.callStatistics.functionZeroCrossingsEquations++;
  
  data->simulationInfo.discreteCall = 0;
  CoupledClutches_eqFunction_83(data);

  CoupledClutches_eqFunction_84(data);

  CoupledClutches_eqFunction_85(data);

  CoupledClutches_eqFunction_86(data);

  CoupledClutches_eqFunction_87(data);

  CoupledClutches_eqFunction_88(data);

  CoupledClutches_eqFunction_89(data);

  CoupledClutches_eqFunction_90(data);

  CoupledClutches_eqFunction_91(data);

  CoupledClutches_eqFunction_92(data);

  CoupledClutches_eqFunction_94(data);

  CoupledClutches_eqFunction_95(data);

  CoupledClutches_eqFunction_96(data);

  CoupledClutches_eqFunction_97(data);

  CoupledClutches_eqFunction_100(data);

  CoupledClutches_eqFunction_123(data);

  CoupledClutches_eqFunction_124(data);

  CoupledClutches_eqFunction_125(data);

  CoupledClutches_eqFunction_126(data);

  CoupledClutches_eqFunction_127(data);

  CoupledClutches_eqFunction_130(data);

  CoupledClutches_eqFunction_131(data);
  
  TRACE_POP
  return 0;
}

int CoupledClutches_function_ZeroCrossings(DATA *data, double *gout)
{
  TRACE_PUSH
  modelica_boolean tmp1365;
  modelica_boolean tmp1366;
  modelica_boolean tmp1367;
  modelica_boolean tmp1368;
  modelica_boolean tmp1369;
  modelica_boolean tmp1370;
  modelica_boolean tmp1372;
  modelica_boolean tmp1373;
  modelica_boolean tmp1375;
  modelica_boolean tmp1376;
  modelica_boolean tmp1378;
  modelica_boolean tmp1379;
  modelica_boolean tmp1381;
  modelica_boolean tmp1382;
  modelica_boolean tmp1384;
  modelica_boolean tmp1385;
  modelica_boolean tmp1387;
  modelica_boolean tmp1388;
  modelica_boolean tmp1390;
  modelica_boolean tmp1391;
  modelica_boolean tmp1393;
  modelica_boolean tmp1394;
  modelica_boolean tmp1396;
  modelica_boolean tmp1397;
  modelica_boolean tmp1399;
  modelica_boolean tmp1400;
  modelica_boolean tmp1402;
  modelica_boolean tmp1403;
  modelica_boolean tmp1405;
  modelica_boolean tmp1406;
  modelica_boolean tmp1407;
  modelica_boolean tmp1408;
  modelica_boolean tmp1409;
  modelica_boolean tmp1410;
  modelica_boolean tmp1411;
  modelica_boolean tmp1412;
  
  data->simulationInfo.callStatistics.functionZeroCrossings++;
  
  tmp1365 = LessZC(time, $Psin1$PstartTime, data->simulationInfo.storedRelations[0]);
  gout[0] = (tmp1365) ? 1 : -1;
  tmp1366 = LessEqZC($Pclutch3$Pfn, 0.0, data->simulationInfo.storedRelations[1]);
  gout[1] = (tmp1366) ? 1 : -1;
  tmp1367 = LessZC(time, $Psin2$PstartTime, data->simulationInfo.storedRelations[2]);
  gout[2] = (tmp1367) ? 1 : -1;
  tmp1368 = LessEqZC($Pclutch1$Pfn, 0.0, data->simulationInfo.storedRelations[3]);
  gout[3] = (tmp1368) ? 1 : -1;
  tmp1369 = LessZC(time, $Pstep1$PstartTime, data->simulationInfo.storedRelations[4]);
  gout[4] = (tmp1369) ? 1 : -1;
  tmp1370 = LessEqZC($Pclutch2$Pfn, 0.0, data->simulationInfo.storedRelations[5]);
  gout[5] = (tmp1370) ? 1 : -1;
  tmp1372 = GreaterZC($Pclutch2$Psa, $Pclutch2$Ptau0_max, data->simulationInfo.storedRelations[6]);
  tmp1373 = GreaterZC($Pclutch2$Psa, $Pclutch2$Ptau0, data->simulationInfo.storedRelations[7]);
  tmp1375 = GreaterZC($Pclutch2$Pw_rel, $Pclutch2$Pw_small, data->simulationInfo.storedRelations[8]);
  tmp1376 = GreaterZC($Pclutch2$Pw_rel, 0.0, data->simulationInfo.storedRelations[9]);
  gout[6] = ((((($P$PRE$Pclutch2$Pmode == (modelica_integer) 0) && (tmp1372 || ($P$PRE$Pclutch2$PstartForward && tmp1373))) || (($P$PRE$Pclutch2$Pmode == (modelica_integer) -1) && tmp1375)) || (initial() && tmp1376))) ? 1 : -1;
  tmp1378 = GreaterZC($Pclutch1$Psa, $Pclutch1$Ptau0_max, data->simulationInfo.storedRelations[10]);
  tmp1379 = GreaterZC($Pclutch1$Psa, $Pclutch1$Ptau0, data->simulationInfo.storedRelations[11]);
  tmp1381 = GreaterZC($Pclutch1$Pw_rel, $Pclutch1$Pw_small, data->simulationInfo.storedRelations[12]);
  tmp1382 = GreaterZC($Pclutch1$Pw_rel, 0.0, data->simulationInfo.storedRelations[13]);
  gout[7] = ((((($P$PRE$Pclutch1$Pmode == (modelica_integer) 0) && (tmp1378 || ($P$PRE$Pclutch1$PstartForward && tmp1379))) || (($P$PRE$Pclutch1$Pmode == (modelica_integer) -1) && tmp1381)) || (initial() && tmp1382))) ? 1 : -1;
  tmp1384 = LessZC($Pclutch1$Psa, (-$Pclutch1$Ptau0_max), data->simulationInfo.storedRelations[14]);
  tmp1385 = LessZC($Pclutch1$Psa, (-$Pclutch1$Ptau0), data->simulationInfo.storedRelations[15]);
  tmp1387 = LessZC($Pclutch1$Pw_rel, (-$Pclutch1$Pw_small), data->simulationInfo.storedRelations[16]);
  tmp1388 = LessZC($Pclutch1$Pw_rel, 0.0, data->simulationInfo.storedRelations[17]);
  gout[8] = ((((($P$PRE$Pclutch1$Pmode == (modelica_integer) 0) && (tmp1384 || ($P$PRE$Pclutch1$PstartBackward && tmp1385))) || (($P$PRE$Pclutch1$Pmode == (modelica_integer) 1) && tmp1387)) || (initial() && tmp1388))) ? 1 : -1;
  tmp1390 = GreaterZC($Pclutch3$Psa, $Pclutch3$Ptau0_max, data->simulationInfo.storedRelations[18]);
  tmp1391 = GreaterZC($Pclutch3$Psa, $Pclutch3$Ptau0, data->simulationInfo.storedRelations[19]);
  tmp1393 = GreaterZC($Pclutch3$Pw_rel, $Pclutch3$Pw_small, data->simulationInfo.storedRelations[20]);
  tmp1394 = GreaterZC($Pclutch3$Pw_rel, 0.0, data->simulationInfo.storedRelations[21]);
  gout[9] = ((((($P$PRE$Pclutch3$Pmode == (modelica_integer) 0) && (tmp1390 || ($P$PRE$Pclutch3$PstartForward && tmp1391))) || (($P$PRE$Pclutch3$Pmode == (modelica_integer) -1) && tmp1393)) || (initial() && tmp1394))) ? 1 : -1;
  tmp1396 = LessZC($Pclutch3$Psa, (-$Pclutch3$Ptau0_max), data->simulationInfo.storedRelations[22]);
  tmp1397 = LessZC($Pclutch3$Psa, (-$Pclutch3$Ptau0), data->simulationInfo.storedRelations[23]);
  tmp1399 = LessZC($Pclutch3$Pw_rel, (-$Pclutch3$Pw_small), data->simulationInfo.storedRelations[24]);
  tmp1400 = LessZC($Pclutch3$Pw_rel, 0.0, data->simulationInfo.storedRelations[25]);
  gout[10] = ((((($P$PRE$Pclutch3$Pmode == (modelica_integer) 0) && (tmp1396 || ($P$PRE$Pclutch3$PstartBackward && tmp1397))) || (($P$PRE$Pclutch3$Pmode == (modelica_integer) 1) && tmp1399)) || (initial() && tmp1400))) ? 1 : -1;
  tmp1402 = LessZC($Pclutch2$Psa, (-$Pclutch2$Ptau0_max), data->simulationInfo.storedRelations[26]);
  tmp1403 = LessZC($Pclutch2$Psa, (-$Pclutch2$Ptau0), data->simulationInfo.storedRelations[27]);
  tmp1405 = LessZC($Pclutch2$Pw_rel, (-$Pclutch2$Pw_small), data->simulationInfo.storedRelations[28]);
  tmp1406 = LessZC($Pclutch2$Pw_rel, 0.0, data->simulationInfo.storedRelations[29]);
  gout[11] = ((((($P$PRE$Pclutch2$Pmode == (modelica_integer) 0) && (tmp1402 || ($P$PRE$Pclutch2$PstartBackward && tmp1403))) || (($P$PRE$Pclutch2$Pmode == (modelica_integer) 1) && tmp1405)) || (initial() && tmp1406))) ? 1 : -1;
  tmp1407 = GreaterZC($Pclutch2$Pw_rel, 0.0, data->simulationInfo.storedRelations[9]);
  gout[12] = (tmp1407) ? 1 : -1;
  tmp1408 = LessZC($Pclutch2$Pw_rel, 0.0, data->simulationInfo.storedRelations[29]);
  gout[13] = (tmp1408) ? 1 : -1;
  tmp1409 = GreaterZC($Pclutch3$Pw_rel, 0.0, data->simulationInfo.storedRelations[21]);
  gout[14] = (tmp1409) ? 1 : -1;
  tmp1410 = LessZC($Pclutch3$Pw_rel, 0.0, data->simulationInfo.storedRelations[25]);
  gout[15] = (tmp1410) ? 1 : -1;
  tmp1411 = GreaterZC($Pclutch1$Pw_rel, 0.0, data->simulationInfo.storedRelations[13]);
  gout[16] = (tmp1411) ? 1 : -1;
  tmp1412 = LessZC($Pclutch1$Pw_rel, 0.0, data->simulationInfo.storedRelations[17]);
  gout[17] = (tmp1412) ? 1 : -1;
  
  TRACE_POP
  return 0;
}

const char *CoupledClutches_relationDescription(int i)
{
  const char *res[] = {"time < sin1.startTime",
  "clutch3.fn <= 0.0",
  "time < sin2.startTime",
  "clutch1.fn <= 0.0",
  "time < step1.startTime",
  "clutch2.fn <= 0.0",
  "clutch2.sa > clutch2.tau0_max",
  "clutch2.sa > clutch2.tau0",
  "clutch2.w_rel > clutch2.w_small",
  "clutch2.w_rel > 0.0",
  "clutch1.sa > clutch1.tau0_max",
  "clutch1.sa > clutch1.tau0",
  "clutch1.w_rel > clutch1.w_small",
  "clutch1.w_rel > 0.0",
  "clutch1.sa < (-clutch1.tau0_max)",
  "clutch1.sa < (-clutch1.tau0)",
  "clutch1.w_rel < (-clutch1.w_small)",
  "clutch1.w_rel < 0.0",
  "clutch3.sa > clutch3.tau0_max",
  "clutch3.sa > clutch3.tau0",
  "clutch3.w_rel > clutch3.w_small",
  "clutch3.w_rel > 0.0",
  "clutch3.sa < (-clutch3.tau0_max)",
  "clutch3.sa < (-clutch3.tau0)",
  "clutch3.w_rel < (-clutch3.w_small)",
  "clutch3.w_rel < 0.0",
  "clutch2.sa < (-clutch2.tau0_max)",
  "clutch2.sa < (-clutch2.tau0)",
  "clutch2.w_rel < (-clutch2.w_small)",
  "clutch2.w_rel < 0.0"};
  return res[i];
}

int CoupledClutches_function_updateRelations(DATA *data, int evalforZeroCross)
{
  TRACE_PUSH
  modelica_boolean tmp1413;
  modelica_boolean tmp1414;
  modelica_boolean tmp1415;
  modelica_boolean tmp1416;
  modelica_boolean tmp1417;
  modelica_boolean tmp1418;
  modelica_boolean tmp1419;
  modelica_boolean tmp1420;
  modelica_boolean tmp1421;
  modelica_boolean tmp1422;
  modelica_boolean tmp1423;
  modelica_boolean tmp1424;
  modelica_boolean tmp1425;
  modelica_boolean tmp1426;
  modelica_boolean tmp1427;
  modelica_boolean tmp1428;
  modelica_boolean tmp1429;
  modelica_boolean tmp1430;
  modelica_boolean tmp1431;
  modelica_boolean tmp1432;
  modelica_boolean tmp1433;
  modelica_boolean tmp1434;
  modelica_boolean tmp1435;
  modelica_boolean tmp1436;
  modelica_boolean tmp1437;
  modelica_boolean tmp1438;
  modelica_boolean tmp1439;
  modelica_boolean tmp1440;
  modelica_boolean tmp1441;
  modelica_boolean tmp1442;
  
  
  if(evalforZeroCross)
  {
    tmp1413 = LessZC(time, $Psin1$PstartTime, data->simulationInfo.storedRelations[0]);
    data->simulationInfo.relations[0] = tmp1413;
    tmp1414 = LessEqZC($Pclutch3$Pfn, 0.0, data->simulationInfo.storedRelations[1]);
    data->simulationInfo.relations[1] = tmp1414;
    tmp1415 = LessZC(time, $Psin2$PstartTime, data->simulationInfo.storedRelations[2]);
    data->simulationInfo.relations[2] = tmp1415;
    tmp1416 = LessEqZC($Pclutch1$Pfn, 0.0, data->simulationInfo.storedRelations[3]);
    data->simulationInfo.relations[3] = tmp1416;
    tmp1417 = LessZC(time, $Pstep1$PstartTime, data->simulationInfo.storedRelations[4]);
    data->simulationInfo.relations[4] = tmp1417;
    tmp1418 = LessEqZC($Pclutch2$Pfn, 0.0, data->simulationInfo.storedRelations[5]);
    data->simulationInfo.relations[5] = tmp1418;
    tmp1419 = GreaterZC($Pclutch2$Psa, $Pclutch2$Ptau0_max, data->simulationInfo.storedRelations[6]);
    data->simulationInfo.relations[6] = tmp1419;
    tmp1420 = GreaterZC($Pclutch2$Psa, $Pclutch2$Ptau0, data->simulationInfo.storedRelations[7]);
    data->simulationInfo.relations[7] = tmp1420;
    tmp1421 = GreaterZC($Pclutch2$Pw_rel, $Pclutch2$Pw_small, data->simulationInfo.storedRelations[8]);
    data->simulationInfo.relations[8] = tmp1421;
    tmp1422 = GreaterZC($Pclutch2$Pw_rel, 0.0, data->simulationInfo.storedRelations[9]);
    data->simulationInfo.relations[9] = tmp1422;
    tmp1423 = GreaterZC($Pclutch1$Psa, $Pclutch1$Ptau0_max, data->simulationInfo.storedRelations[10]);
    data->simulationInfo.relations[10] = tmp1423;
    tmp1424 = GreaterZC($Pclutch1$Psa, $Pclutch1$Ptau0, data->simulationInfo.storedRelations[11]);
    data->simulationInfo.relations[11] = tmp1424;
    tmp1425 = GreaterZC($Pclutch1$Pw_rel, $Pclutch1$Pw_small, data->simulationInfo.storedRelations[12]);
    data->simulationInfo.relations[12] = tmp1425;
    tmp1426 = GreaterZC($Pclutch1$Pw_rel, 0.0, data->simulationInfo.storedRelations[13]);
    data->simulationInfo.relations[13] = tmp1426;
    tmp1427 = LessZC($Pclutch1$Psa, (-$Pclutch1$Ptau0_max), data->simulationInfo.storedRelations[14]);
    data->simulationInfo.relations[14] = tmp1427;
    tmp1428 = LessZC($Pclutch1$Psa, (-$Pclutch1$Ptau0), data->simulationInfo.storedRelations[15]);
    data->simulationInfo.relations[15] = tmp1428;
    tmp1429 = LessZC($Pclutch1$Pw_rel, (-$Pclutch1$Pw_small), data->simulationInfo.storedRelations[16]);
    data->simulationInfo.relations[16] = tmp1429;
    tmp1430 = LessZC($Pclutch1$Pw_rel, 0.0, data->simulationInfo.storedRelations[17]);
    data->simulationInfo.relations[17] = tmp1430;
    tmp1431 = GreaterZC($Pclutch3$Psa, $Pclutch3$Ptau0_max, data->simulationInfo.storedRelations[18]);
    data->simulationInfo.relations[18] = tmp1431;
    tmp1432 = GreaterZC($Pclutch3$Psa, $Pclutch3$Ptau0, data->simulationInfo.storedRelations[19]);
    data->simulationInfo.relations[19] = tmp1432;
    tmp1433 = GreaterZC($Pclutch3$Pw_rel, $Pclutch3$Pw_small, data->simulationInfo.storedRelations[20]);
    data->simulationInfo.relations[20] = tmp1433;
    tmp1434 = GreaterZC($Pclutch3$Pw_rel, 0.0, data->simulationInfo.storedRelations[21]);
    data->simulationInfo.relations[21] = tmp1434;
    tmp1435 = LessZC($Pclutch3$Psa, (-$Pclutch3$Ptau0_max), data->simulationInfo.storedRelations[22]);
    data->simulationInfo.relations[22] = tmp1435;
    tmp1436 = LessZC($Pclutch3$Psa, (-$Pclutch3$Ptau0), data->simulationInfo.storedRelations[23]);
    data->simulationInfo.relations[23] = tmp1436;
    tmp1437 = LessZC($Pclutch3$Pw_rel, (-$Pclutch3$Pw_small), data->simulationInfo.storedRelations[24]);
    data->simulationInfo.relations[24] = tmp1437;
    tmp1438 = LessZC($Pclutch3$Pw_rel, 0.0, data->simulationInfo.storedRelations[25]);
    data->simulationInfo.relations[25] = tmp1438;
    tmp1439 = LessZC($Pclutch2$Psa, (-$Pclutch2$Ptau0_max), data->simulationInfo.storedRelations[26]);
    data->simulationInfo.relations[26] = tmp1439;
    tmp1440 = LessZC($Pclutch2$Psa, (-$Pclutch2$Ptau0), data->simulationInfo.storedRelations[27]);
    data->simulationInfo.relations[27] = tmp1440;
    tmp1441 = LessZC($Pclutch2$Pw_rel, (-$Pclutch2$Pw_small), data->simulationInfo.storedRelations[28]);
    data->simulationInfo.relations[28] = tmp1441;
    tmp1442 = LessZC($Pclutch2$Pw_rel, 0.0, data->simulationInfo.storedRelations[29]);
    data->simulationInfo.relations[29] = tmp1442;
  }
  else
  {
    data->simulationInfo.relations[0] = (time < $Psin1$PstartTime);
    data->simulationInfo.relations[1] = ($Pclutch3$Pfn <= 0.0);
    data->simulationInfo.relations[2] = (time < $Psin2$PstartTime);
    data->simulationInfo.relations[3] = ($Pclutch1$Pfn <= 0.0);
    data->simulationInfo.relations[4] = (time < $Pstep1$PstartTime);
    data->simulationInfo.relations[5] = ($Pclutch2$Pfn <= 0.0);
    data->simulationInfo.relations[6] = ($Pclutch2$Psa > $Pclutch2$Ptau0_max);
    data->simulationInfo.relations[7] = ($Pclutch2$Psa > $Pclutch2$Ptau0);
    data->simulationInfo.relations[8] = ($Pclutch2$Pw_rel > $Pclutch2$Pw_small);
    data->simulationInfo.relations[9] = ($Pclutch2$Pw_rel > 0.0);
    data->simulationInfo.relations[10] = ($Pclutch1$Psa > $Pclutch1$Ptau0_max);
    data->simulationInfo.relations[11] = ($Pclutch1$Psa > $Pclutch1$Ptau0);
    data->simulationInfo.relations[12] = ($Pclutch1$Pw_rel > $Pclutch1$Pw_small);
    data->simulationInfo.relations[13] = ($Pclutch1$Pw_rel > 0.0);
    data->simulationInfo.relations[14] = ($Pclutch1$Psa < (-$Pclutch1$Ptau0_max));
    data->simulationInfo.relations[15] = ($Pclutch1$Psa < (-$Pclutch1$Ptau0));
    data->simulationInfo.relations[16] = ($Pclutch1$Pw_rel < (-$Pclutch1$Pw_small));
    data->simulationInfo.relations[17] = ($Pclutch1$Pw_rel < 0.0);
    data->simulationInfo.relations[18] = ($Pclutch3$Psa > $Pclutch3$Ptau0_max);
    data->simulationInfo.relations[19] = ($Pclutch3$Psa > $Pclutch3$Ptau0);
    data->simulationInfo.relations[20] = ($Pclutch3$Pw_rel > $Pclutch3$Pw_small);
    data->simulationInfo.relations[21] = ($Pclutch3$Pw_rel > 0.0);
    data->simulationInfo.relations[22] = ($Pclutch3$Psa < (-$Pclutch3$Ptau0_max));
    data->simulationInfo.relations[23] = ($Pclutch3$Psa < (-$Pclutch3$Ptau0));
    data->simulationInfo.relations[24] = ($Pclutch3$Pw_rel < (-$Pclutch3$Pw_small));
    data->simulationInfo.relations[25] = ($Pclutch3$Pw_rel < 0.0);
    data->simulationInfo.relations[26] = ($Pclutch2$Psa < (-$Pclutch2$Ptau0_max));
    data->simulationInfo.relations[27] = ($Pclutch2$Psa < (-$Pclutch2$Ptau0));
    data->simulationInfo.relations[28] = ($Pclutch2$Pw_rel < (-$Pclutch2$Pw_small));
    data->simulationInfo.relations[29] = ($Pclutch2$Pw_rel < 0.0);
  }
  
  TRACE_POP
  return 0;
}

int CoupledClutches_checkForDiscreteChanges(DATA *data)
{
  TRACE_PUSH
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes at time=%.12g", data->localData[0]->timeValue);
  if($Pclutch1$Pfree != $P$PRE$Pclutch1$Pfree)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch1._free from %d to %d", $P$PRE$Pclutch1$Pfree, $Pclutch1$Pfree);
    needToIterate = 1;
  }
  if($Pclutch1$PstartForward != $P$PRE$Pclutch1$PstartForward)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch1._startForward from %d to %d", $P$PRE$Pclutch1$PstartForward, $Pclutch1$PstartForward);
    needToIterate = 1;
  }
  if($Pclutch1$PstartBackward != $P$PRE$Pclutch1$PstartBackward)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch1._startBackward from %d to %d", $P$PRE$Pclutch1$PstartBackward, $Pclutch1$PstartBackward);
    needToIterate = 1;
  }
  if($Pclutch1$Plocked != $P$PRE$Pclutch1$Plocked)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch1._locked from %d to %d", $P$PRE$Pclutch1$Plocked, $Pclutch1$Plocked);
    needToIterate = 1;
  }
  if($Pclutch1$Pmode != $P$PRE$Pclutch1$Pmode)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch1._mode from %ld to %ld", $P$PRE$Pclutch1$Pmode, $Pclutch1$Pmode);
    needToIterate = 1;
  }
  if($Pclutch2$Pfree != $P$PRE$Pclutch2$Pfree)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch2._free from %d to %d", $P$PRE$Pclutch2$Pfree, $Pclutch2$Pfree);
    needToIterate = 1;
  }
  if($Pclutch2$PstartForward != $P$PRE$Pclutch2$PstartForward)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch2._startForward from %d to %d", $P$PRE$Pclutch2$PstartForward, $Pclutch2$PstartForward);
    needToIterate = 1;
  }
  if($Pclutch2$PstartBackward != $P$PRE$Pclutch2$PstartBackward)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch2._startBackward from %d to %d", $P$PRE$Pclutch2$PstartBackward, $Pclutch2$PstartBackward);
    needToIterate = 1;
  }
  if($Pclutch2$Plocked != $P$PRE$Pclutch2$Plocked)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch2._locked from %d to %d", $P$PRE$Pclutch2$Plocked, $Pclutch2$Plocked);
    needToIterate = 1;
  }
  if($Pclutch2$Pmode != $P$PRE$Pclutch2$Pmode)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch2._mode from %ld to %ld", $P$PRE$Pclutch2$Pmode, $Pclutch2$Pmode);
    needToIterate = 1;
  }
  if($Pclutch3$Pfree != $P$PRE$Pclutch3$Pfree)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch3._free from %d to %d", $P$PRE$Pclutch3$Pfree, $Pclutch3$Pfree);
    needToIterate = 1;
  }
  if($Pclutch3$PstartForward != $P$PRE$Pclutch3$PstartForward)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch3._startForward from %d to %d", $P$PRE$Pclutch3$PstartForward, $Pclutch3$PstartForward);
    needToIterate = 1;
  }
  if($Pclutch3$PstartBackward != $P$PRE$Pclutch3$PstartBackward)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch3._startBackward from %d to %d", $P$PRE$Pclutch3$PstartBackward, $Pclutch3$PstartBackward);
    needToIterate = 1;
  }
  if($Pclutch3$Plocked != $P$PRE$Pclutch3$Plocked)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch3._locked from %d to %d", $P$PRE$Pclutch3$Plocked, $Pclutch3$Plocked);
    needToIterate = 1;
  }
  if($Pclutch3$Pmode != $P$PRE$Pclutch3$Pmode)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: clutch3._mode from %ld to %ld", $P$PRE$Pclutch3$Pmode, $Pclutch3$Pmode);
    needToIterate = 1;
  }
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  TRACE_POP
  return needToIterate;
}

#if defined(__cplusplus)
}
#endif

