/* Algebraic */
/* Simulation code for CoupledClutches generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "CoupledClutches_functions.h"
#include "CoupledClutches_model.h"
#include "CoupledClutches_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#ifdef __cplusplus
extern "C" {
#endif


/* forwarded equations */
extern void CoupledClutches_eqFunction_125(DATA* data);
extern void CoupledClutches_eqFunction_127(DATA* data);
extern void CoupledClutches_eqFunction_128(DATA* data);
extern void CoupledClutches_eqFunction_129(DATA* data);
extern void CoupledClutches_eqFunction_130(DATA* data);
extern void CoupledClutches_eqFunction_133(DATA* data);
extern void CoupledClutches_eqFunction_135(DATA* data);
extern void CoupledClutches_eqFunction_136(DATA* data);
extern void CoupledClutches_eqFunction_137(DATA* data);
extern void CoupledClutches_eqFunction_138(DATA* data);
extern void CoupledClutches_eqFunction_139(DATA* data);
extern void CoupledClutches_eqFunction_140(DATA* data);
extern void CoupledClutches_eqFunction_141(DATA* data);

static void functionAlg_system0(DATA *data)
{
  CoupledClutches_eqFunction_125(data);

  CoupledClutches_eqFunction_127(data);

  CoupledClutches_eqFunction_128(data);

  CoupledClutches_eqFunction_129(data);

  CoupledClutches_eqFunction_130(data);

  CoupledClutches_eqFunction_133(data);

  CoupledClutches_eqFunction_135(data);

  CoupledClutches_eqFunction_136(data);

  CoupledClutches_eqFunction_137(data);

  CoupledClutches_eqFunction_138(data);

  CoupledClutches_eqFunction_139(data);

  CoupledClutches_eqFunction_140(data);

  CoupledClutches_eqFunction_141(data);
}
/* for continuous time variables */
int CoupledClutches_functionAlgebraics(DATA *data)
{
  TRACE_PUSH
  
  data->simulationInfo.discreteCall = 0;
  functionAlg_system0(data);
  
  TRACE_POP
  return 0;
}

#ifdef __cplusplus
}
#endif
