/* Non Linear Systems */
/* Simulation code for CoupledClutches generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "CoupledClutches_functions.h"
#include "CoupledClutches_model.h"
#include "CoupledClutches_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "CoupledClutches_12jac.h"
#if defined(__cplusplus)
extern "C" {
#endif

/*
 equation index: 49
 type: SIMPLE_ASSIGN
 clutch2._startForward = $PRE.clutch2.mode == 0 and (clutch2.sa > clutch2.tau0_max or $PRE.clutch2.startForward and clutch2.sa > clutch2.tau0) or $PRE.clutch2.mode == -1 and clutch2.w_rel > clutch2.w_small or clutch2.w_rel > 0.0
 */
void CoupledClutches_eqFunction_49(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,49};
  modelica_boolean tmp1072;
  modelica_boolean tmp1073;
  modelica_boolean tmp1075;
  modelica_boolean tmp1076;
  RELATIONHYSTERESIS(tmp1072, $Pclutch2$Psa, $Pclutch2$Ptau0_max, 6, Greater);
  RELATIONHYSTERESIS(tmp1073, $Pclutch2$Psa, $Pclutch2$Ptau0, 7, Greater);
  RELATIONHYSTERESIS(tmp1075, $Pclutch2$Pw_rel, $Pclutch2$Pw_small, 8, Greater);
  RELATIONHYSTERESIS(tmp1076, $Pclutch2$Pw_rel, 0.0, 9, Greater);
  $Pclutch2$PstartForward = (((((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) 0) && (tmp1072 || ($P$PRE$Pclutch2$PstartForward && tmp1073))) || (((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) -1) && tmp1075)) || tmp1076);
  TRACE_POP
}
/*
 equation index: 50
 type: SIMPLE_ASSIGN
 clutch3._startForward = $PRE.clutch3.mode == 0 and (clutch3.sa > clutch3.tau0_max or $PRE.clutch3.startForward and clutch3.sa > clutch3.tau0) or $PRE.clutch3.mode == -1 and clutch3.w_rel > clutch3.w_small or clutch3.w_rel > 0.0
 */
void CoupledClutches_eqFunction_50(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,50};
  modelica_boolean tmp1078;
  modelica_boolean tmp1079;
  modelica_boolean tmp1081;
  modelica_boolean tmp1082;
  RELATIONHYSTERESIS(tmp1078, $Pclutch3$Psa, $Pclutch3$Ptau0_max, 18, Greater);
  RELATIONHYSTERESIS(tmp1079, $Pclutch3$Psa, $Pclutch3$Ptau0, 19, Greater);
  RELATIONHYSTERESIS(tmp1081, $Pclutch3$Pw_rel, $Pclutch3$Pw_small, 20, Greater);
  RELATIONHYSTERESIS(tmp1082, $Pclutch3$Pw_rel, 0.0, 21, Greater);
  $Pclutch3$PstartForward = (((((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) 0) && (tmp1078 || ($P$PRE$Pclutch3$PstartForward && tmp1079))) || (((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) -1) && tmp1081)) || tmp1082);
  TRACE_POP
}
/*
 equation index: 51
 type: SIMPLE_ASSIGN
 clutch3._startBackward = $PRE.clutch3.mode == 0 and (clutch3.sa < (-clutch3.tau0_max) or $PRE.clutch3.startBackward and clutch3.sa < (-clutch3.tau0)) or $PRE.clutch3.mode == 1 and clutch3.w_rel < (-clutch3.w_small) or clutch3.w_rel < 0.0
 */
void CoupledClutches_eqFunction_51(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,51};
  modelica_boolean tmp1084;
  modelica_boolean tmp1085;
  modelica_boolean tmp1087;
  modelica_boolean tmp1088;
  RELATIONHYSTERESIS(tmp1084, $Pclutch3$Psa, (-$Pclutch3$Ptau0_max), 22, Less);
  RELATIONHYSTERESIS(tmp1085, $Pclutch3$Psa, (-$Pclutch3$Ptau0), 23, Less);
  RELATIONHYSTERESIS(tmp1087, $Pclutch3$Pw_rel, (-$Pclutch3$Pw_small), 24, Less);
  RELATIONHYSTERESIS(tmp1088, $Pclutch3$Pw_rel, 0.0, 25, Less);
  $Pclutch3$PstartBackward = (((((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) 0) && (tmp1084 || ($P$PRE$Pclutch3$PstartBackward && tmp1085))) || (((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) 1) && tmp1087)) || tmp1088);
  TRACE_POP
}
/*
 equation index: 52
 type: SIMPLE_ASSIGN
 clutch2._startBackward = $PRE.clutch2.mode == 0 and (clutch2.sa < (-clutch2.tau0_max) or $PRE.clutch2.startBackward and clutch2.sa < (-clutch2.tau0)) or $PRE.clutch2.mode == 1 and clutch2.w_rel < (-clutch2.w_small) or clutch2.w_rel < 0.0
 */
void CoupledClutches_eqFunction_52(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,52};
  modelica_boolean tmp1090;
  modelica_boolean tmp1091;
  modelica_boolean tmp1093;
  modelica_boolean tmp1094;
  RELATIONHYSTERESIS(tmp1090, $Pclutch2$Psa, (-$Pclutch2$Ptau0_max), 26, Less);
  RELATIONHYSTERESIS(tmp1091, $Pclutch2$Psa, (-$Pclutch2$Ptau0), 27, Less);
  RELATIONHYSTERESIS(tmp1093, $Pclutch2$Pw_rel, (-$Pclutch2$Pw_small), 28, Less);
  RELATIONHYSTERESIS(tmp1094, $Pclutch2$Pw_rel, 0.0, 29, Less);
  $Pclutch2$PstartBackward = (((((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) 0) && (tmp1090 || ($P$PRE$Pclutch2$PstartBackward && tmp1091))) || (((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) 1) && tmp1093)) || tmp1094);
  TRACE_POP
}
/*
 equation index: 53
 type: SIMPLE_ASSIGN
 clutch3._locked = not clutch3.free and not ($PRE.clutch3.mode == 1 or clutch3.startForward or $PRE.clutch3.mode == -1 or clutch3.startBackward)
 */
void CoupledClutches_eqFunction_53(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,53};
  $Pclutch3$Plocked = ((!$Pclutch3$Pfree) && (!(((((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) 1) || $Pclutch3$PstartForward) || ((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) -1)) || $Pclutch3$PstartBackward)));
  TRACE_POP
}
/*
 equation index: 54
 type: SIMPLE_ASSIGN
 clutch2._locked = not clutch2.free and not ($PRE.clutch2.mode == 1 or clutch2.startForward or $PRE.clutch2.mode == -1 or clutch2.startBackward)
 */
void CoupledClutches_eqFunction_54(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,54};
  $Pclutch2$Plocked = ((!$Pclutch2$Pfree) && (!(((((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) 1) || $Pclutch2$PstartForward) || ((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) -1)) || $Pclutch2$PstartBackward)));
  TRACE_POP
}
/*
 equation index: 55
 type: SIMPLE_ASSIGN
 clutch3._tau = if clutch3.locked then clutch3.sa else if clutch3.free then 0.0 else clutch3.cgeo * clutch3.fn * (if clutch3.startForward then Modelica.Math.tempInterpol1(clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2) else if clutch3.startBackward then -Modelica.Math.tempInterpol1(-clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2) else if $PRE.clutch3.mode == 1 then Modelica.Math.tempInterpol1(clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2) else -Modelica.Math.tempInterpol1(-clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2))
 */
void CoupledClutches_eqFunction_55(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,55};
  real_array tmp1099;
  real_array tmp1100;
  real_array tmp1102;
  real_array tmp1103;
  modelica_boolean tmp1104;
  modelica_real tmp1105;
  modelica_boolean tmp1106;
  modelica_real tmp1107;
  modelica_boolean tmp1108;
  modelica_real tmp1109;
  modelica_boolean tmp1110;
  modelica_real tmp1111;
  modelica_boolean tmp1112;
  modelica_real tmp1113;
  tmp1112 = (modelica_boolean)$Pclutch3$Plocked;
  if(tmp1112)
  {
    tmp1113 = $Pclutch3$Psa;
  }
  else
  {
    tmp1110 = (modelica_boolean)$Pclutch3$Pfree;
    if(tmp1110)
    {
      tmp1111 = 0.0;
    }
    else
    {
      tmp1108 = (modelica_boolean)$Pclutch3$PstartForward;
      if(tmp1108)
      {
        /* -- start: matrix[1,2] -- */
        alloc_real_array(&tmp1099, 2, 1, 2);
        put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1099);
        put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1099);
        /* -- end: matrix[1,2] -- */
        tmp1109 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch3$Pw_rel, tmp1099, (modelica_integer) 2);
      }
      else
      {
        tmp1106 = (modelica_boolean)$Pclutch3$PstartBackward;
        if(tmp1106)
        {
          /* -- start: matrix[1,2] -- */
          alloc_real_array(&tmp1100, 2, 1, 2);
          put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1100);
          put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1100);
          /* -- end: matrix[1,2] -- */
          tmp1107 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch3$Pw_rel), tmp1100, (modelica_integer) 2));
        }
        else
        {
          tmp1104 = (modelica_boolean)((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) 1);
          if(tmp1104)
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1102, 2, 1, 2);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1102);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1102);
            /* -- end: matrix[1,2] -- */
            tmp1105 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch3$Pw_rel, tmp1102, (modelica_integer) 2);
          }
          else
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1103, 2, 1, 2);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1103);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1103);
            /* -- end: matrix[1,2] -- */
            tmp1105 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch3$Pw_rel), tmp1103, (modelica_integer) 2));
          }
          tmp1107 = tmp1105;
        }
        tmp1109 = tmp1107;
      }
      tmp1111 = ($Pclutch3$Pcgeo * ($Pclutch3$Pfn * tmp1109));
    }
    tmp1113 = tmp1111;
  }
  $Pclutch3$Ptau = tmp1113;
  TRACE_POP
}
/*
 equation index: 56
 type: SIMPLE_ASSIGN
 clutch2._tau = if clutch2.locked then clutch2.sa else if clutch2.free then 0.0 else clutch2.cgeo * clutch2.fn * (if clutch2.startForward then Modelica.Math.tempInterpol1(clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2) else if clutch2.startBackward then -Modelica.Math.tempInterpol1(-clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2) else if $PRE.clutch2.mode == 1 then Modelica.Math.tempInterpol1(clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2) else -Modelica.Math.tempInterpol1(-clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2))
 */
void CoupledClutches_eqFunction_56(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,56};
  real_array tmp1114;
  real_array tmp1115;
  real_array tmp1117;
  real_array tmp1118;
  modelica_boolean tmp1119;
  modelica_real tmp1120;
  modelica_boolean tmp1121;
  modelica_real tmp1122;
  modelica_boolean tmp1123;
  modelica_real tmp1124;
  modelica_boolean tmp1125;
  modelica_real tmp1126;
  modelica_boolean tmp1127;
  modelica_real tmp1128;
  tmp1127 = (modelica_boolean)$Pclutch2$Plocked;
  if(tmp1127)
  {
    tmp1128 = $Pclutch2$Psa;
  }
  else
  {
    tmp1125 = (modelica_boolean)$Pclutch2$Pfree;
    if(tmp1125)
    {
      tmp1126 = 0.0;
    }
    else
    {
      tmp1123 = (modelica_boolean)$Pclutch2$PstartForward;
      if(tmp1123)
      {
        /* -- start: matrix[1,2] -- */
        alloc_real_array(&tmp1114, 2, 1, 2);
        put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1114);
        put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1114);
        /* -- end: matrix[1,2] -- */
        tmp1124 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch2$Pw_rel, tmp1114, (modelica_integer) 2);
      }
      else
      {
        tmp1121 = (modelica_boolean)$Pclutch2$PstartBackward;
        if(tmp1121)
        {
          /* -- start: matrix[1,2] -- */
          alloc_real_array(&tmp1115, 2, 1, 2);
          put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1115);
          put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1115);
          /* -- end: matrix[1,2] -- */
          tmp1122 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch2$Pw_rel), tmp1115, (modelica_integer) 2));
        }
        else
        {
          tmp1119 = (modelica_boolean)((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) 1);
          if(tmp1119)
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1117, 2, 1, 2);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1117);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1117);
            /* -- end: matrix[1,2] -- */
            tmp1120 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch2$Pw_rel, tmp1117, (modelica_integer) 2);
          }
          else
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1118, 2, 1, 2);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1118);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1118);
            /* -- end: matrix[1,2] -- */
            tmp1120 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch2$Pw_rel), tmp1118, (modelica_integer) 2));
          }
          tmp1122 = tmp1120;
        }
        tmp1124 = tmp1122;
      }
      tmp1126 = ($Pclutch2$Pcgeo * ($Pclutch2$Pfn * tmp1124));
    }
    tmp1128 = tmp1126;
  }
  $Pclutch2$Ptau = tmp1128;
  TRACE_POP
}
/*
 equation index: 57
 type: SIMPLE_ASSIGN
 clutch2._a_relfric = if clutch2.locked then 0.0 else if clutch2.free then clutch2.sa else if clutch2.startForward then clutch2.sa - clutch2.tau0_max else if clutch2.startBackward then clutch2.sa + clutch2.tau0_max else if $PRE.clutch2.mode == 1 then clutch2.sa - clutch2.tau0_max else clutch2.sa + clutch2.tau0_max
 */
void CoupledClutches_eqFunction_57(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,57};
  $Pclutch2$Pa_relfric = ($Pclutch2$Plocked?0.0:($Pclutch2$Pfree?$Pclutch2$Psa:($Pclutch2$PstartForward?($Pclutch2$Psa - $Pclutch2$Ptau0_max):($Pclutch2$PstartBackward?($Pclutch2$Psa + $Pclutch2$Ptau0_max):(((modelica_integer)$P$PRE$Pclutch2$Pmode == (modelica_integer) 1)?($Pclutch2$Psa - $Pclutch2$Ptau0_max):($Pclutch2$Psa + $Pclutch2$Ptau0_max))))));
  TRACE_POP
}
/*
 equation index: 58
 type: SIMPLE_ASSIGN
 clutch3._a_relfric = if clutch3.locked then 0.0 else if clutch3.free then clutch3.sa else if clutch3.startForward then clutch3.sa - clutch3.tau0_max else if clutch3.startBackward then clutch3.sa + clutch3.tau0_max else if $PRE.clutch3.mode == 1 then clutch3.sa - clutch3.tau0_max else clutch3.sa + clutch3.tau0_max
 */
void CoupledClutches_eqFunction_58(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,58};
  $Pclutch3$Pa_relfric = ($Pclutch3$Plocked?0.0:($Pclutch3$Pfree?$Pclutch3$Psa:($Pclutch3$PstartForward?($Pclutch3$Psa - $Pclutch3$Ptau0_max):($Pclutch3$PstartBackward?($Pclutch3$Psa + $Pclutch3$Ptau0_max):(((modelica_integer)$P$PRE$Pclutch3$Pmode == (modelica_integer) 1)?($Pclutch3$Psa - $Pclutch3$Ptau0_max):($Pclutch3$Psa + $Pclutch3$Ptau0_max))))));
  TRACE_POP
}
/*
 equation index: 59
 type: SIMPLE_ASSIGN
 clutch1._startForward = $PRE.clutch1.mode == 0 and (clutch1.sa > clutch1.tau0_max or $PRE.clutch1.startForward and clutch1.sa > clutch1.tau0) or $PRE.clutch1.mode == -1 and clutch1.w_rel > clutch1.w_small or clutch1.w_rel > 0.0
 */
void CoupledClutches_eqFunction_59(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,59};
  modelica_boolean tmp1132;
  modelica_boolean tmp1133;
  modelica_boolean tmp1135;
  modelica_boolean tmp1136;
  RELATIONHYSTERESIS(tmp1132, $Pclutch1$Psa, $Pclutch1$Ptau0_max, 10, Greater);
  RELATIONHYSTERESIS(tmp1133, $Pclutch1$Psa, $Pclutch1$Ptau0, 11, Greater);
  RELATIONHYSTERESIS(tmp1135, $Pclutch1$Pw_rel, $Pclutch1$Pw_small, 12, Greater);
  RELATIONHYSTERESIS(tmp1136, $Pclutch1$Pw_rel, 0.0, 13, Greater);
  $Pclutch1$PstartForward = (((((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) 0) && (tmp1132 || ($P$PRE$Pclutch1$PstartForward && tmp1133))) || (((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) -1) && tmp1135)) || tmp1136);
  TRACE_POP
}
/*
 equation index: 60
 type: SIMPLE_ASSIGN
 clutch1._startBackward = $PRE.clutch1.mode == 0 and (clutch1.sa < (-clutch1.tau0_max) or $PRE.clutch1.startBackward and clutch1.sa < (-clutch1.tau0)) or $PRE.clutch1.mode == 1 and clutch1.w_rel < (-clutch1.w_small) or clutch1.w_rel < 0.0
 */
void CoupledClutches_eqFunction_60(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,60};
  modelica_boolean tmp1138;
  modelica_boolean tmp1139;
  modelica_boolean tmp1141;
  modelica_boolean tmp1142;
  RELATIONHYSTERESIS(tmp1138, $Pclutch1$Psa, (-$Pclutch1$Ptau0_max), 14, Less);
  RELATIONHYSTERESIS(tmp1139, $Pclutch1$Psa, (-$Pclutch1$Ptau0), 15, Less);
  RELATIONHYSTERESIS(tmp1141, $Pclutch1$Pw_rel, (-$Pclutch1$Pw_small), 16, Less);
  RELATIONHYSTERESIS(tmp1142, $Pclutch1$Pw_rel, 0.0, 17, Less);
  $Pclutch1$PstartBackward = (((((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) 0) && (tmp1138 || ($P$PRE$Pclutch1$PstartBackward && tmp1139))) || (((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) 1) && tmp1141)) || tmp1142);
  TRACE_POP
}
/*
 equation index: 61
 type: SIMPLE_ASSIGN
 clutch1._locked = not clutch1.free and not ($PRE.clutch1.mode == 1 or clutch1.startForward or $PRE.clutch1.mode == -1 or clutch1.startBackward)
 */
void CoupledClutches_eqFunction_61(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,61};
  $Pclutch1$Plocked = ((!$Pclutch1$Pfree) && (!(((((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) 1) || $Pclutch1$PstartForward) || ((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) -1)) || $Pclutch1$PstartBackward)));
  TRACE_POP
}
/*
 equation index: 62
 type: SIMPLE_ASSIGN
 clutch1._tau = if clutch1.locked then clutch1.sa else if clutch1.free then 0.0 else clutch1.cgeo * clutch1.fn * (if clutch1.startForward then Modelica.Math.tempInterpol1(clutch1.w_rel, {{clutch1.mue_pos[1,1], clutch1.mue_pos[1,2]}}, 2) else if clutch1.startBackward then -Modelica.Math.tempInterpol1(-clutch1.w_rel, {{clutch1.mue_pos[1,1], clutch1.mue_pos[1,2]}}, 2) else if $PRE.clutch1.mode == 1 then Modelica.Math.tempInterpol1(clutch1.w_rel, {{clutch1.mue_pos[1,1], clutch1.mue_pos[1,2]}}, 2) else -Modelica.Math.tempInterpol1(-clutch1.w_rel, {{clutch1.mue_pos[1,1], clutch1.mue_pos[1,2]}}, 2))
 */
void CoupledClutches_eqFunction_62(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,62};
  real_array tmp1145;
  real_array tmp1146;
  real_array tmp1148;
  real_array tmp1149;
  modelica_boolean tmp1150;
  modelica_real tmp1151;
  modelica_boolean tmp1152;
  modelica_real tmp1153;
  modelica_boolean tmp1154;
  modelica_real tmp1155;
  modelica_boolean tmp1156;
  modelica_real tmp1157;
  modelica_boolean tmp1158;
  modelica_real tmp1159;
  tmp1158 = (modelica_boolean)$Pclutch1$Plocked;
  if(tmp1158)
  {
    tmp1159 = $Pclutch1$Psa;
  }
  else
  {
    tmp1156 = (modelica_boolean)$Pclutch1$Pfree;
    if(tmp1156)
    {
      tmp1157 = 0.0;
    }
    else
    {
      tmp1154 = (modelica_boolean)$Pclutch1$PstartForward;
      if(tmp1154)
      {
        /* -- start: matrix[1,2] -- */
        alloc_real_array(&tmp1145, 2, 1, 2);
        put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1145);
        put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1145);
        /* -- end: matrix[1,2] -- */
        tmp1155 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch1$Pw_rel, tmp1145, (modelica_integer) 2);
      }
      else
      {
        tmp1152 = (modelica_boolean)$Pclutch1$PstartBackward;
        if(tmp1152)
        {
          /* -- start: matrix[1,2] -- */
          alloc_real_array(&tmp1146, 2, 1, 2);
          put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1146);
          put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1146);
          /* -- end: matrix[1,2] -- */
          tmp1153 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch1$Pw_rel), tmp1146, (modelica_integer) 2));
        }
        else
        {
          tmp1150 = (modelica_boolean)((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) 1);
          if(tmp1150)
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1148, 2, 1, 2);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1148);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1148);
            /* -- end: matrix[1,2] -- */
            tmp1151 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch1$Pw_rel, tmp1148, (modelica_integer) 2);
          }
          else
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1149, 2, 1, 2);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1149);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1149);
            /* -- end: matrix[1,2] -- */
            tmp1151 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch1$Pw_rel), tmp1149, (modelica_integer) 2));
          }
          tmp1153 = tmp1151;
        }
        tmp1155 = tmp1153;
      }
      tmp1157 = ($Pclutch1$Pcgeo * ($Pclutch1$Pfn * tmp1155));
    }
    tmp1159 = tmp1157;
  }
  $Pclutch1$Ptau = tmp1159;
  TRACE_POP
}
/*
 equation index: 63
 type: SIMPLE_ASSIGN
 clutch1._a_relfric = if clutch1.locked then 0.0 else if clutch1.free then clutch1.sa else if clutch1.startForward then clutch1.sa - clutch1.tau0_max else if clutch1.startBackward then clutch1.sa + clutch1.tau0_max else if $PRE.clutch1.mode == 1 then clutch1.sa - clutch1.tau0_max else clutch1.sa + clutch1.tau0_max
 */
void CoupledClutches_eqFunction_63(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,63};
  $Pclutch1$Pa_relfric = ($Pclutch1$Plocked?0.0:($Pclutch1$Pfree?$Pclutch1$Psa:($Pclutch1$PstartForward?($Pclutch1$Psa - $Pclutch1$Ptau0_max):($Pclutch1$PstartBackward?($Pclutch1$Psa + $Pclutch1$Ptau0_max):(((modelica_integer)$P$PRE$Pclutch1$Pmode == (modelica_integer) 1)?($Pclutch1$Psa - $Pclutch1$Ptau0_max):($Pclutch1$Psa + $Pclutch1$Ptau0_max))))));
  TRACE_POP
}
/*
 equation index: 64
 type: SIMPLE_ASSIGN
 J3._a = clutch2.a_relfric + J2.a
 */
void CoupledClutches_eqFunction_64(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,64};
  $PJ3$Pa = ($Pclutch2$Pa_relfric + $PJ2$Pa);
  TRACE_POP
}
/*
 equation index: 65
 type: SIMPLE_ASSIGN
 J1._a = J2.a - clutch1.a_relfric
 */
void CoupledClutches_eqFunction_65(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,65};
  $PJ1$Pa = ($PJ2$Pa - $Pclutch1$Pa_relfric);
  TRACE_POP
}
/*
 equation index: 66
 type: SIMPLE_ASSIGN
 J4._a = clutch3.a_relfric + J3.a
 */
void CoupledClutches_eqFunction_66(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,66};
  $PJ4$Pa = ($Pclutch3$Pa_relfric + $PJ3$Pa);
  TRACE_POP
}
void initializeStaticNLSData71(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PJ2$Pa */
  nlsData->nominal[i] = $P$ATTRIBUTE$PJ2$Pa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PJ2$Pa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PJ2$Pa.max;
  /* static nls data for $Pclutch2$Psa */
  nlsData->nominal[i] = $P$ATTRIBUTE$Pclutch2$Psa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$Pclutch2$Psa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$Pclutch2$Psa.max;
  /* static nls data for $Pclutch3$Psa */
  nlsData->nominal[i] = $P$ATTRIBUTE$Pclutch3$Psa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$Pclutch3$Psa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$Pclutch3$Psa.max;
  /* static nls data for $Pclutch1$Psa */
  nlsData->nominal[i] = $P$ATTRIBUTE$Pclutch1$Psa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$Pclutch1$Psa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$Pclutch1$Psa.max;
}

void residualFunc71(void* dataIn, const double* xloc, double* res, const int* iflag)
{
  DATA* data = (DATA*) dataIn;
  const int equationIndexes[2] = {1,71};
  $PJ2$Pa = xloc[0];
  $Pclutch2$Psa = xloc[1];
  $Pclutch3$Psa = xloc[2];
  $Pclutch1$Psa = xloc[3];
  CoupledClutches_eqFunction_49(data);

  CoupledClutches_eqFunction_50(data);

  CoupledClutches_eqFunction_51(data);

  CoupledClutches_eqFunction_52(data);

  CoupledClutches_eqFunction_53(data);

  CoupledClutches_eqFunction_54(data);

  CoupledClutches_eqFunction_55(data);

  CoupledClutches_eqFunction_56(data);

  CoupledClutches_eqFunction_57(data);

  CoupledClutches_eqFunction_58(data);

  CoupledClutches_eqFunction_59(data);

  CoupledClutches_eqFunction_60(data);

  CoupledClutches_eqFunction_61(data);

  CoupledClutches_eqFunction_62(data);

  CoupledClutches_eqFunction_63(data);

  CoupledClutches_eqFunction_64(data);

  CoupledClutches_eqFunction_65(data);

  CoupledClutches_eqFunction_66(data);
  res[0] = ((-$Pclutch3$Ptau) - ($PJ4$PJ * $PJ4$Pa));

  res[1] = ($Pclutch1$Ptau + ($Psin1$Py - ($PJ1$PJ * $PJ1$Pa)));

  res[2] = ($Pclutch2$Ptau + ((-$Pclutch1$Ptau) - ($PJ2$PJ * $PJ2$Pa)));

  res[3] = ($Pclutch3$Ptau + ((-$Pclutch2$Ptau) - ($PJ3$PJ * $PJ3$Pa)));
}

/*
 equation index: 101
 type: SIMPLE_ASSIGN
 clutch3._startBackward = pre(clutch3.mode) == 0 and (clutch3.sa < (-clutch3.tau0_max) or pre(clutch3.startBackward) and clutch3.sa < (-clutch3.tau0)) or pre(clutch3.mode) == 1 and clutch3.w_rel < (-clutch3.w_small) or initial() and clutch3.w_rel < 0.0
 */
void CoupledClutches_eqFunction_101(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,101};
  modelica_boolean tmp1162;
  modelica_boolean tmp1163;
  modelica_boolean tmp1165;
  modelica_boolean tmp1166;
  RELATIONHYSTERESIS(tmp1162, $Pclutch3$Psa, (-$Pclutch3$Ptau0_max), 22, Less);
  RELATIONHYSTERESIS(tmp1163, $Pclutch3$Psa, (-$Pclutch3$Ptau0), 23, Less);
  RELATIONHYSTERESIS(tmp1165, $Pclutch3$Pw_rel, (-$Pclutch3$Pw_small), 24, Less);
  RELATIONHYSTERESIS(tmp1166, $Pclutch3$Pw_rel, 0.0, 25, Less);
  $Pclutch3$PstartBackward = (((($P$PRE$Pclutch3$Pmode == (modelica_integer) 0) && (tmp1162 || ($P$PRE$Pclutch3$PstartBackward && tmp1163))) || (($P$PRE$Pclutch3$Pmode == (modelica_integer) 1) && tmp1165)) || (initial() && tmp1166));
  TRACE_POP
}
/*
 equation index: 102
 type: SIMPLE_ASSIGN
 clutch2._startBackward = pre(clutch2.mode) == 0 and (clutch2.sa < (-clutch2.tau0_max) or pre(clutch2.startBackward) and clutch2.sa < (-clutch2.tau0)) or pre(clutch2.mode) == 1 and clutch2.w_rel < (-clutch2.w_small) or initial() and clutch2.w_rel < 0.0
 */
void CoupledClutches_eqFunction_102(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,102};
  modelica_boolean tmp1168;
  modelica_boolean tmp1169;
  modelica_boolean tmp1171;
  modelica_boolean tmp1172;
  RELATIONHYSTERESIS(tmp1168, $Pclutch2$Psa, (-$Pclutch2$Ptau0_max), 26, Less);
  RELATIONHYSTERESIS(tmp1169, $Pclutch2$Psa, (-$Pclutch2$Ptau0), 27, Less);
  RELATIONHYSTERESIS(tmp1171, $Pclutch2$Pw_rel, (-$Pclutch2$Pw_small), 28, Less);
  RELATIONHYSTERESIS(tmp1172, $Pclutch2$Pw_rel, 0.0, 29, Less);
  $Pclutch2$PstartBackward = (((($P$PRE$Pclutch2$Pmode == (modelica_integer) 0) && (tmp1168 || ($P$PRE$Pclutch2$PstartBackward && tmp1169))) || (($P$PRE$Pclutch2$Pmode == (modelica_integer) 1) && tmp1171)) || (initial() && tmp1172));
  TRACE_POP
}
/*
 equation index: 103
 type: SIMPLE_ASSIGN
 clutch2._startForward = pre(clutch2.mode) == 0 and (clutch2.sa > clutch2.tau0_max or pre(clutch2.startForward) and clutch2.sa > clutch2.tau0) or pre(clutch2.mode) == -1 and clutch2.w_rel > clutch2.w_small or initial() and clutch2.w_rel > 0.0
 */
void CoupledClutches_eqFunction_103(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,103};
  modelica_boolean tmp1174;
  modelica_boolean tmp1175;
  modelica_boolean tmp1177;
  modelica_boolean tmp1178;
  RELATIONHYSTERESIS(tmp1174, $Pclutch2$Psa, $Pclutch2$Ptau0_max, 6, Greater);
  RELATIONHYSTERESIS(tmp1175, $Pclutch2$Psa, $Pclutch2$Ptau0, 7, Greater);
  RELATIONHYSTERESIS(tmp1177, $Pclutch2$Pw_rel, $Pclutch2$Pw_small, 8, Greater);
  RELATIONHYSTERESIS(tmp1178, $Pclutch2$Pw_rel, 0.0, 9, Greater);
  $Pclutch2$PstartForward = (((($P$PRE$Pclutch2$Pmode == (modelica_integer) 0) && (tmp1174 || ($P$PRE$Pclutch2$PstartForward && tmp1175))) || (($P$PRE$Pclutch2$Pmode == (modelica_integer) -1) && tmp1177)) || (initial() && tmp1178));
  TRACE_POP
}
/*
 equation index: 104
 type: SIMPLE_ASSIGN
 clutch3._startForward = pre(clutch3.mode) == 0 and (clutch3.sa > clutch3.tau0_max or pre(clutch3.startForward) and clutch3.sa > clutch3.tau0) or pre(clutch3.mode) == -1 and clutch3.w_rel > clutch3.w_small or initial() and clutch3.w_rel > 0.0
 */
void CoupledClutches_eqFunction_104(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,104};
  modelica_boolean tmp1180;
  modelica_boolean tmp1181;
  modelica_boolean tmp1183;
  modelica_boolean tmp1184;
  RELATIONHYSTERESIS(tmp1180, $Pclutch3$Psa, $Pclutch3$Ptau0_max, 18, Greater);
  RELATIONHYSTERESIS(tmp1181, $Pclutch3$Psa, $Pclutch3$Ptau0, 19, Greater);
  RELATIONHYSTERESIS(tmp1183, $Pclutch3$Pw_rel, $Pclutch3$Pw_small, 20, Greater);
  RELATIONHYSTERESIS(tmp1184, $Pclutch3$Pw_rel, 0.0, 21, Greater);
  $Pclutch3$PstartForward = (((($P$PRE$Pclutch3$Pmode == (modelica_integer) 0) && (tmp1180 || ($P$PRE$Pclutch3$PstartForward && tmp1181))) || (($P$PRE$Pclutch3$Pmode == (modelica_integer) -1) && tmp1183)) || (initial() && tmp1184));
  TRACE_POP
}
/*
 equation index: 105
 type: SIMPLE_ASSIGN
 clutch2._locked = not clutch2.free and not (pre(clutch2.mode) == 1 or clutch2.startForward or pre(clutch2.mode) == -1 or clutch2.startBackward)
 */
void CoupledClutches_eqFunction_105(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,105};
  $Pclutch2$Plocked = ((!$Pclutch2$Pfree) && (!(((($P$PRE$Pclutch2$Pmode == (modelica_integer) 1) || $Pclutch2$PstartForward) || ($P$PRE$Pclutch2$Pmode == (modelica_integer) -1)) || $Pclutch2$PstartBackward)));
  TRACE_POP
}
/*
 equation index: 106
 type: SIMPLE_ASSIGN
 clutch3._locked = not clutch3.free and not (pre(clutch3.mode) == 1 or clutch3.startForward or pre(clutch3.mode) == -1 or clutch3.startBackward)
 */
void CoupledClutches_eqFunction_106(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,106};
  $Pclutch3$Plocked = ((!$Pclutch3$Pfree) && (!(((($P$PRE$Pclutch3$Pmode == (modelica_integer) 1) || $Pclutch3$PstartForward) || ($P$PRE$Pclutch3$Pmode == (modelica_integer) -1)) || $Pclutch3$PstartBackward)));
  TRACE_POP
}
/*
 equation index: 107
 type: SIMPLE_ASSIGN
 clutch2._tau = if clutch2.locked then clutch2.sa else if clutch2.free then 0.0 else clutch2.cgeo * clutch2.fn * (if clutch2.startForward then Modelica.Math.tempInterpol1(clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2) else if clutch2.startBackward then -Modelica.Math.tempInterpol1(-clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2) else if pre(clutch2.mode) == 1 then Modelica.Math.tempInterpol1(clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2) else -Modelica.Math.tempInterpol1(-clutch2.w_rel, {{clutch2.mue_pos[1,1], clutch2.mue_pos[1,2]}}, 2))
 */
void CoupledClutches_eqFunction_107(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,107};
  real_array tmp1189;
  real_array tmp1190;
  real_array tmp1192;
  real_array tmp1193;
  modelica_boolean tmp1194;
  modelica_real tmp1195;
  modelica_boolean tmp1196;
  modelica_real tmp1197;
  modelica_boolean tmp1198;
  modelica_real tmp1199;
  modelica_boolean tmp1200;
  modelica_real tmp1201;
  modelica_boolean tmp1202;
  modelica_real tmp1203;
  tmp1202 = (modelica_boolean)$Pclutch2$Plocked;
  if(tmp1202)
  {
    tmp1203 = $Pclutch2$Psa;
  }
  else
  {
    tmp1200 = (modelica_boolean)$Pclutch2$Pfree;
    if(tmp1200)
    {
      tmp1201 = 0.0;
    }
    else
    {
      tmp1198 = (modelica_boolean)$Pclutch2$PstartForward;
      if(tmp1198)
      {
        /* -- start: matrix[1,2] -- */
        alloc_real_array(&tmp1189, 2, 1, 2);
        put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1189);
        put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1189);
        /* -- end: matrix[1,2] -- */
        tmp1199 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch2$Pw_rel, tmp1189, (modelica_integer) 2);
      }
      else
      {
        tmp1196 = (modelica_boolean)$Pclutch2$PstartBackward;
        if(tmp1196)
        {
          /* -- start: matrix[1,2] -- */
          alloc_real_array(&tmp1190, 2, 1, 2);
          put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1190);
          put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1190);
          /* -- end: matrix[1,2] -- */
          tmp1197 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch2$Pw_rel), tmp1190, (modelica_integer) 2));
        }
        else
        {
          tmp1194 = (modelica_boolean)($P$PRE$Pclutch2$Pmode == (modelica_integer) 1);
          if(tmp1194)
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1192, 2, 1, 2);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1192);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1192);
            /* -- end: matrix[1,2] -- */
            tmp1195 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch2$Pw_rel, tmp1192, (modelica_integer) 2);
          }
          else
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1193, 2, 1, 2);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1193);
            put_real_matrix_element($Pclutch2$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1193);
            /* -- end: matrix[1,2] -- */
            tmp1195 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch2$Pw_rel), tmp1193, (modelica_integer) 2));
          }
          tmp1197 = tmp1195;
        }
        tmp1199 = tmp1197;
      }
      tmp1201 = ($Pclutch2$Pcgeo * ($Pclutch2$Pfn * tmp1199));
    }
    tmp1203 = tmp1201;
  }
  $Pclutch2$Ptau = tmp1203;
  TRACE_POP
}
/*
 equation index: 108
 type: SIMPLE_ASSIGN
 clutch3._a_relfric = if clutch3.locked then 0.0 else if clutch3.free then clutch3.sa else if clutch3.startForward then clutch3.sa - clutch3.tau0_max else if clutch3.startBackward then clutch3.sa + clutch3.tau0_max else if pre(clutch3.mode) == 1 then clutch3.sa - clutch3.tau0_max else clutch3.sa + clutch3.tau0_max
 */
void CoupledClutches_eqFunction_108(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,108};
  $Pclutch3$Pa_relfric = ($Pclutch3$Plocked?0.0:($Pclutch3$Pfree?$Pclutch3$Psa:($Pclutch3$PstartForward?($Pclutch3$Psa - $Pclutch3$Ptau0_max):($Pclutch3$PstartBackward?($Pclutch3$Psa + $Pclutch3$Ptau0_max):(($P$PRE$Pclutch3$Pmode == (modelica_integer) 1)?($Pclutch3$Psa - $Pclutch3$Ptau0_max):($Pclutch3$Psa + $Pclutch3$Ptau0_max))))));
  TRACE_POP
}
/*
 equation index: 109
 type: SIMPLE_ASSIGN
 clutch3._tau = if clutch3.locked then clutch3.sa else if clutch3.free then 0.0 else clutch3.cgeo * clutch3.fn * (if clutch3.startForward then Modelica.Math.tempInterpol1(clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2) else if clutch3.startBackward then -Modelica.Math.tempInterpol1(-clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2) else if pre(clutch3.mode) == 1 then Modelica.Math.tempInterpol1(clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2) else -Modelica.Math.tempInterpol1(-clutch3.w_rel, {{clutch3.mue_pos[1,1], clutch3.mue_pos[1,2]}}, 2))
 */
void CoupledClutches_eqFunction_109(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,109};
  real_array tmp1205;
  real_array tmp1206;
  real_array tmp1208;
  real_array tmp1209;
  modelica_boolean tmp1210;
  modelica_real tmp1211;
  modelica_boolean tmp1212;
  modelica_real tmp1213;
  modelica_boolean tmp1214;
  modelica_real tmp1215;
  modelica_boolean tmp1216;
  modelica_real tmp1217;
  modelica_boolean tmp1218;
  modelica_real tmp1219;
  tmp1218 = (modelica_boolean)$Pclutch3$Plocked;
  if(tmp1218)
  {
    tmp1219 = $Pclutch3$Psa;
  }
  else
  {
    tmp1216 = (modelica_boolean)$Pclutch3$Pfree;
    if(tmp1216)
    {
      tmp1217 = 0.0;
    }
    else
    {
      tmp1214 = (modelica_boolean)$Pclutch3$PstartForward;
      if(tmp1214)
      {
        /* -- start: matrix[1,2] -- */
        alloc_real_array(&tmp1205, 2, 1, 2);
        put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1205);
        put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1205);
        /* -- end: matrix[1,2] -- */
        tmp1215 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch3$Pw_rel, tmp1205, (modelica_integer) 2);
      }
      else
      {
        tmp1212 = (modelica_boolean)$Pclutch3$PstartBackward;
        if(tmp1212)
        {
          /* -- start: matrix[1,2] -- */
          alloc_real_array(&tmp1206, 2, 1, 2);
          put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1206);
          put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1206);
          /* -- end: matrix[1,2] -- */
          tmp1213 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch3$Pw_rel), tmp1206, (modelica_integer) 2));
        }
        else
        {
          tmp1210 = (modelica_boolean)($P$PRE$Pclutch3$Pmode == (modelica_integer) 1);
          if(tmp1210)
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1208, 2, 1, 2);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1208);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1208);
            /* -- end: matrix[1,2] -- */
            tmp1211 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch3$Pw_rel, tmp1208, (modelica_integer) 2);
          }
          else
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1209, 2, 1, 2);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1209);
            put_real_matrix_element($Pclutch3$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1209);
            /* -- end: matrix[1,2] -- */
            tmp1211 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch3$Pw_rel), tmp1209, (modelica_integer) 2));
          }
          tmp1213 = tmp1211;
        }
        tmp1215 = tmp1213;
      }
      tmp1217 = ($Pclutch3$Pcgeo * ($Pclutch3$Pfn * tmp1215));
    }
    tmp1219 = tmp1217;
  }
  $Pclutch3$Ptau = tmp1219;
  TRACE_POP
}
/*
 equation index: 110
 type: SIMPLE_ASSIGN
 clutch2._a_relfric = if clutch2.locked then 0.0 else if clutch2.free then clutch2.sa else if clutch2.startForward then clutch2.sa - clutch2.tau0_max else if clutch2.startBackward then clutch2.sa + clutch2.tau0_max else if pre(clutch2.mode) == 1 then clutch2.sa - clutch2.tau0_max else clutch2.sa + clutch2.tau0_max
 */
void CoupledClutches_eqFunction_110(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,110};
  $Pclutch2$Pa_relfric = ($Pclutch2$Plocked?0.0:($Pclutch2$Pfree?$Pclutch2$Psa:($Pclutch2$PstartForward?($Pclutch2$Psa - $Pclutch2$Ptau0_max):($Pclutch2$PstartBackward?($Pclutch2$Psa + $Pclutch2$Ptau0_max):(($P$PRE$Pclutch2$Pmode == (modelica_integer) 1)?($Pclutch2$Psa - $Pclutch2$Ptau0_max):($Pclutch2$Psa + $Pclutch2$Ptau0_max))))));
  TRACE_POP
}
/*
 equation index: 111
 type: SIMPLE_ASSIGN
 J4._a = DIVISION(-clutch3.tau, J4.J)
 */
void CoupledClutches_eqFunction_111(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,111};
  $PJ4$Pa = DIVISION_SIM((-$Pclutch3$Ptau),$PJ4$PJ,"J4.J",equationIndexes);
  TRACE_POP
}
/*
 equation index: 112
 type: SIMPLE_ASSIGN
 J3._a = DIVISION(clutch3.tau - clutch2.tau, J3.J)
 */
void CoupledClutches_eqFunction_112(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,112};
  $PJ3$Pa = DIVISION_SIM(($Pclutch3$Ptau - $Pclutch2$Ptau),$PJ3$PJ,"J3.J",equationIndexes);
  TRACE_POP
}
/*
 equation index: 113
 type: SIMPLE_ASSIGN
 clutch1._startBackward = pre(clutch1.mode) == 0 and (clutch1.sa < (-clutch1.tau0_max) or pre(clutch1.startBackward) and clutch1.sa < (-clutch1.tau0)) or pre(clutch1.mode) == 1 and clutch1.w_rel < (-clutch1.w_small) or initial() and clutch1.w_rel < 0.0
 */
void CoupledClutches_eqFunction_113(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,113};
  modelica_boolean tmp1222;
  modelica_boolean tmp1223;
  modelica_boolean tmp1225;
  modelica_boolean tmp1226;
  RELATIONHYSTERESIS(tmp1222, $Pclutch1$Psa, (-$Pclutch1$Ptau0_max), 14, Less);
  RELATIONHYSTERESIS(tmp1223, $Pclutch1$Psa, (-$Pclutch1$Ptau0), 15, Less);
  RELATIONHYSTERESIS(tmp1225, $Pclutch1$Pw_rel, (-$Pclutch1$Pw_small), 16, Less);
  RELATIONHYSTERESIS(tmp1226, $Pclutch1$Pw_rel, 0.0, 17, Less);
  $Pclutch1$PstartBackward = (((($P$PRE$Pclutch1$Pmode == (modelica_integer) 0) && (tmp1222 || ($P$PRE$Pclutch1$PstartBackward && tmp1223))) || (($P$PRE$Pclutch1$Pmode == (modelica_integer) 1) && tmp1225)) || (initial() && tmp1226));
  TRACE_POP
}
/*
 equation index: 114
 type: SIMPLE_ASSIGN
 J2._a = J3.a - clutch2.a_relfric
 */
void CoupledClutches_eqFunction_114(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,114};
  $PJ2$Pa = ($PJ3$Pa - $Pclutch2$Pa_relfric);
  TRACE_POP
}
/*
 equation index: 115
 type: SIMPLE_ASSIGN
 clutch1._startForward = pre(clutch1.mode) == 0 and (clutch1.sa > clutch1.tau0_max or pre(clutch1.startForward) and clutch1.sa > clutch1.tau0) or pre(clutch1.mode) == -1 and clutch1.w_rel > clutch1.w_small or initial() and clutch1.w_rel > 0.0
 */
void CoupledClutches_eqFunction_115(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,115};
  modelica_boolean tmp1228;
  modelica_boolean tmp1229;
  modelica_boolean tmp1231;
  modelica_boolean tmp1232;
  RELATIONHYSTERESIS(tmp1228, $Pclutch1$Psa, $Pclutch1$Ptau0_max, 10, Greater);
  RELATIONHYSTERESIS(tmp1229, $Pclutch1$Psa, $Pclutch1$Ptau0, 11, Greater);
  RELATIONHYSTERESIS(tmp1231, $Pclutch1$Pw_rel, $Pclutch1$Pw_small, 12, Greater);
  RELATIONHYSTERESIS(tmp1232, $Pclutch1$Pw_rel, 0.0, 13, Greater);
  $Pclutch1$PstartForward = (((($P$PRE$Pclutch1$Pmode == (modelica_integer) 0) && (tmp1228 || ($P$PRE$Pclutch1$PstartForward && tmp1229))) || (($P$PRE$Pclutch1$Pmode == (modelica_integer) -1) && tmp1231)) || (initial() && tmp1232));
  TRACE_POP
}
/*
 equation index: 116
 type: SIMPLE_ASSIGN
 clutch1._tau = clutch2.tau - J2.J * J2.a
 */
void CoupledClutches_eqFunction_116(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,116};
  $Pclutch1$Ptau = ($Pclutch2$Ptau - ($PJ2$PJ * $PJ2$Pa));
  TRACE_POP
}
/*
 equation index: 117
 type: SIMPLE_ASSIGN
 clutch1._locked = not clutch1.free and not (pre(clutch1.mode) == 1 or clutch1.startForward or pre(clutch1.mode) == -1 or clutch1.startBackward)
 */
void CoupledClutches_eqFunction_117(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,117};
  $Pclutch1$Plocked = ((!$Pclutch1$Pfree) && (!(((($P$PRE$Pclutch1$Pmode == (modelica_integer) 1) || $Pclutch1$PstartForward) || ($P$PRE$Pclutch1$Pmode == (modelica_integer) -1)) || $Pclutch1$PstartBackward)));
  TRACE_POP
}
/*
 equation index: 118
 type: SIMPLE_ASSIGN
 J1._a = DIVISION(sin1.y + clutch1.tau, J1.J)
 */
void CoupledClutches_eqFunction_118(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,118};
  $PJ1$Pa = DIVISION_SIM(($Psin1$Py + $Pclutch1$Ptau),$PJ1$PJ,"J1.J",equationIndexes);
  TRACE_POP
}
/*
 equation index: 119
 type: SIMPLE_ASSIGN
 clutch1._a_relfric = if clutch1.locked then 0.0 else if clutch1.free then clutch1.sa else if clutch1.startForward then clutch1.sa - clutch1.tau0_max else if clutch1.startBackward then clutch1.sa + clutch1.tau0_max else if pre(clutch1.mode) == 1 then clutch1.sa - clutch1.tau0_max else clutch1.sa + clutch1.tau0_max
 */
void CoupledClutches_eqFunction_119(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,119};
  $Pclutch1$Pa_relfric = ($Pclutch1$Plocked?0.0:($Pclutch1$Pfree?$Pclutch1$Psa:($Pclutch1$PstartForward?($Pclutch1$Psa - $Pclutch1$Ptau0_max):($Pclutch1$PstartBackward?($Pclutch1$Psa + $Pclutch1$Ptau0_max):(($P$PRE$Pclutch1$Pmode == (modelica_integer) 1)?($Pclutch1$Psa - $Pclutch1$Ptau0_max):($Pclutch1$Psa + $Pclutch1$Ptau0_max))))));
  TRACE_POP
}
void initializeStaticNLSData123(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $Pclutch3$Psa */
  nlsData->nominal[i] = $P$ATTRIBUTE$Pclutch3$Psa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$Pclutch3$Psa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$Pclutch3$Psa.max;
  /* static nls data for $Pclutch2$Psa */
  nlsData->nominal[i] = $P$ATTRIBUTE$Pclutch2$Psa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$Pclutch2$Psa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$Pclutch2$Psa.max;
  /* static nls data for $Pclutch1$Psa */
  nlsData->nominal[i] = $P$ATTRIBUTE$Pclutch1$Psa.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$Pclutch1$Psa.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$Pclutch1$Psa.max;
}

void residualFunc123(void* dataIn, const double* xloc, double* res, const int* iflag)
{
  DATA* data = (DATA*) dataIn;
  const int equationIndexes[2] = {1,123};
  real_array tmp1236;
  real_array tmp1237;
  real_array tmp1239;
  real_array tmp1240;
  modelica_boolean tmp1241;
  modelica_real tmp1242;
  modelica_boolean tmp1243;
  modelica_real tmp1244;
  modelica_boolean tmp1245;
  modelica_real tmp1246;
  modelica_boolean tmp1247;
  modelica_real tmp1248;
  modelica_boolean tmp1249;
  modelica_real tmp1250;
  $Pclutch3$Psa = xloc[0];
  $Pclutch2$Psa = xloc[1];
  $Pclutch1$Psa = xloc[2];
  CoupledClutches_eqFunction_101(data);

  CoupledClutches_eqFunction_102(data);

  CoupledClutches_eqFunction_103(data);

  CoupledClutches_eqFunction_104(data);

  CoupledClutches_eqFunction_105(data);

  CoupledClutches_eqFunction_106(data);

  CoupledClutches_eqFunction_107(data);

  CoupledClutches_eqFunction_108(data);

  CoupledClutches_eqFunction_109(data);

  CoupledClutches_eqFunction_110(data);

  CoupledClutches_eqFunction_111(data);

  CoupledClutches_eqFunction_112(data);

  CoupledClutches_eqFunction_113(data);

  CoupledClutches_eqFunction_114(data);

  CoupledClutches_eqFunction_115(data);

  CoupledClutches_eqFunction_116(data);

  CoupledClutches_eqFunction_117(data);

  CoupledClutches_eqFunction_118(data);

  CoupledClutches_eqFunction_119(data);
  tmp1249 = (modelica_boolean)$Pclutch1$Plocked;
  if(tmp1249)
  {
    tmp1250 = $Pclutch1$Psa;
  }
  else
  {
    tmp1247 = (modelica_boolean)$Pclutch1$Pfree;
    if(tmp1247)
    {
      tmp1248 = 0.0;
    }
    else
    {
      tmp1245 = (modelica_boolean)$Pclutch1$PstartForward;
      if(tmp1245)
      {
        /* -- start: matrix[1,2] -- */
        alloc_real_array(&tmp1236, 2, 1, 2);
        put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1236);
        put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1236);
        /* -- end: matrix[1,2] -- */
        tmp1246 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch1$Pw_rel, tmp1236, (modelica_integer) 2);
      }
      else
      {
        tmp1243 = (modelica_boolean)$Pclutch1$PstartBackward;
        if(tmp1243)
        {
          /* -- start: matrix[1,2] -- */
          alloc_real_array(&tmp1237, 2, 1, 2);
          put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1237);
          put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1237);
          /* -- end: matrix[1,2] -- */
          tmp1244 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch1$Pw_rel), tmp1237, (modelica_integer) 2));
        }
        else
        {
          tmp1241 = (modelica_boolean)($P$PRE$Pclutch1$Pmode == (modelica_integer) 1);
          if(tmp1241)
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1239, 2, 1, 2);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1239);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1239);
            /* -- end: matrix[1,2] -- */
            tmp1242 = omc_Modelica_Math_tempInterpol1(threadData, $Pclutch1$Pw_rel, tmp1239, (modelica_integer) 2);
          }
          else
          {
            /* -- start: matrix[1,2] -- */
            alloc_real_array(&tmp1240, 2, 1, 2);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c1$rB, 0, 0, &tmp1240);
            put_real_matrix_element($Pclutch1$Pmue_pos$lB1$c2$rB, 0, 1, &tmp1240);
            /* -- end: matrix[1,2] -- */
            tmp1242 = (-omc_Modelica_Math_tempInterpol1(threadData, (-$Pclutch1$Pw_rel), tmp1240, (modelica_integer) 2));
          }
          tmp1244 = tmp1242;
        }
        tmp1246 = tmp1244;
      }
      tmp1248 = ($Pclutch1$Pcgeo * ($Pclutch1$Pfn * tmp1246));
    }
    tmp1250 = tmp1248;
  }
  res[0] = (tmp1250 - $Pclutch1$Ptau);

  res[1] = ($PJ4$Pa + ((-$PJ3$Pa) - $Pclutch3$Pa_relfric));

  res[2] = ($PJ2$Pa + ((-$PJ1$Pa) - $Pclutch1$Pa_relfric));
}

/* funtion initialize non-linear systems */
void CoupledClutches_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA* nonLinearSystemData)
{
  assertStreamPrint(NULL, nNonLinearSystems > 0, "Internal Error: nNonLinearSystems mismatch!");
  nonLinearSystemData[0].equationIndex = 71;
  nonLinearSystemData[0].size = 4;
  nonLinearSystemData[0].method = 0;
  nonLinearSystemData[0].homotopySupport = 0;
  nonLinearSystemData[0].mixedSystem = 1;
  nonLinearSystemData[0].residualFunc = residualFunc71;
  nonLinearSystemData[0].analyticalJacobianColumn = NULL;
  nonLinearSystemData[0].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[0].jacobianIndex = -1;
  nonLinearSystemData[0].initializeStaticNLSData = initializeStaticNLSData71;
  assertStreamPrint(NULL, nNonLinearSystems > 1, "Internal Error: nNonLinearSystems mismatch!");
  nonLinearSystemData[1].equationIndex = 123;
  nonLinearSystemData[1].size = 3;
  nonLinearSystemData[1].method = 0;
  nonLinearSystemData[1].homotopySupport = 0;
  nonLinearSystemData[1].mixedSystem = 1;
  nonLinearSystemData[1].residualFunc = residualFunc123;
  nonLinearSystemData[1].analyticalJacobianColumn = NULL;
  nonLinearSystemData[1].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[1].jacobianIndex = -1;
  nonLinearSystemData[1].initializeStaticNLSData = initializeStaticNLSData123;
}

#if defined(__cplusplus)
}
#endif

