/* Simulation code for CoupledClutches generated by the OpenModelica Compiler 1.9.2+dev (r24999). */
#define time data->localData[0]->timeValue

/* States */
/* J3.phi */
#define _$PJ3$Pphi(i) data->localData[i]->realVars[0]
#define $PJ3$Pphi _$PJ3$Pphi(0)
#define $P$PRE$PJ3$Pphi data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$PJ3$Pphi data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PJ3$Pphi $P$ATTRIBUTE$PJ3$Pphi
#define $PJ3$Pphi__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$PJ3$Pphi__varInfo data->modelData.realVarsData[0].info
#define _$P$PRE$PJ3$Pphi(i) $P$PRE$PJ3$Pphi


/* J3.w */
#define _$PJ3$Pw(i) data->localData[i]->realVars[1]
#define $PJ3$Pw _$PJ3$Pw(0)
#define $P$PRE$PJ3$Pw data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$PJ3$Pw data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PJ3$Pw $P$ATTRIBUTE$PJ3$Pw
#define $PJ3$Pw__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$PJ3$Pw__varInfo data->modelData.realVarsData[1].info
#define _$P$PRE$PJ3$Pw(i) $P$PRE$PJ3$Pw


/* clutch1.phi_rel */
#define _$Pclutch1$Pphi_rel(i) data->localData[i]->realVars[2]
#define $Pclutch1$Pphi_rel _$Pclutch1$Pphi_rel(0)
#define $P$PRE$Pclutch1$Pphi_rel data->simulationInfo.realVarsPre[2]
#define $P$ATTRIBUTE$Pclutch1$Pphi_rel data->modelData.realVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pphi_rel $P$ATTRIBUTE$Pclutch1$Pphi_rel
#define $Pclutch1$Pphi_rel__varInfo data->modelData.realVarsData[2].info
#define $P$PRE$Pclutch1$Pphi_rel__varInfo data->modelData.realVarsData[2].info
#define _$P$PRE$Pclutch1$Pphi_rel(i) $P$PRE$Pclutch1$Pphi_rel


/* clutch1.w_rel */
#define _$Pclutch1$Pw_rel(i) data->localData[i]->realVars[3]
#define $Pclutch1$Pw_rel _$Pclutch1$Pw_rel(0)
#define $P$PRE$Pclutch1$Pw_rel data->simulationInfo.realVarsPre[3]
#define $P$ATTRIBUTE$Pclutch1$Pw_rel data->modelData.realVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pw_rel $P$ATTRIBUTE$Pclutch1$Pw_rel
#define $Pclutch1$Pw_rel__varInfo data->modelData.realVarsData[3].info
#define $P$PRE$Pclutch1$Pw_rel__varInfo data->modelData.realVarsData[3].info
#define _$P$PRE$Pclutch1$Pw_rel(i) $P$PRE$Pclutch1$Pw_rel


/* clutch2.phi_rel */
#define _$Pclutch2$Pphi_rel(i) data->localData[i]->realVars[4]
#define $Pclutch2$Pphi_rel _$Pclutch2$Pphi_rel(0)
#define $P$PRE$Pclutch2$Pphi_rel data->simulationInfo.realVarsPre[4]
#define $P$ATTRIBUTE$Pclutch2$Pphi_rel data->modelData.realVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pphi_rel $P$ATTRIBUTE$Pclutch2$Pphi_rel
#define $Pclutch2$Pphi_rel__varInfo data->modelData.realVarsData[4].info
#define $P$PRE$Pclutch2$Pphi_rel__varInfo data->modelData.realVarsData[4].info
#define _$P$PRE$Pclutch2$Pphi_rel(i) $P$PRE$Pclutch2$Pphi_rel


/* clutch2.w_rel */
#define _$Pclutch2$Pw_rel(i) data->localData[i]->realVars[5]
#define $Pclutch2$Pw_rel _$Pclutch2$Pw_rel(0)
#define $P$PRE$Pclutch2$Pw_rel data->simulationInfo.realVarsPre[5]
#define $P$ATTRIBUTE$Pclutch2$Pw_rel data->modelData.realVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pw_rel $P$ATTRIBUTE$Pclutch2$Pw_rel
#define $Pclutch2$Pw_rel__varInfo data->modelData.realVarsData[5].info
#define $P$PRE$Pclutch2$Pw_rel__varInfo data->modelData.realVarsData[5].info
#define _$P$PRE$Pclutch2$Pw_rel(i) $P$PRE$Pclutch2$Pw_rel


/* clutch3.phi_rel */
#define _$Pclutch3$Pphi_rel(i) data->localData[i]->realVars[6]
#define $Pclutch3$Pphi_rel _$Pclutch3$Pphi_rel(0)
#define $P$PRE$Pclutch3$Pphi_rel data->simulationInfo.realVarsPre[6]
#define $P$ATTRIBUTE$Pclutch3$Pphi_rel data->modelData.realVarsData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pphi_rel $P$ATTRIBUTE$Pclutch3$Pphi_rel
#define $Pclutch3$Pphi_rel__varInfo data->modelData.realVarsData[6].info
#define $P$PRE$Pclutch3$Pphi_rel__varInfo data->modelData.realVarsData[6].info
#define _$P$PRE$Pclutch3$Pphi_rel(i) $P$PRE$Pclutch3$Pphi_rel


/* clutch3.w_rel */
#define _$Pclutch3$Pw_rel(i) data->localData[i]->realVars[7]
#define $Pclutch3$Pw_rel _$Pclutch3$Pw_rel(0)
#define $P$PRE$Pclutch3$Pw_rel data->simulationInfo.realVarsPre[7]
#define $P$ATTRIBUTE$Pclutch3$Pw_rel data->modelData.realVarsData[7].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pw_rel $P$ATTRIBUTE$Pclutch3$Pw_rel
#define $Pclutch3$Pw_rel__varInfo data->modelData.realVarsData[7].info
#define $P$PRE$Pclutch3$Pw_rel__varInfo data->modelData.realVarsData[7].info
#define _$P$PRE$Pclutch3$Pw_rel(i) $P$PRE$Pclutch3$Pw_rel


/* StatesDerivatives */
/* der(J3.phi) */
#define _$P$DER$PJ3$Pphi(i) data->localData[i]->realVars[8]
#define $P$DER$PJ3$Pphi _$P$DER$PJ3$Pphi(0)
#define $P$PRE$P$DER$PJ3$Pphi data->simulationInfo.realVarsPre[8]
#define $P$ATTRIBUTE$P$DER$PJ3$Pphi data->modelData.realVarsData[8].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$PJ3$Pphi $P$ATTRIBUTE$P$DER$PJ3$Pphi
#define $P$DER$PJ3$Pphi__varInfo data->modelData.realVarsData[8].info
#define $P$PRE$P$DER$PJ3$Pphi__varInfo data->modelData.realVarsData[8].info
#define _$P$PRE$P$DER$PJ3$Pphi(i) $P$PRE$P$DER$PJ3$Pphi


/* der(J3.w) */
#define _$P$DER$PJ3$Pw(i) data->localData[i]->realVars[9]
#define $P$DER$PJ3$Pw _$P$DER$PJ3$Pw(0)
#define $P$PRE$P$DER$PJ3$Pw data->simulationInfo.realVarsPre[9]
#define $P$ATTRIBUTE$P$DER$PJ3$Pw data->modelData.realVarsData[9].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$PJ3$Pw $P$ATTRIBUTE$P$DER$PJ3$Pw
#define $P$DER$PJ3$Pw__varInfo data->modelData.realVarsData[9].info
#define $P$PRE$P$DER$PJ3$Pw__varInfo data->modelData.realVarsData[9].info
#define _$P$PRE$P$DER$PJ3$Pw(i) $P$PRE$P$DER$PJ3$Pw


/* der(clutch1.phi_rel) */
#define _$P$DER$Pclutch1$Pphi_rel(i) data->localData[i]->realVars[10]
#define $P$DER$Pclutch1$Pphi_rel _$P$DER$Pclutch1$Pphi_rel(0)
#define $P$PRE$P$DER$Pclutch1$Pphi_rel data->simulationInfo.realVarsPre[10]
#define $P$ATTRIBUTE$P$DER$Pclutch1$Pphi_rel data->modelData.realVarsData[10].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Pclutch1$Pphi_rel $P$ATTRIBUTE$P$DER$Pclutch1$Pphi_rel
#define $P$DER$Pclutch1$Pphi_rel__varInfo data->modelData.realVarsData[10].info
#define $P$PRE$P$DER$Pclutch1$Pphi_rel__varInfo data->modelData.realVarsData[10].info
#define _$P$PRE$P$DER$Pclutch1$Pphi_rel(i) $P$PRE$P$DER$Pclutch1$Pphi_rel


/* der(clutch1.w_rel) */
#define _$P$DER$Pclutch1$Pw_rel(i) data->localData[i]->realVars[11]
#define $P$DER$Pclutch1$Pw_rel _$P$DER$Pclutch1$Pw_rel(0)
#define $P$PRE$P$DER$Pclutch1$Pw_rel data->simulationInfo.realVarsPre[11]
#define $P$ATTRIBUTE$P$DER$Pclutch1$Pw_rel data->modelData.realVarsData[11].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Pclutch1$Pw_rel $P$ATTRIBUTE$P$DER$Pclutch1$Pw_rel
#define $P$DER$Pclutch1$Pw_rel__varInfo data->modelData.realVarsData[11].info
#define $P$PRE$P$DER$Pclutch1$Pw_rel__varInfo data->modelData.realVarsData[11].info
#define _$P$PRE$P$DER$Pclutch1$Pw_rel(i) $P$PRE$P$DER$Pclutch1$Pw_rel


/* der(clutch2.phi_rel) */
#define _$P$DER$Pclutch2$Pphi_rel(i) data->localData[i]->realVars[12]
#define $P$DER$Pclutch2$Pphi_rel _$P$DER$Pclutch2$Pphi_rel(0)
#define $P$PRE$P$DER$Pclutch2$Pphi_rel data->simulationInfo.realVarsPre[12]
#define $P$ATTRIBUTE$P$DER$Pclutch2$Pphi_rel data->modelData.realVarsData[12].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Pclutch2$Pphi_rel $P$ATTRIBUTE$P$DER$Pclutch2$Pphi_rel
#define $P$DER$Pclutch2$Pphi_rel__varInfo data->modelData.realVarsData[12].info
#define $P$PRE$P$DER$Pclutch2$Pphi_rel__varInfo data->modelData.realVarsData[12].info
#define _$P$PRE$P$DER$Pclutch2$Pphi_rel(i) $P$PRE$P$DER$Pclutch2$Pphi_rel


/* der(clutch2.w_rel) */
#define _$P$DER$Pclutch2$Pw_rel(i) data->localData[i]->realVars[13]
#define $P$DER$Pclutch2$Pw_rel _$P$DER$Pclutch2$Pw_rel(0)
#define $P$PRE$P$DER$Pclutch2$Pw_rel data->simulationInfo.realVarsPre[13]
#define $P$ATTRIBUTE$P$DER$Pclutch2$Pw_rel data->modelData.realVarsData[13].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Pclutch2$Pw_rel $P$ATTRIBUTE$P$DER$Pclutch2$Pw_rel
#define $P$DER$Pclutch2$Pw_rel__varInfo data->modelData.realVarsData[13].info
#define $P$PRE$P$DER$Pclutch2$Pw_rel__varInfo data->modelData.realVarsData[13].info
#define _$P$PRE$P$DER$Pclutch2$Pw_rel(i) $P$PRE$P$DER$Pclutch2$Pw_rel


/* der(clutch3.phi_rel) */
#define _$P$DER$Pclutch3$Pphi_rel(i) data->localData[i]->realVars[14]
#define $P$DER$Pclutch3$Pphi_rel _$P$DER$Pclutch3$Pphi_rel(0)
#define $P$PRE$P$DER$Pclutch3$Pphi_rel data->simulationInfo.realVarsPre[14]
#define $P$ATTRIBUTE$P$DER$Pclutch3$Pphi_rel data->modelData.realVarsData[14].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Pclutch3$Pphi_rel $P$ATTRIBUTE$P$DER$Pclutch3$Pphi_rel
#define $P$DER$Pclutch3$Pphi_rel__varInfo data->modelData.realVarsData[14].info
#define $P$PRE$P$DER$Pclutch3$Pphi_rel__varInfo data->modelData.realVarsData[14].info
#define _$P$PRE$P$DER$Pclutch3$Pphi_rel(i) $P$PRE$P$DER$Pclutch3$Pphi_rel


/* der(clutch3.w_rel) */
#define _$P$DER$Pclutch3$Pw_rel(i) data->localData[i]->realVars[15]
#define $P$DER$Pclutch3$Pw_rel _$P$DER$Pclutch3$Pw_rel(0)
#define $P$PRE$P$DER$Pclutch3$Pw_rel data->simulationInfo.realVarsPre[15]
#define $P$ATTRIBUTE$P$DER$Pclutch3$Pw_rel data->modelData.realVarsData[15].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Pclutch3$Pw_rel $P$ATTRIBUTE$P$DER$Pclutch3$Pw_rel
#define $P$DER$Pclutch3$Pw_rel__varInfo data->modelData.realVarsData[15].info
#define $P$PRE$P$DER$Pclutch3$Pw_rel__varInfo data->modelData.realVarsData[15].info
#define _$P$PRE$P$DER$Pclutch3$Pw_rel(i) $P$PRE$P$DER$Pclutch3$Pw_rel


/* Non Discrete Real Algebraic Vars */
/* J1.a */
#define _$PJ1$Pa(i) data->localData[i]->realVars[16]
#define $PJ1$Pa _$PJ1$Pa(0)
#define $P$PRE$PJ1$Pa data->simulationInfo.realVarsPre[16]
#define $P$ATTRIBUTE$PJ1$Pa data->modelData.realVarsData[16].attribute
#define $P$ATTRIBUTE$P$PRE$PJ1$Pa $P$ATTRIBUTE$PJ1$Pa
#define $PJ1$Pa__varInfo data->modelData.realVarsData[16].info
#define $P$PRE$PJ1$Pa__varInfo data->modelData.realVarsData[16].info
#define _$P$PRE$PJ1$Pa(i) $P$PRE$PJ1$Pa


/* J1.phi */
#define _$PJ1$Pphi(i) data->localData[i]->realVars[17]
#define $PJ1$Pphi _$PJ1$Pphi(0)
#define $P$PRE$PJ1$Pphi data->simulationInfo.realVarsPre[17]
#define $P$ATTRIBUTE$PJ1$Pphi data->modelData.realVarsData[17].attribute
#define $P$ATTRIBUTE$P$PRE$PJ1$Pphi $P$ATTRIBUTE$PJ1$Pphi
#define $PJ1$Pphi__varInfo data->modelData.realVarsData[17].info
#define $P$PRE$PJ1$Pphi__varInfo data->modelData.realVarsData[17].info
#define _$P$PRE$PJ1$Pphi(i) $P$PRE$PJ1$Pphi


/* J1_w1 */
#define _$PJ1_w1(i) data->localData[i]->realVars[18]
#define $PJ1_w1 _$PJ1_w1(0)
#define $P$PRE$PJ1_w1 data->simulationInfo.realVarsPre[18]
#define $P$ATTRIBUTE$PJ1_w1 data->modelData.realVarsData[18].attribute
#define $P$ATTRIBUTE$P$PRE$PJ1_w1 $P$ATTRIBUTE$PJ1_w1
#define $PJ1_w1__varInfo data->modelData.realVarsData[18].info
#define $P$PRE$PJ1_w1__varInfo data->modelData.realVarsData[18].info
#define _$P$PRE$PJ1_w1(i) $P$PRE$PJ1_w1


/* J2.a */
#define _$PJ2$Pa(i) data->localData[i]->realVars[19]
#define $PJ2$Pa _$PJ2$Pa(0)
#define $P$PRE$PJ2$Pa data->simulationInfo.realVarsPre[19]
#define $P$ATTRIBUTE$PJ2$Pa data->modelData.realVarsData[19].attribute
#define $P$ATTRIBUTE$P$PRE$PJ2$Pa $P$ATTRIBUTE$PJ2$Pa
#define $PJ2$Pa__varInfo data->modelData.realVarsData[19].info
#define $P$PRE$PJ2$Pa__varInfo data->modelData.realVarsData[19].info
#define _$P$PRE$PJ2$Pa(i) $P$PRE$PJ2$Pa


/* J2.phi */
#define _$PJ2$Pphi(i) data->localData[i]->realVars[20]
#define $PJ2$Pphi _$PJ2$Pphi(0)
#define $P$PRE$PJ2$Pphi data->simulationInfo.realVarsPre[20]
#define $P$ATTRIBUTE$PJ2$Pphi data->modelData.realVarsData[20].attribute
#define $P$ATTRIBUTE$P$PRE$PJ2$Pphi $P$ATTRIBUTE$PJ2$Pphi
#define $PJ2$Pphi__varInfo data->modelData.realVarsData[20].info
#define $P$PRE$PJ2$Pphi__varInfo data->modelData.realVarsData[20].info
#define _$P$PRE$PJ2$Pphi(i) $P$PRE$PJ2$Pphi


/* J2_w1 */
#define _$PJ2_w1(i) data->localData[i]->realVars[21]
#define $PJ2_w1 _$PJ2_w1(0)
#define $P$PRE$PJ2_w1 data->simulationInfo.realVarsPre[21]
#define $P$ATTRIBUTE$PJ2_w1 data->modelData.realVarsData[21].attribute
#define $P$ATTRIBUTE$P$PRE$PJ2_w1 $P$ATTRIBUTE$PJ2_w1
#define $PJ2_w1__varInfo data->modelData.realVarsData[21].info
#define $P$PRE$PJ2_w1__varInfo data->modelData.realVarsData[21].info
#define _$P$PRE$PJ2_w1(i) $P$PRE$PJ2_w1


/* J3.a */
#define _$PJ3$Pa(i) data->localData[i]->realVars[22]
#define $PJ3$Pa _$PJ3$Pa(0)
#define $P$PRE$PJ3$Pa data->simulationInfo.realVarsPre[22]
#define $P$ATTRIBUTE$PJ3$Pa data->modelData.realVarsData[22].attribute
#define $P$ATTRIBUTE$P$PRE$PJ3$Pa $P$ATTRIBUTE$PJ3$Pa
#define $PJ3$Pa__varInfo data->modelData.realVarsData[22].info
#define $P$PRE$PJ3$Pa__varInfo data->modelData.realVarsData[22].info
#define _$P$PRE$PJ3$Pa(i) $P$PRE$PJ3$Pa


/* J3_w1 */
#define _$PJ3_w1(i) data->localData[i]->realVars[23]
#define $PJ3_w1 _$PJ3_w1(0)
#define $P$PRE$PJ3_w1 data->simulationInfo.realVarsPre[23]
#define $P$ATTRIBUTE$PJ3_w1 data->modelData.realVarsData[23].attribute
#define $P$ATTRIBUTE$P$PRE$PJ3_w1 $P$ATTRIBUTE$PJ3_w1
#define $PJ3_w1__varInfo data->modelData.realVarsData[23].info
#define $P$PRE$PJ3_w1__varInfo data->modelData.realVarsData[23].info
#define _$P$PRE$PJ3_w1(i) $P$PRE$PJ3_w1


/* J4.a */
#define _$PJ4$Pa(i) data->localData[i]->realVars[24]
#define $PJ4$Pa _$PJ4$Pa(0)
#define $P$PRE$PJ4$Pa data->simulationInfo.realVarsPre[24]
#define $P$ATTRIBUTE$PJ4$Pa data->modelData.realVarsData[24].attribute
#define $P$ATTRIBUTE$P$PRE$PJ4$Pa $P$ATTRIBUTE$PJ4$Pa
#define $PJ4$Pa__varInfo data->modelData.realVarsData[24].info
#define $P$PRE$PJ4$Pa__varInfo data->modelData.realVarsData[24].info
#define _$P$PRE$PJ4$Pa(i) $P$PRE$PJ4$Pa


/* J4.flange_b.tau */
#define _$PJ4$Pflange_b$Ptau(i) data->localData[i]->realVars[25]
#define $PJ4$Pflange_b$Ptau _$PJ4$Pflange_b$Ptau(0)
#define $P$PRE$PJ4$Pflange_b$Ptau data->simulationInfo.realVarsPre[25]
#define $P$ATTRIBUTE$PJ4$Pflange_b$Ptau data->modelData.realVarsData[25].attribute
#define $P$ATTRIBUTE$P$PRE$PJ4$Pflange_b$Ptau $P$ATTRIBUTE$PJ4$Pflange_b$Ptau
#define $PJ4$Pflange_b$Ptau__varInfo data->modelData.realVarsData[25].info
#define $P$PRE$PJ4$Pflange_b$Ptau__varInfo data->modelData.realVarsData[25].info
#define _$P$PRE$PJ4$Pflange_b$Ptau(i) $P$PRE$PJ4$Pflange_b$Ptau


/* J4.phi */
#define _$PJ4$Pphi(i) data->localData[i]->realVars[26]
#define $PJ4$Pphi _$PJ4$Pphi(0)
#define $P$PRE$PJ4$Pphi data->simulationInfo.realVarsPre[26]
#define $P$ATTRIBUTE$PJ4$Pphi data->modelData.realVarsData[26].attribute
#define $P$ATTRIBUTE$P$PRE$PJ4$Pphi $P$ATTRIBUTE$PJ4$Pphi
#define $PJ4$Pphi__varInfo data->modelData.realVarsData[26].info
#define $P$PRE$PJ4$Pphi__varInfo data->modelData.realVarsData[26].info
#define _$P$PRE$PJ4$Pphi(i) $P$PRE$PJ4$Pphi


/* J4_w1 */
#define _$PJ4_w1(i) data->localData[i]->realVars[27]
#define $PJ4_w1 _$PJ4_w1(0)
#define $P$PRE$PJ4_w1 data->simulationInfo.realVarsPre[27]
#define $P$ATTRIBUTE$PJ4_w1 data->modelData.realVarsData[27].attribute
#define $P$ATTRIBUTE$P$PRE$PJ4_w1 $P$ATTRIBUTE$PJ4_w1
#define $PJ4_w1__varInfo data->modelData.realVarsData[27].info
#define $P$PRE$PJ4_w1__varInfo data->modelData.realVarsData[27].info
#define _$P$PRE$PJ4_w1(i) $P$PRE$PJ4_w1


/* clutch1.a_relfric */
#define _$Pclutch1$Pa_relfric(i) data->localData[i]->realVars[28]
#define $Pclutch1$Pa_relfric _$Pclutch1$Pa_relfric(0)
#define $P$PRE$Pclutch1$Pa_relfric data->simulationInfo.realVarsPre[28]
#define $P$ATTRIBUTE$Pclutch1$Pa_relfric data->modelData.realVarsData[28].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pa_relfric $P$ATTRIBUTE$Pclutch1$Pa_relfric
#define $Pclutch1$Pa_relfric__varInfo data->modelData.realVarsData[28].info
#define $P$PRE$Pclutch1$Pa_relfric__varInfo data->modelData.realVarsData[28].info
#define _$P$PRE$Pclutch1$Pa_relfric(i) $P$PRE$Pclutch1$Pa_relfric


/* clutch1.f_normalized */
#define _$Pclutch1$Pf_normalized(i) data->localData[i]->realVars[29]
#define $Pclutch1$Pf_normalized _$Pclutch1$Pf_normalized(0)
#define $P$PRE$Pclutch1$Pf_normalized data->simulationInfo.realVarsPre[29]
#define $P$ATTRIBUTE$Pclutch1$Pf_normalized data->modelData.realVarsData[29].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pf_normalized $P$ATTRIBUTE$Pclutch1$Pf_normalized
#define $Pclutch1$Pf_normalized__varInfo data->modelData.realVarsData[29].info
#define $P$PRE$Pclutch1$Pf_normalized__varInfo data->modelData.realVarsData[29].info
#define _$P$PRE$Pclutch1$Pf_normalized(i) $P$PRE$Pclutch1$Pf_normalized


/* clutch1.fn */
#define _$Pclutch1$Pfn(i) data->localData[i]->realVars[30]
#define $Pclutch1$Pfn _$Pclutch1$Pfn(0)
#define $P$PRE$Pclutch1$Pfn data->simulationInfo.realVarsPre[30]
#define $P$ATTRIBUTE$Pclutch1$Pfn data->modelData.realVarsData[30].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pfn $P$ATTRIBUTE$Pclutch1$Pfn
#define $Pclutch1$Pfn__varInfo data->modelData.realVarsData[30].info
#define $P$PRE$Pclutch1$Pfn__varInfo data->modelData.realVarsData[30].info
#define _$P$PRE$Pclutch1$Pfn(i) $P$PRE$Pclutch1$Pfn


/* clutch1.lossPower */
#define _$Pclutch1$PlossPower(i) data->localData[i]->realVars[31]
#define $Pclutch1$PlossPower _$Pclutch1$PlossPower(0)
#define $P$PRE$Pclutch1$PlossPower data->simulationInfo.realVarsPre[31]
#define $P$ATTRIBUTE$Pclutch1$PlossPower data->modelData.realVarsData[31].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$PlossPower $P$ATTRIBUTE$Pclutch1$PlossPower
#define $Pclutch1$PlossPower__varInfo data->modelData.realVarsData[31].info
#define $P$PRE$Pclutch1$PlossPower__varInfo data->modelData.realVarsData[31].info
#define _$P$PRE$Pclutch1$PlossPower(i) $P$PRE$Pclutch1$PlossPower


/* clutch1.mue0 */
#define _$Pclutch1$Pmue0(i) data->localData[i]->realVars[32]
#define $Pclutch1$Pmue0 _$Pclutch1$Pmue0(0)
#define $P$PRE$Pclutch1$Pmue0 data->simulationInfo.realVarsPre[32]
#define $P$ATTRIBUTE$Pclutch1$Pmue0 data->modelData.realVarsData[32].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pmue0 $P$ATTRIBUTE$Pclutch1$Pmue0
#define $Pclutch1$Pmue0__varInfo data->modelData.realVarsData[32].info
#define $P$PRE$Pclutch1$Pmue0__varInfo data->modelData.realVarsData[32].info
#define _$P$PRE$Pclutch1$Pmue0(i) $P$PRE$Pclutch1$Pmue0


/* clutch1.sa */
#define _$Pclutch1$Psa(i) data->localData[i]->realVars[33]
#define $Pclutch1$Psa _$Pclutch1$Psa(0)
#define $P$PRE$Pclutch1$Psa data->simulationInfo.realVarsPre[33]
#define $P$ATTRIBUTE$Pclutch1$Psa data->modelData.realVarsData[33].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Psa $P$ATTRIBUTE$Pclutch1$Psa
#define $Pclutch1$Psa__varInfo data->modelData.realVarsData[33].info
#define $P$PRE$Pclutch1$Psa__varInfo data->modelData.realVarsData[33].info
#define _$P$PRE$Pclutch1$Psa(i) $P$PRE$Pclutch1$Psa


/* clutch1.tau */
#define _$Pclutch1$Ptau(i) data->localData[i]->realVars[34]
#define $Pclutch1$Ptau _$Pclutch1$Ptau(0)
#define $P$PRE$Pclutch1$Ptau data->simulationInfo.realVarsPre[34]
#define $P$ATTRIBUTE$Pclutch1$Ptau data->modelData.realVarsData[34].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Ptau $P$ATTRIBUTE$Pclutch1$Ptau
#define $Pclutch1$Ptau__varInfo data->modelData.realVarsData[34].info
#define $P$PRE$Pclutch1$Ptau__varInfo data->modelData.realVarsData[34].info
#define _$P$PRE$Pclutch1$Ptau(i) $P$PRE$Pclutch1$Ptau


/* clutch1.tau0 */
#define _$Pclutch1$Ptau0(i) data->localData[i]->realVars[35]
#define $Pclutch1$Ptau0 _$Pclutch1$Ptau0(0)
#define $P$PRE$Pclutch1$Ptau0 data->simulationInfo.realVarsPre[35]
#define $P$ATTRIBUTE$Pclutch1$Ptau0 data->modelData.realVarsData[35].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Ptau0 $P$ATTRIBUTE$Pclutch1$Ptau0
#define $Pclutch1$Ptau0__varInfo data->modelData.realVarsData[35].info
#define $P$PRE$Pclutch1$Ptau0__varInfo data->modelData.realVarsData[35].info
#define _$P$PRE$Pclutch1$Ptau0(i) $P$PRE$Pclutch1$Ptau0


/* clutch1.tau0_max */
#define _$Pclutch1$Ptau0_max(i) data->localData[i]->realVars[36]
#define $Pclutch1$Ptau0_max _$Pclutch1$Ptau0_max(0)
#define $P$PRE$Pclutch1$Ptau0_max data->simulationInfo.realVarsPre[36]
#define $P$ATTRIBUTE$Pclutch1$Ptau0_max data->modelData.realVarsData[36].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Ptau0_max $P$ATTRIBUTE$Pclutch1$Ptau0_max
#define $Pclutch1$Ptau0_max__varInfo data->modelData.realVarsData[36].info
#define $P$PRE$Pclutch1$Ptau0_max__varInfo data->modelData.realVarsData[36].info
#define _$P$PRE$Pclutch1$Ptau0_max(i) $P$PRE$Pclutch1$Ptau0_max


/* clutch2.a_relfric */
#define _$Pclutch2$Pa_relfric(i) data->localData[i]->realVars[37]
#define $Pclutch2$Pa_relfric _$Pclutch2$Pa_relfric(0)
#define $P$PRE$Pclutch2$Pa_relfric data->simulationInfo.realVarsPre[37]
#define $P$ATTRIBUTE$Pclutch2$Pa_relfric data->modelData.realVarsData[37].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pa_relfric $P$ATTRIBUTE$Pclutch2$Pa_relfric
#define $Pclutch2$Pa_relfric__varInfo data->modelData.realVarsData[37].info
#define $P$PRE$Pclutch2$Pa_relfric__varInfo data->modelData.realVarsData[37].info
#define _$P$PRE$Pclutch2$Pa_relfric(i) $P$PRE$Pclutch2$Pa_relfric


/* clutch2.f_normalized */
#define _$Pclutch2$Pf_normalized(i) data->localData[i]->realVars[38]
#define $Pclutch2$Pf_normalized _$Pclutch2$Pf_normalized(0)
#define $P$PRE$Pclutch2$Pf_normalized data->simulationInfo.realVarsPre[38]
#define $P$ATTRIBUTE$Pclutch2$Pf_normalized data->modelData.realVarsData[38].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pf_normalized $P$ATTRIBUTE$Pclutch2$Pf_normalized
#define $Pclutch2$Pf_normalized__varInfo data->modelData.realVarsData[38].info
#define $P$PRE$Pclutch2$Pf_normalized__varInfo data->modelData.realVarsData[38].info
#define _$P$PRE$Pclutch2$Pf_normalized(i) $P$PRE$Pclutch2$Pf_normalized


/* clutch2.fn */
#define _$Pclutch2$Pfn(i) data->localData[i]->realVars[39]
#define $Pclutch2$Pfn _$Pclutch2$Pfn(0)
#define $P$PRE$Pclutch2$Pfn data->simulationInfo.realVarsPre[39]
#define $P$ATTRIBUTE$Pclutch2$Pfn data->modelData.realVarsData[39].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pfn $P$ATTRIBUTE$Pclutch2$Pfn
#define $Pclutch2$Pfn__varInfo data->modelData.realVarsData[39].info
#define $P$PRE$Pclutch2$Pfn__varInfo data->modelData.realVarsData[39].info
#define _$P$PRE$Pclutch2$Pfn(i) $P$PRE$Pclutch2$Pfn


/* clutch2.lossPower */
#define _$Pclutch2$PlossPower(i) data->localData[i]->realVars[40]
#define $Pclutch2$PlossPower _$Pclutch2$PlossPower(0)
#define $P$PRE$Pclutch2$PlossPower data->simulationInfo.realVarsPre[40]
#define $P$ATTRIBUTE$Pclutch2$PlossPower data->modelData.realVarsData[40].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$PlossPower $P$ATTRIBUTE$Pclutch2$PlossPower
#define $Pclutch2$PlossPower__varInfo data->modelData.realVarsData[40].info
#define $P$PRE$Pclutch2$PlossPower__varInfo data->modelData.realVarsData[40].info
#define _$P$PRE$Pclutch2$PlossPower(i) $P$PRE$Pclutch2$PlossPower


/* clutch2.mue0 */
#define _$Pclutch2$Pmue0(i) data->localData[i]->realVars[41]
#define $Pclutch2$Pmue0 _$Pclutch2$Pmue0(0)
#define $P$PRE$Pclutch2$Pmue0 data->simulationInfo.realVarsPre[41]
#define $P$ATTRIBUTE$Pclutch2$Pmue0 data->modelData.realVarsData[41].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pmue0 $P$ATTRIBUTE$Pclutch2$Pmue0
#define $Pclutch2$Pmue0__varInfo data->modelData.realVarsData[41].info
#define $P$PRE$Pclutch2$Pmue0__varInfo data->modelData.realVarsData[41].info
#define _$P$PRE$Pclutch2$Pmue0(i) $P$PRE$Pclutch2$Pmue0


/* clutch2.sa */
#define _$Pclutch2$Psa(i) data->localData[i]->realVars[42]
#define $Pclutch2$Psa _$Pclutch2$Psa(0)
#define $P$PRE$Pclutch2$Psa data->simulationInfo.realVarsPre[42]
#define $P$ATTRIBUTE$Pclutch2$Psa data->modelData.realVarsData[42].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Psa $P$ATTRIBUTE$Pclutch2$Psa
#define $Pclutch2$Psa__varInfo data->modelData.realVarsData[42].info
#define $P$PRE$Pclutch2$Psa__varInfo data->modelData.realVarsData[42].info
#define _$P$PRE$Pclutch2$Psa(i) $P$PRE$Pclutch2$Psa


/* clutch2.tau */
#define _$Pclutch2$Ptau(i) data->localData[i]->realVars[43]
#define $Pclutch2$Ptau _$Pclutch2$Ptau(0)
#define $P$PRE$Pclutch2$Ptau data->simulationInfo.realVarsPre[43]
#define $P$ATTRIBUTE$Pclutch2$Ptau data->modelData.realVarsData[43].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Ptau $P$ATTRIBUTE$Pclutch2$Ptau
#define $Pclutch2$Ptau__varInfo data->modelData.realVarsData[43].info
#define $P$PRE$Pclutch2$Ptau__varInfo data->modelData.realVarsData[43].info
#define _$P$PRE$Pclutch2$Ptau(i) $P$PRE$Pclutch2$Ptau


/* clutch2.tau0 */
#define _$Pclutch2$Ptau0(i) data->localData[i]->realVars[44]
#define $Pclutch2$Ptau0 _$Pclutch2$Ptau0(0)
#define $P$PRE$Pclutch2$Ptau0 data->simulationInfo.realVarsPre[44]
#define $P$ATTRIBUTE$Pclutch2$Ptau0 data->modelData.realVarsData[44].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Ptau0 $P$ATTRIBUTE$Pclutch2$Ptau0
#define $Pclutch2$Ptau0__varInfo data->modelData.realVarsData[44].info
#define $P$PRE$Pclutch2$Ptau0__varInfo data->modelData.realVarsData[44].info
#define _$P$PRE$Pclutch2$Ptau0(i) $P$PRE$Pclutch2$Ptau0


/* clutch2.tau0_max */
#define _$Pclutch2$Ptau0_max(i) data->localData[i]->realVars[45]
#define $Pclutch2$Ptau0_max _$Pclutch2$Ptau0_max(0)
#define $P$PRE$Pclutch2$Ptau0_max data->simulationInfo.realVarsPre[45]
#define $P$ATTRIBUTE$Pclutch2$Ptau0_max data->modelData.realVarsData[45].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Ptau0_max $P$ATTRIBUTE$Pclutch2$Ptau0_max
#define $Pclutch2$Ptau0_max__varInfo data->modelData.realVarsData[45].info
#define $P$PRE$Pclutch2$Ptau0_max__varInfo data->modelData.realVarsData[45].info
#define _$P$PRE$Pclutch2$Ptau0_max(i) $P$PRE$Pclutch2$Ptau0_max


/* clutch3.a_relfric */
#define _$Pclutch3$Pa_relfric(i) data->localData[i]->realVars[46]
#define $Pclutch3$Pa_relfric _$Pclutch3$Pa_relfric(0)
#define $P$PRE$Pclutch3$Pa_relfric data->simulationInfo.realVarsPre[46]
#define $P$ATTRIBUTE$Pclutch3$Pa_relfric data->modelData.realVarsData[46].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pa_relfric $P$ATTRIBUTE$Pclutch3$Pa_relfric
#define $Pclutch3$Pa_relfric__varInfo data->modelData.realVarsData[46].info
#define $P$PRE$Pclutch3$Pa_relfric__varInfo data->modelData.realVarsData[46].info
#define _$P$PRE$Pclutch3$Pa_relfric(i) $P$PRE$Pclutch3$Pa_relfric


/* clutch3.fn */
#define _$Pclutch3$Pfn(i) data->localData[i]->realVars[47]
#define $Pclutch3$Pfn _$Pclutch3$Pfn(0)
#define $P$PRE$Pclutch3$Pfn data->simulationInfo.realVarsPre[47]
#define $P$ATTRIBUTE$Pclutch3$Pfn data->modelData.realVarsData[47].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pfn $P$ATTRIBUTE$Pclutch3$Pfn
#define $Pclutch3$Pfn__varInfo data->modelData.realVarsData[47].info
#define $P$PRE$Pclutch3$Pfn__varInfo data->modelData.realVarsData[47].info
#define _$P$PRE$Pclutch3$Pfn(i) $P$PRE$Pclutch3$Pfn


/* clutch3.lossPower */
#define _$Pclutch3$PlossPower(i) data->localData[i]->realVars[48]
#define $Pclutch3$PlossPower _$Pclutch3$PlossPower(0)
#define $P$PRE$Pclutch3$PlossPower data->simulationInfo.realVarsPre[48]
#define $P$ATTRIBUTE$Pclutch3$PlossPower data->modelData.realVarsData[48].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$PlossPower $P$ATTRIBUTE$Pclutch3$PlossPower
#define $Pclutch3$PlossPower__varInfo data->modelData.realVarsData[48].info
#define $P$PRE$Pclutch3$PlossPower__varInfo data->modelData.realVarsData[48].info
#define _$P$PRE$Pclutch3$PlossPower(i) $P$PRE$Pclutch3$PlossPower


/* clutch3.mue0 */
#define _$Pclutch3$Pmue0(i) data->localData[i]->realVars[49]
#define $Pclutch3$Pmue0 _$Pclutch3$Pmue0(0)
#define $P$PRE$Pclutch3$Pmue0 data->simulationInfo.realVarsPre[49]
#define $P$ATTRIBUTE$Pclutch3$Pmue0 data->modelData.realVarsData[49].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pmue0 $P$ATTRIBUTE$Pclutch3$Pmue0
#define $Pclutch3$Pmue0__varInfo data->modelData.realVarsData[49].info
#define $P$PRE$Pclutch3$Pmue0__varInfo data->modelData.realVarsData[49].info
#define _$P$PRE$Pclutch3$Pmue0(i) $P$PRE$Pclutch3$Pmue0


/* clutch3.sa */
#define _$Pclutch3$Psa(i) data->localData[i]->realVars[50]
#define $Pclutch3$Psa _$Pclutch3$Psa(0)
#define $P$PRE$Pclutch3$Psa data->simulationInfo.realVarsPre[50]
#define $P$ATTRIBUTE$Pclutch3$Psa data->modelData.realVarsData[50].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Psa $P$ATTRIBUTE$Pclutch3$Psa
#define $Pclutch3$Psa__varInfo data->modelData.realVarsData[50].info
#define $P$PRE$Pclutch3$Psa__varInfo data->modelData.realVarsData[50].info
#define _$P$PRE$Pclutch3$Psa(i) $P$PRE$Pclutch3$Psa


/* clutch3.tau */
#define _$Pclutch3$Ptau(i) data->localData[i]->realVars[51]
#define $Pclutch3$Ptau _$Pclutch3$Ptau(0)
#define $P$PRE$Pclutch3$Ptau data->simulationInfo.realVarsPre[51]
#define $P$ATTRIBUTE$Pclutch3$Ptau data->modelData.realVarsData[51].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Ptau $P$ATTRIBUTE$Pclutch3$Ptau
#define $Pclutch3$Ptau__varInfo data->modelData.realVarsData[51].info
#define $P$PRE$Pclutch3$Ptau__varInfo data->modelData.realVarsData[51].info
#define _$P$PRE$Pclutch3$Ptau(i) $P$PRE$Pclutch3$Ptau


/* clutch3.tau0 */
#define _$Pclutch3$Ptau0(i) data->localData[i]->realVars[52]
#define $Pclutch3$Ptau0 _$Pclutch3$Ptau0(0)
#define $P$PRE$Pclutch3$Ptau0 data->simulationInfo.realVarsPre[52]
#define $P$ATTRIBUTE$Pclutch3$Ptau0 data->modelData.realVarsData[52].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Ptau0 $P$ATTRIBUTE$Pclutch3$Ptau0
#define $Pclutch3$Ptau0__varInfo data->modelData.realVarsData[52].info
#define $P$PRE$Pclutch3$Ptau0__varInfo data->modelData.realVarsData[52].info
#define _$P$PRE$Pclutch3$Ptau0(i) $P$PRE$Pclutch3$Ptau0


/* clutch3.tau0_max */
#define _$Pclutch3$Ptau0_max(i) data->localData[i]->realVars[53]
#define $Pclutch3$Ptau0_max _$Pclutch3$Ptau0_max(0)
#define $P$PRE$Pclutch3$Ptau0_max data->simulationInfo.realVarsPre[53]
#define $P$ATTRIBUTE$Pclutch3$Ptau0_max data->modelData.realVarsData[53].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Ptau0_max $P$ATTRIBUTE$Pclutch3$Ptau0_max
#define $Pclutch3$Ptau0_max__varInfo data->modelData.realVarsData[53].info
#define $P$PRE$Pclutch3$Ptau0_max__varInfo data->modelData.realVarsData[53].info
#define _$P$PRE$Pclutch3$Ptau0_max(i) $P$PRE$Pclutch3$Ptau0_max


/* sin1.y */
#define _$Psin1$Py(i) data->localData[i]->realVars[54]
#define $Psin1$Py _$Psin1$Py(0)
#define $P$PRE$Psin1$Py data->simulationInfo.realVarsPre[54]
#define $P$ATTRIBUTE$Psin1$Py data->modelData.realVarsData[54].attribute
#define $P$ATTRIBUTE$P$PRE$Psin1$Py $P$ATTRIBUTE$Psin1$Py
#define $Psin1$Py__varInfo data->modelData.realVarsData[54].info
#define $P$PRE$Psin1$Py__varInfo data->modelData.realVarsData[54].info
#define _$P$PRE$Psin1$Py(i) $P$PRE$Psin1$Py


/* step2 */
#define _$Pstep2(i) data->localData[i]->realVars[55]
#define $Pstep2 _$Pstep2(0)
#define $P$PRE$Pstep2 data->simulationInfo.realVarsPre[55]
#define $P$ATTRIBUTE$Pstep2 data->modelData.realVarsData[55].attribute
#define $P$ATTRIBUTE$P$PRE$Pstep2 $P$ATTRIBUTE$Pstep2
#define $Pstep2__varInfo data->modelData.realVarsData[55].info
#define $P$PRE$Pstep2__varInfo data->modelData.realVarsData[55].info
#define _$P$PRE$Pstep2(i) $P$PRE$Pstep2


/* Discrete Real Algebraic Vars */

/* Nonlinear Constraints For Dyn. Optimization */

/* Nonlinear Final Constraints For Dyn. Optimization */

/* Algebraic Parameter */
/* J1.J */
#define $PJ1$PJ data->simulationInfo.realParameter[0]
#define _$PJ1$PJ(i) $PJ1$PJ
#define $P$ATTRIBUTE$PJ1$PJ data->modelData.realParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PJ1$PJ $P$ATTRIBUTE$PJ1$PJ
#define $PJ1$PJ__varInfo data->modelData.realParameterData[0].info


/* J2.J */
#define $PJ2$PJ data->simulationInfo.realParameter[1]
#define _$PJ2$PJ(i) $PJ2$PJ
#define $P$ATTRIBUTE$PJ2$PJ data->modelData.realParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PJ2$PJ $P$ATTRIBUTE$PJ2$PJ
#define $PJ2$PJ__varInfo data->modelData.realParameterData[1].info


/* J3.J */
#define $PJ3$PJ data->simulationInfo.realParameter[2]
#define _$PJ3$PJ(i) $PJ3$PJ
#define $P$ATTRIBUTE$PJ3$PJ data->modelData.realParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PJ3$PJ $P$ATTRIBUTE$PJ3$PJ
#define $PJ3$PJ__varInfo data->modelData.realParameterData[2].info


/* J4.J */
#define $PJ4$PJ data->simulationInfo.realParameter[3]
#define _$PJ4$PJ(i) $PJ4$PJ
#define $P$ATTRIBUTE$PJ4$PJ data->modelData.realParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PJ4$PJ $P$ATTRIBUTE$PJ4$PJ
#define $PJ4$PJ__varInfo data->modelData.realParameterData[3].info


/* T2 */
#define $PT2 data->simulationInfo.realParameter[4]
#define _$PT2(i) $PT2
#define $P$ATTRIBUTE$PT2 data->modelData.realParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$PT2 $P$ATTRIBUTE$PT2
#define $PT2__varInfo data->modelData.realParameterData[4].info


/* T3 */
#define $PT3 data->simulationInfo.realParameter[5]
#define _$PT3(i) $PT3
#define $P$ATTRIBUTE$PT3 data->modelData.realParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$PT3 $P$ATTRIBUTE$PT3
#define $PT3__varInfo data->modelData.realParameterData[5].info


/* clutch1.cgeo */
#define $Pclutch1$Pcgeo data->simulationInfo.realParameter[6]
#define _$Pclutch1$Pcgeo(i) $Pclutch1$Pcgeo
#define $P$ATTRIBUTE$Pclutch1$Pcgeo data->modelData.realParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pcgeo $P$ATTRIBUTE$Pclutch1$Pcgeo
#define $Pclutch1$Pcgeo__varInfo data->modelData.realParameterData[6].info


/* clutch1.fn_max */
#define $Pclutch1$Pfn_max data->simulationInfo.realParameter[7]
#define _$Pclutch1$Pfn_max(i) $Pclutch1$Pfn_max
#define $P$ATTRIBUTE$Pclutch1$Pfn_max data->modelData.realParameterData[7].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pfn_max $P$ATTRIBUTE$Pclutch1$Pfn_max
#define $Pclutch1$Pfn_max__varInfo data->modelData.realParameterData[7].info


/* clutch1.mue_pos */
#define $Pclutch1$Pmue_pos data->simulationInfo.realParameter[8]

#define $Pclutch1$Pmue_pos_index(i_1,i_2)    (&$Pclutch1$Pmue_pos)[calc_base_index_dims_subs(2, 1, 2, i_1,i_2)]

/* clutch1.mue_pos[1,1] */
#define $Pclutch1$Pmue_pos$lB1$c1$rB data->simulationInfo.realParameter[8]
#define $P$ATTRIBUTE$Pclutch1$Pmue_pos$lB1$c1$rB data->modelData.realParameterData[8].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pmue_pos$lB1$c1$rB $P$ATTRIBUTE$Pclutch1$Pmue_pos$lB1$c1$rB
#define _$Pclutch1$Pmue_pos$lB1$c1$rB(i) $Pclutch1$Pmue_pos$lB1$c1$rB
#define $Pclutch1$Pmue_pos$lB1$c1$rB__varInfo data->modelData.realParameterData[8].info


/* clutch1.mue_pos[1,2] */
#define $Pclutch1$Pmue_pos$lB1$c2$rB data->simulationInfo.realParameter[9]
#define _$Pclutch1$Pmue_pos$lB1$c2$rB(i) $Pclutch1$Pmue_pos$lB1$c2$rB
#define $P$ATTRIBUTE$Pclutch1$Pmue_pos$lB1$c2$rB data->modelData.realParameterData[9].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pmue_pos$lB1$c2$rB $P$ATTRIBUTE$Pclutch1$Pmue_pos$lB1$c2$rB
#define $Pclutch1$Pmue_pos$lB1$c2$rB__varInfo data->modelData.realParameterData[9].info


/* clutch1.peak */
#define $Pclutch1$Ppeak data->simulationInfo.realParameter[10]
#define _$Pclutch1$Ppeak(i) $Pclutch1$Ppeak
#define $P$ATTRIBUTE$Pclutch1$Ppeak data->modelData.realParameterData[10].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Ppeak $P$ATTRIBUTE$Pclutch1$Ppeak
#define $Pclutch1$Ppeak__varInfo data->modelData.realParameterData[10].info


/* clutch1.phi_nominal */
#define $Pclutch1$Pphi_nominal data->simulationInfo.realParameter[11]
#define _$Pclutch1$Pphi_nominal(i) $Pclutch1$Pphi_nominal
#define $P$ATTRIBUTE$Pclutch1$Pphi_nominal data->modelData.realParameterData[11].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pphi_nominal $P$ATTRIBUTE$Pclutch1$Pphi_nominal
#define $Pclutch1$Pphi_nominal__varInfo data->modelData.realParameterData[11].info


/* clutch1.w_small */
#define $Pclutch1$Pw_small data->simulationInfo.realParameter[12]
#define _$Pclutch1$Pw_small(i) $Pclutch1$Pw_small
#define $P$ATTRIBUTE$Pclutch1$Pw_small data->modelData.realParameterData[12].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pw_small $P$ATTRIBUTE$Pclutch1$Pw_small
#define $Pclutch1$Pw_small__varInfo data->modelData.realParameterData[12].info


/* clutch2.cgeo */
#define $Pclutch2$Pcgeo data->simulationInfo.realParameter[13]
#define _$Pclutch2$Pcgeo(i) $Pclutch2$Pcgeo
#define $P$ATTRIBUTE$Pclutch2$Pcgeo data->modelData.realParameterData[13].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pcgeo $P$ATTRIBUTE$Pclutch2$Pcgeo
#define $Pclutch2$Pcgeo__varInfo data->modelData.realParameterData[13].info


/* clutch2.fn_max */
#define $Pclutch2$Pfn_max data->simulationInfo.realParameter[14]
#define _$Pclutch2$Pfn_max(i) $Pclutch2$Pfn_max
#define $P$ATTRIBUTE$Pclutch2$Pfn_max data->modelData.realParameterData[14].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pfn_max $P$ATTRIBUTE$Pclutch2$Pfn_max
#define $Pclutch2$Pfn_max__varInfo data->modelData.realParameterData[14].info


/* clutch2.mue_pos */
#define $Pclutch2$Pmue_pos data->simulationInfo.realParameter[15]

#define $Pclutch2$Pmue_pos_index(i_1,i_2)    (&$Pclutch2$Pmue_pos)[calc_base_index_dims_subs(2, 1, 2, i_1,i_2)]

/* clutch2.mue_pos[1,1] */
#define $Pclutch2$Pmue_pos$lB1$c1$rB data->simulationInfo.realParameter[15]
#define $P$ATTRIBUTE$Pclutch2$Pmue_pos$lB1$c1$rB data->modelData.realParameterData[15].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pmue_pos$lB1$c1$rB $P$ATTRIBUTE$Pclutch2$Pmue_pos$lB1$c1$rB
#define _$Pclutch2$Pmue_pos$lB1$c1$rB(i) $Pclutch2$Pmue_pos$lB1$c1$rB
#define $Pclutch2$Pmue_pos$lB1$c1$rB__varInfo data->modelData.realParameterData[15].info


/* clutch2.mue_pos[1,2] */
#define $Pclutch2$Pmue_pos$lB1$c2$rB data->simulationInfo.realParameter[16]
#define _$Pclutch2$Pmue_pos$lB1$c2$rB(i) $Pclutch2$Pmue_pos$lB1$c2$rB
#define $P$ATTRIBUTE$Pclutch2$Pmue_pos$lB1$c2$rB data->modelData.realParameterData[16].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pmue_pos$lB1$c2$rB $P$ATTRIBUTE$Pclutch2$Pmue_pos$lB1$c2$rB
#define $Pclutch2$Pmue_pos$lB1$c2$rB__varInfo data->modelData.realParameterData[16].info


/* clutch2.peak */
#define $Pclutch2$Ppeak data->simulationInfo.realParameter[17]
#define _$Pclutch2$Ppeak(i) $Pclutch2$Ppeak
#define $P$ATTRIBUTE$Pclutch2$Ppeak data->modelData.realParameterData[17].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Ppeak $P$ATTRIBUTE$Pclutch2$Ppeak
#define $Pclutch2$Ppeak__varInfo data->modelData.realParameterData[17].info


/* clutch2.phi_nominal */
#define $Pclutch2$Pphi_nominal data->simulationInfo.realParameter[18]
#define _$Pclutch2$Pphi_nominal(i) $Pclutch2$Pphi_nominal
#define $P$ATTRIBUTE$Pclutch2$Pphi_nominal data->modelData.realParameterData[18].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pphi_nominal $P$ATTRIBUTE$Pclutch2$Pphi_nominal
#define $Pclutch2$Pphi_nominal__varInfo data->modelData.realParameterData[18].info


/* clutch2.w_small */
#define $Pclutch2$Pw_small data->simulationInfo.realParameter[19]
#define _$Pclutch2$Pw_small(i) $Pclutch2$Pw_small
#define $P$ATTRIBUTE$Pclutch2$Pw_small data->modelData.realParameterData[19].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pw_small $P$ATTRIBUTE$Pclutch2$Pw_small
#define $Pclutch2$Pw_small__varInfo data->modelData.realParameterData[19].info


/* clutch3.cgeo */
#define $Pclutch3$Pcgeo data->simulationInfo.realParameter[20]
#define _$Pclutch3$Pcgeo(i) $Pclutch3$Pcgeo
#define $P$ATTRIBUTE$Pclutch3$Pcgeo data->modelData.realParameterData[20].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pcgeo $P$ATTRIBUTE$Pclutch3$Pcgeo
#define $Pclutch3$Pcgeo__varInfo data->modelData.realParameterData[20].info


/* clutch3.fn_max */
#define $Pclutch3$Pfn_max data->simulationInfo.realParameter[21]
#define _$Pclutch3$Pfn_max(i) $Pclutch3$Pfn_max
#define $P$ATTRIBUTE$Pclutch3$Pfn_max data->modelData.realParameterData[21].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pfn_max $P$ATTRIBUTE$Pclutch3$Pfn_max
#define $Pclutch3$Pfn_max__varInfo data->modelData.realParameterData[21].info


/* clutch3.mue_pos */
#define $Pclutch3$Pmue_pos data->simulationInfo.realParameter[22]

#define $Pclutch3$Pmue_pos_index(i_1,i_2)    (&$Pclutch3$Pmue_pos)[calc_base_index_dims_subs(2, 1, 2, i_1,i_2)]

/* clutch3.mue_pos[1,1] */
#define $Pclutch3$Pmue_pos$lB1$c1$rB data->simulationInfo.realParameter[22]
#define $P$ATTRIBUTE$Pclutch3$Pmue_pos$lB1$c1$rB data->modelData.realParameterData[22].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pmue_pos$lB1$c1$rB $P$ATTRIBUTE$Pclutch3$Pmue_pos$lB1$c1$rB
#define _$Pclutch3$Pmue_pos$lB1$c1$rB(i) $Pclutch3$Pmue_pos$lB1$c1$rB
#define $Pclutch3$Pmue_pos$lB1$c1$rB__varInfo data->modelData.realParameterData[22].info


/* clutch3.mue_pos[1,2] */
#define $Pclutch3$Pmue_pos$lB1$c2$rB data->simulationInfo.realParameter[23]
#define _$Pclutch3$Pmue_pos$lB1$c2$rB(i) $Pclutch3$Pmue_pos$lB1$c2$rB
#define $P$ATTRIBUTE$Pclutch3$Pmue_pos$lB1$c2$rB data->modelData.realParameterData[23].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pmue_pos$lB1$c2$rB $P$ATTRIBUTE$Pclutch3$Pmue_pos$lB1$c2$rB
#define $Pclutch3$Pmue_pos$lB1$c2$rB__varInfo data->modelData.realParameterData[23].info


/* clutch3.peak */
#define $Pclutch3$Ppeak data->simulationInfo.realParameter[24]
#define _$Pclutch3$Ppeak(i) $Pclutch3$Ppeak
#define $P$ATTRIBUTE$Pclutch3$Ppeak data->modelData.realParameterData[24].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Ppeak $P$ATTRIBUTE$Pclutch3$Ppeak
#define $Pclutch3$Ppeak__varInfo data->modelData.realParameterData[24].info


/* clutch3.phi_nominal */
#define $Pclutch3$Pphi_nominal data->simulationInfo.realParameter[25]
#define _$Pclutch3$Pphi_nominal(i) $Pclutch3$Pphi_nominal
#define $P$ATTRIBUTE$Pclutch3$Pphi_nominal data->modelData.realParameterData[25].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pphi_nominal $P$ATTRIBUTE$Pclutch3$Pphi_nominal
#define $Pclutch3$Pphi_nominal__varInfo data->modelData.realParameterData[25].info


/* clutch3.w_small */
#define $Pclutch3$Pw_small data->simulationInfo.realParameter[26]
#define _$Pclutch3$Pw_small(i) $Pclutch3$Pw_small
#define $P$ATTRIBUTE$Pclutch3$Pw_small data->modelData.realParameterData[26].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pw_small $P$ATTRIBUTE$Pclutch3$Pw_small
#define $Pclutch3$Pw_small__varInfo data->modelData.realParameterData[26].info


/* fixed.phi0 */
#define $Pfixed$Pphi0 data->simulationInfo.realParameter[27]
#define _$Pfixed$Pphi0(i) $Pfixed$Pphi0
#define $P$ATTRIBUTE$Pfixed$Pphi0 data->modelData.realParameterData[27].attribute
#define $P$ATTRIBUTE$P$PRE$Pfixed$Pphi0 $P$ATTRIBUTE$Pfixed$Pphi0
#define $Pfixed$Pphi0__varInfo data->modelData.realParameterData[27].info


/* freqHz */
#define $PfreqHz data->simulationInfo.realParameter[28]
#define _$PfreqHz(i) $PfreqHz
#define $P$ATTRIBUTE$PfreqHz data->modelData.realParameterData[28].attribute
#define $P$ATTRIBUTE$P$PRE$PfreqHz $P$ATTRIBUTE$PfreqHz
#define $PfreqHz__varInfo data->modelData.realParameterData[28].info


/* sin1.amplitude */
#define $Psin1$Pamplitude data->simulationInfo.realParameter[29]
#define _$Psin1$Pamplitude(i) $Psin1$Pamplitude
#define $P$ATTRIBUTE$Psin1$Pamplitude data->modelData.realParameterData[29].attribute
#define $P$ATTRIBUTE$P$PRE$Psin1$Pamplitude $P$ATTRIBUTE$Psin1$Pamplitude
#define $Psin1$Pamplitude__varInfo data->modelData.realParameterData[29].info


/* sin1.freqHz */
#define $Psin1$PfreqHz data->simulationInfo.realParameter[30]
#define _$Psin1$PfreqHz(i) $Psin1$PfreqHz
#define $P$ATTRIBUTE$Psin1$PfreqHz data->modelData.realParameterData[30].attribute
#define $P$ATTRIBUTE$P$PRE$Psin1$PfreqHz $P$ATTRIBUTE$Psin1$PfreqHz
#define $Psin1$PfreqHz__varInfo data->modelData.realParameterData[30].info


/* sin1.offset */
#define $Psin1$Poffset data->simulationInfo.realParameter[31]
#define _$Psin1$Poffset(i) $Psin1$Poffset
#define $P$ATTRIBUTE$Psin1$Poffset data->modelData.realParameterData[31].attribute
#define $P$ATTRIBUTE$P$PRE$Psin1$Poffset $P$ATTRIBUTE$Psin1$Poffset
#define $Psin1$Poffset__varInfo data->modelData.realParameterData[31].info


/* sin1.phase */
#define $Psin1$Pphase data->simulationInfo.realParameter[32]
#define _$Psin1$Pphase(i) $Psin1$Pphase
#define $P$ATTRIBUTE$Psin1$Pphase data->modelData.realParameterData[32].attribute
#define $P$ATTRIBUTE$P$PRE$Psin1$Pphase $P$ATTRIBUTE$Psin1$Pphase
#define $Psin1$Pphase__varInfo data->modelData.realParameterData[32].info


/* sin1.startTime */
#define $Psin1$PstartTime data->simulationInfo.realParameter[33]
#define _$Psin1$PstartTime(i) $Psin1$PstartTime
#define $P$ATTRIBUTE$Psin1$PstartTime data->modelData.realParameterData[33].attribute
#define $P$ATTRIBUTE$P$PRE$Psin1$PstartTime $P$ATTRIBUTE$Psin1$PstartTime
#define $Psin1$PstartTime__varInfo data->modelData.realParameterData[33].info


/* sin2.amplitude */
#define $Psin2$Pamplitude data->simulationInfo.realParameter[34]
#define _$Psin2$Pamplitude(i) $Psin2$Pamplitude
#define $P$ATTRIBUTE$Psin2$Pamplitude data->modelData.realParameterData[34].attribute
#define $P$ATTRIBUTE$P$PRE$Psin2$Pamplitude $P$ATTRIBUTE$Psin2$Pamplitude
#define $Psin2$Pamplitude__varInfo data->modelData.realParameterData[34].info


/* sin2.freqHz */
#define $Psin2$PfreqHz data->simulationInfo.realParameter[35]
#define _$Psin2$PfreqHz(i) $Psin2$PfreqHz
#define $P$ATTRIBUTE$Psin2$PfreqHz data->modelData.realParameterData[35].attribute
#define $P$ATTRIBUTE$P$PRE$Psin2$PfreqHz $P$ATTRIBUTE$Psin2$PfreqHz
#define $Psin2$PfreqHz__varInfo data->modelData.realParameterData[35].info


/* sin2.offset */
#define $Psin2$Poffset data->simulationInfo.realParameter[36]
#define _$Psin2$Poffset(i) $Psin2$Poffset
#define $P$ATTRIBUTE$Psin2$Poffset data->modelData.realParameterData[36].attribute
#define $P$ATTRIBUTE$P$PRE$Psin2$Poffset $P$ATTRIBUTE$Psin2$Poffset
#define $Psin2$Poffset__varInfo data->modelData.realParameterData[36].info


/* sin2.phase */
#define $Psin2$Pphase data->simulationInfo.realParameter[37]
#define _$Psin2$Pphase(i) $Psin2$Pphase
#define $P$ATTRIBUTE$Psin2$Pphase data->modelData.realParameterData[37].attribute
#define $P$ATTRIBUTE$P$PRE$Psin2$Pphase $P$ATTRIBUTE$Psin2$Pphase
#define $Psin2$Pphase__varInfo data->modelData.realParameterData[37].info


/* sin2.startTime */
#define $Psin2$PstartTime data->simulationInfo.realParameter[38]
#define _$Psin2$PstartTime(i) $Psin2$PstartTime
#define $P$ATTRIBUTE$Psin2$PstartTime data->modelData.realParameterData[38].attribute
#define $P$ATTRIBUTE$P$PRE$Psin2$PstartTime $P$ATTRIBUTE$Psin2$PstartTime
#define $Psin2$PstartTime__varInfo data->modelData.realParameterData[38].info


/* step1.height */
#define $Pstep1$Pheight data->simulationInfo.realParameter[39]
#define _$Pstep1$Pheight(i) $Pstep1$Pheight
#define $P$ATTRIBUTE$Pstep1$Pheight data->modelData.realParameterData[39].attribute
#define $P$ATTRIBUTE$P$PRE$Pstep1$Pheight $P$ATTRIBUTE$Pstep1$Pheight
#define $Pstep1$Pheight__varInfo data->modelData.realParameterData[39].info


/* step1.offset */
#define $Pstep1$Poffset data->simulationInfo.realParameter[40]
#define _$Pstep1$Poffset(i) $Pstep1$Poffset
#define $P$ATTRIBUTE$Pstep1$Poffset data->modelData.realParameterData[40].attribute
#define $P$ATTRIBUTE$P$PRE$Pstep1$Poffset $P$ATTRIBUTE$Pstep1$Poffset
#define $Pstep1$Poffset__varInfo data->modelData.realParameterData[40].info


/* step1.startTime */
#define $Pstep1$PstartTime data->simulationInfo.realParameter[41]
#define _$Pstep1$PstartTime(i) $Pstep1$PstartTime
#define $P$ATTRIBUTE$Pstep1$PstartTime data->modelData.realParameterData[41].attribute
#define $P$ATTRIBUTE$P$PRE$Pstep1$PstartTime $P$ATTRIBUTE$Pstep1$PstartTime
#define $Pstep1$PstartTime__varInfo data->modelData.realParameterData[41].info


/* External Objects */

/* Algebraic Integer Vars */
/* clutch1.mode */
#define _$Pclutch1$Pmode(i) data->localData[i]->integerVars[0]
#define $Pclutch1$Pmode _$Pclutch1$Pmode(0)
#define $P$PRE$Pclutch1$Pmode data->simulationInfo.integerVarsPre[0]
#define $P$ATTRIBUTE$Pclutch1$Pmode data->modelData.integerVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pmode $P$ATTRIBUTE$Pclutch1$Pmode
#define $Pclutch1$Pmode__varInfo data->modelData.integerVarsData[0].info
#define $P$PRE$Pclutch1$Pmode__varInfo data->modelData.integerVarsData[0].info
#define _$P$PRE$Pclutch1$Pmode(i) $P$PRE$Pclutch1$Pmode


/* clutch2.mode */
#define _$Pclutch2$Pmode(i) data->localData[i]->integerVars[1]
#define $Pclutch2$Pmode _$Pclutch2$Pmode(0)
#define $P$PRE$Pclutch2$Pmode data->simulationInfo.integerVarsPre[1]
#define $P$ATTRIBUTE$Pclutch2$Pmode data->modelData.integerVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pmode $P$ATTRIBUTE$Pclutch2$Pmode
#define $Pclutch2$Pmode__varInfo data->modelData.integerVarsData[1].info
#define $P$PRE$Pclutch2$Pmode__varInfo data->modelData.integerVarsData[1].info
#define _$P$PRE$Pclutch2$Pmode(i) $P$PRE$Pclutch2$Pmode


/* clutch3.mode */
#define _$Pclutch3$Pmode(i) data->localData[i]->integerVars[2]
#define $Pclutch3$Pmode _$Pclutch3$Pmode(0)
#define $P$PRE$Pclutch3$Pmode data->simulationInfo.integerVarsPre[2]
#define $P$ATTRIBUTE$Pclutch3$Pmode data->modelData.integerVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pmode $P$ATTRIBUTE$Pclutch3$Pmode
#define $Pclutch3$Pmode__varInfo data->modelData.integerVarsData[2].info
#define $P$PRE$Pclutch3$Pmode__varInfo data->modelData.integerVarsData[2].info
#define _$P$PRE$Pclutch3$Pmode(i) $P$PRE$Pclutch3$Pmode


/* Algebraic Integer Parameter */
/* J1.stateSelect */
#define $PJ1$PstateSelect data->simulationInfo.integerParameter[0]
#define _$PJ1$PstateSelect(i) $PJ1$PstateSelect
#define $P$ATTRIBUTE$PJ1$PstateSelect data->modelData.integerParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PJ1$PstateSelect $P$ATTRIBUTE$PJ1$PstateSelect
#define $PJ1$PstateSelect__varInfo data->modelData.integerParameterData[0].info


/* J2.stateSelect */
#define $PJ2$PstateSelect data->simulationInfo.integerParameter[1]
#define _$PJ2$PstateSelect(i) $PJ2$PstateSelect
#define $P$ATTRIBUTE$PJ2$PstateSelect data->modelData.integerParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PJ2$PstateSelect $P$ATTRIBUTE$PJ2$PstateSelect
#define $PJ2$PstateSelect__varInfo data->modelData.integerParameterData[1].info


/* J3.stateSelect */
#define $PJ3$PstateSelect data->simulationInfo.integerParameter[2]
#define _$PJ3$PstateSelect(i) $PJ3$PstateSelect
#define $P$ATTRIBUTE$PJ3$PstateSelect data->modelData.integerParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PJ3$PstateSelect $P$ATTRIBUTE$PJ3$PstateSelect
#define $PJ3$PstateSelect__varInfo data->modelData.integerParameterData[2].info


/* J4.stateSelect */
#define $PJ4$PstateSelect data->simulationInfo.integerParameter[3]
#define _$PJ4$PstateSelect(i) $PJ4$PstateSelect
#define $P$ATTRIBUTE$PJ4$PstateSelect data->modelData.integerParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PJ4$PstateSelect $P$ATTRIBUTE$PJ4$PstateSelect
#define $PJ4$PstateSelect__varInfo data->modelData.integerParameterData[3].info


/* clutch1.stateSelect */
#define $Pclutch1$PstateSelect data->simulationInfo.integerParameter[4]
#define _$Pclutch1$PstateSelect(i) $Pclutch1$PstateSelect
#define $P$ATTRIBUTE$Pclutch1$PstateSelect data->modelData.integerParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$PstateSelect $P$ATTRIBUTE$Pclutch1$PstateSelect
#define $Pclutch1$PstateSelect__varInfo data->modelData.integerParameterData[4].info


/* clutch2.stateSelect */
#define $Pclutch2$PstateSelect data->simulationInfo.integerParameter[5]
#define _$Pclutch2$PstateSelect(i) $Pclutch2$PstateSelect
#define $P$ATTRIBUTE$Pclutch2$PstateSelect data->modelData.integerParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$PstateSelect $P$ATTRIBUTE$Pclutch2$PstateSelect
#define $Pclutch2$PstateSelect__varInfo data->modelData.integerParameterData[5].info


/* clutch3.stateSelect */
#define $Pclutch3$PstateSelect data->simulationInfo.integerParameter[6]
#define _$Pclutch3$PstateSelect(i) $Pclutch3$PstateSelect
#define $P$ATTRIBUTE$Pclutch3$PstateSelect data->modelData.integerParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$PstateSelect $P$ATTRIBUTE$Pclutch3$PstateSelect
#define $Pclutch3$PstateSelect__varInfo data->modelData.integerParameterData[6].info


/* Algebraic Boolean Vars */
/* clutch1.free */
#define _$Pclutch1$Pfree(i) data->localData[i]->booleanVars[0]
#define $Pclutch1$Pfree _$Pclutch1$Pfree(0)
#define $P$PRE$Pclutch1$Pfree data->simulationInfo.booleanVarsPre[0]
#define $P$ATTRIBUTE$Pclutch1$Pfree data->modelData.booleanVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Pfree $P$ATTRIBUTE$Pclutch1$Pfree
#define $Pclutch1$Pfree__varInfo data->modelData.booleanVarsData[0].info
#define $P$PRE$Pclutch1$Pfree__varInfo data->modelData.booleanVarsData[0].info
#define _$P$PRE$Pclutch1$Pfree(i) $P$PRE$Pclutch1$Pfree


/* clutch1.locked */
#define _$Pclutch1$Plocked(i) data->localData[i]->booleanVars[1]
#define $Pclutch1$Plocked _$Pclutch1$Plocked(0)
#define $P$PRE$Pclutch1$Plocked data->simulationInfo.booleanVarsPre[1]
#define $P$ATTRIBUTE$Pclutch1$Plocked data->modelData.booleanVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$Plocked $P$ATTRIBUTE$Pclutch1$Plocked
#define $Pclutch1$Plocked__varInfo data->modelData.booleanVarsData[1].info
#define $P$PRE$Pclutch1$Plocked__varInfo data->modelData.booleanVarsData[1].info
#define _$P$PRE$Pclutch1$Plocked(i) $P$PRE$Pclutch1$Plocked


/* clutch1.startBackward */
#define _$Pclutch1$PstartBackward(i) data->localData[i]->booleanVars[2]
#define $Pclutch1$PstartBackward _$Pclutch1$PstartBackward(0)
#define $P$PRE$Pclutch1$PstartBackward data->simulationInfo.booleanVarsPre[2]
#define $P$ATTRIBUTE$Pclutch1$PstartBackward data->modelData.booleanVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$PstartBackward $P$ATTRIBUTE$Pclutch1$PstartBackward
#define $Pclutch1$PstartBackward__varInfo data->modelData.booleanVarsData[2].info
#define $P$PRE$Pclutch1$PstartBackward__varInfo data->modelData.booleanVarsData[2].info
#define _$P$PRE$Pclutch1$PstartBackward(i) $P$PRE$Pclutch1$PstartBackward


/* clutch1.startForward */
#define _$Pclutch1$PstartForward(i) data->localData[i]->booleanVars[3]
#define $Pclutch1$PstartForward _$Pclutch1$PstartForward(0)
#define $P$PRE$Pclutch1$PstartForward data->simulationInfo.booleanVarsPre[3]
#define $P$ATTRIBUTE$Pclutch1$PstartForward data->modelData.booleanVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$PstartForward $P$ATTRIBUTE$Pclutch1$PstartForward
#define $Pclutch1$PstartForward__varInfo data->modelData.booleanVarsData[3].info
#define $P$PRE$Pclutch1$PstartForward__varInfo data->modelData.booleanVarsData[3].info
#define _$P$PRE$Pclutch1$PstartForward(i) $P$PRE$Pclutch1$PstartForward


/* clutch2.free */
#define _$Pclutch2$Pfree(i) data->localData[i]->booleanVars[4]
#define $Pclutch2$Pfree _$Pclutch2$Pfree(0)
#define $P$PRE$Pclutch2$Pfree data->simulationInfo.booleanVarsPre[4]
#define $P$ATTRIBUTE$Pclutch2$Pfree data->modelData.booleanVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Pfree $P$ATTRIBUTE$Pclutch2$Pfree
#define $Pclutch2$Pfree__varInfo data->modelData.booleanVarsData[4].info
#define $P$PRE$Pclutch2$Pfree__varInfo data->modelData.booleanVarsData[4].info
#define _$P$PRE$Pclutch2$Pfree(i) $P$PRE$Pclutch2$Pfree


/* clutch2.locked */
#define _$Pclutch2$Plocked(i) data->localData[i]->booleanVars[5]
#define $Pclutch2$Plocked _$Pclutch2$Plocked(0)
#define $P$PRE$Pclutch2$Plocked data->simulationInfo.booleanVarsPre[5]
#define $P$ATTRIBUTE$Pclutch2$Plocked data->modelData.booleanVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$Plocked $P$ATTRIBUTE$Pclutch2$Plocked
#define $Pclutch2$Plocked__varInfo data->modelData.booleanVarsData[5].info
#define $P$PRE$Pclutch2$Plocked__varInfo data->modelData.booleanVarsData[5].info
#define _$P$PRE$Pclutch2$Plocked(i) $P$PRE$Pclutch2$Plocked


/* clutch2.startBackward */
#define _$Pclutch2$PstartBackward(i) data->localData[i]->booleanVars[6]
#define $Pclutch2$PstartBackward _$Pclutch2$PstartBackward(0)
#define $P$PRE$Pclutch2$PstartBackward data->simulationInfo.booleanVarsPre[6]
#define $P$ATTRIBUTE$Pclutch2$PstartBackward data->modelData.booleanVarsData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$PstartBackward $P$ATTRIBUTE$Pclutch2$PstartBackward
#define $Pclutch2$PstartBackward__varInfo data->modelData.booleanVarsData[6].info
#define $P$PRE$Pclutch2$PstartBackward__varInfo data->modelData.booleanVarsData[6].info
#define _$P$PRE$Pclutch2$PstartBackward(i) $P$PRE$Pclutch2$PstartBackward


/* clutch2.startForward */
#define _$Pclutch2$PstartForward(i) data->localData[i]->booleanVars[7]
#define $Pclutch2$PstartForward _$Pclutch2$PstartForward(0)
#define $P$PRE$Pclutch2$PstartForward data->simulationInfo.booleanVarsPre[7]
#define $P$ATTRIBUTE$Pclutch2$PstartForward data->modelData.booleanVarsData[7].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$PstartForward $P$ATTRIBUTE$Pclutch2$PstartForward
#define $Pclutch2$PstartForward__varInfo data->modelData.booleanVarsData[7].info
#define $P$PRE$Pclutch2$PstartForward__varInfo data->modelData.booleanVarsData[7].info
#define _$P$PRE$Pclutch2$PstartForward(i) $P$PRE$Pclutch2$PstartForward


/* clutch3.free */
#define _$Pclutch3$Pfree(i) data->localData[i]->booleanVars[8]
#define $Pclutch3$Pfree _$Pclutch3$Pfree(0)
#define $P$PRE$Pclutch3$Pfree data->simulationInfo.booleanVarsPre[8]
#define $P$ATTRIBUTE$Pclutch3$Pfree data->modelData.booleanVarsData[8].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Pfree $P$ATTRIBUTE$Pclutch3$Pfree
#define $Pclutch3$Pfree__varInfo data->modelData.booleanVarsData[8].info
#define $P$PRE$Pclutch3$Pfree__varInfo data->modelData.booleanVarsData[8].info
#define _$P$PRE$Pclutch3$Pfree(i) $P$PRE$Pclutch3$Pfree


/* clutch3.locked */
#define _$Pclutch3$Plocked(i) data->localData[i]->booleanVars[9]
#define $Pclutch3$Plocked _$Pclutch3$Plocked(0)
#define $P$PRE$Pclutch3$Plocked data->simulationInfo.booleanVarsPre[9]
#define $P$ATTRIBUTE$Pclutch3$Plocked data->modelData.booleanVarsData[9].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$Plocked $P$ATTRIBUTE$Pclutch3$Plocked
#define $Pclutch3$Plocked__varInfo data->modelData.booleanVarsData[9].info
#define $P$PRE$Pclutch3$Plocked__varInfo data->modelData.booleanVarsData[9].info
#define _$P$PRE$Pclutch3$Plocked(i) $P$PRE$Pclutch3$Plocked


/* clutch3.startBackward */
#define _$Pclutch3$PstartBackward(i) data->localData[i]->booleanVars[10]
#define $Pclutch3$PstartBackward _$Pclutch3$PstartBackward(0)
#define $P$PRE$Pclutch3$PstartBackward data->simulationInfo.booleanVarsPre[10]
#define $P$ATTRIBUTE$Pclutch3$PstartBackward data->modelData.booleanVarsData[10].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$PstartBackward $P$ATTRIBUTE$Pclutch3$PstartBackward
#define $Pclutch3$PstartBackward__varInfo data->modelData.booleanVarsData[10].info
#define $P$PRE$Pclutch3$PstartBackward__varInfo data->modelData.booleanVarsData[10].info
#define _$P$PRE$Pclutch3$PstartBackward(i) $P$PRE$Pclutch3$PstartBackward


/* clutch3.startForward */
#define _$Pclutch3$PstartForward(i) data->localData[i]->booleanVars[11]
#define $Pclutch3$PstartForward _$Pclutch3$PstartForward(0)
#define $P$PRE$Pclutch3$PstartForward data->simulationInfo.booleanVarsPre[11]
#define $P$ATTRIBUTE$Pclutch3$PstartForward data->modelData.booleanVarsData[11].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$PstartForward $P$ATTRIBUTE$Pclutch3$PstartForward
#define $Pclutch3$PstartForward__varInfo data->modelData.booleanVarsData[11].info
#define $P$PRE$Pclutch3$PstartForward__varInfo data->modelData.booleanVarsData[11].info
#define _$P$PRE$Pclutch3$PstartForward(i) $P$PRE$Pclutch3$PstartForward


/* Algebraic Boolean Parameters */
/* clutch1.useHeatPort */
#define $Pclutch1$PuseHeatPort data->simulationInfo.booleanParameter[0]
#define _$Pclutch1$PuseHeatPort(i) $Pclutch1$PuseHeatPort
#define $P$ATTRIBUTE$Pclutch1$PuseHeatPort data->modelData.booleanParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch1$PuseHeatPort $P$ATTRIBUTE$Pclutch1$PuseHeatPort
#define $Pclutch1$PuseHeatPort__varInfo data->modelData.booleanParameterData[0].info


/* clutch2.useHeatPort */
#define $Pclutch2$PuseHeatPort data->simulationInfo.booleanParameter[1]
#define _$Pclutch2$PuseHeatPort(i) $Pclutch2$PuseHeatPort
#define $P$ATTRIBUTE$Pclutch2$PuseHeatPort data->modelData.booleanParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch2$PuseHeatPort $P$ATTRIBUTE$Pclutch2$PuseHeatPort
#define $Pclutch2$PuseHeatPort__varInfo data->modelData.booleanParameterData[1].info


/* clutch3.useHeatPort */
#define $Pclutch3$PuseHeatPort data->simulationInfo.booleanParameter[2]
#define _$Pclutch3$PuseHeatPort(i) $Pclutch3$PuseHeatPort
#define $P$ATTRIBUTE$Pclutch3$PuseHeatPort data->modelData.booleanParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Pclutch3$PuseHeatPort $P$ATTRIBUTE$Pclutch3$PuseHeatPort
#define $Pclutch3$PuseHeatPort__varInfo data->modelData.booleanParameterData[2].info


/* torque.useSupport */
#define $Ptorque$PuseSupport data->simulationInfo.booleanParameter[3]
#define _$Ptorque$PuseSupport(i) $Ptorque$PuseSupport
#define $P$ATTRIBUTE$Ptorque$PuseSupport data->modelData.booleanParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$Ptorque$PuseSupport $P$ATTRIBUTE$Ptorque$PuseSupport
#define $Ptorque$PuseSupport__varInfo data->modelData.booleanParameterData[3].info


/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */

#define Modelica_Math_tempInterpol1_index 0

