/* Jacobians */
/* Simulation code for IntegerNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "IntegerNetwork1_functions.h"
#include "IntegerNetwork1_model.h"
#include "IntegerNetwork1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "IntegerNetwork1_12jac.h"
int IntegerNetwork1_initialAnalyticJacobianD(void* inData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}
int IntegerNetwork1_initialAnalyticJacobianC(void* inData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}
int IntegerNetwork1_initialAnalyticJacobianB(void* inData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}
int IntegerNetwork1_initialAnalyticJacobianA(void* inData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}

int IntegerNetwork1_functionJacD_column(void* data)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}
int IntegerNetwork1_functionJacC_column(void* data)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}
int IntegerNetwork1_functionJacB_column(void* data)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}
int IntegerNetwork1_functionJacA_column(void* data)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}


