/* Algebraic */
/* Simulation code for IntegerNetwork1 generated by the OpenModelica Compiler 1.9.2+dev (r24999). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "IntegerNetwork1_functions.h"
#include "IntegerNetwork1_model.h"
#include "IntegerNetwork1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#ifdef __cplusplus
extern "C" {
#endif


/* forwarded equations */
extern void IntegerNetwork1_eqFunction_29(DATA* data);
extern void IntegerNetwork1_eqFunction_30(DATA* data);
extern void IntegerNetwork1_eqFunction_31(DATA* data);
extern void IntegerNetwork1_eqFunction_33(DATA* data);
extern void IntegerNetwork1_eqFunction_35(DATA* data);
extern void IntegerNetwork1_eqFunction_36(DATA* data);
extern void IntegerNetwork1_eqFunction_37(DATA* data);
extern void IntegerNetwork1_eqFunction_38(DATA* data);
extern void IntegerNetwork1_eqFunction_39(DATA* data);
extern void IntegerNetwork1_eqFunction_41(DATA* data);
extern void IntegerNetwork1_eqFunction_42(DATA* data);
extern void IntegerNetwork1_eqFunction_43(DATA* data);
extern void IntegerNetwork1_eqFunction_44(DATA* data);
extern void IntegerNetwork1_eqFunction_45(DATA* data);

static void functionAlg_system0(DATA *data)
{
  IntegerNetwork1_eqFunction_29(data);

  IntegerNetwork1_eqFunction_30(data);

  IntegerNetwork1_eqFunction_31(data);

  IntegerNetwork1_eqFunction_33(data);

  IntegerNetwork1_eqFunction_35(data);

  IntegerNetwork1_eqFunction_36(data);

  IntegerNetwork1_eqFunction_37(data);

  IntegerNetwork1_eqFunction_38(data);

  IntegerNetwork1_eqFunction_39(data);

  IntegerNetwork1_eqFunction_41(data);

  IntegerNetwork1_eqFunction_42(data);

  IntegerNetwork1_eqFunction_43(data);

  IntegerNetwork1_eqFunction_44(data);

  IntegerNetwork1_eqFunction_45(data);
}
/* for continuous time variables */
int IntegerNetwork1_functionAlgebraics(DATA *data)
{
  TRACE_PUSH
  
  data->simulationInfo.discreteCall = 0;
  functionAlg_system0(data);
  
  TRACE_POP
  return 0;
}

#ifdef __cplusplus
}
#endif
